.ci/Jenkinsfile
Unexpectedly it did not fail in the previous PR as the `beats` stage happened a bit later rather than before the `Unit Tests` stage.
=> fix: stashed scripts should be created in the checkout stage

.ci/scripts/tag-metricbeats.sh, features/apache.feature, features/mysql.feature
so let's use 8.0.0-SNAPSHOT and tag the metricbeats one to ensure it's consumed as SNAPSHOT later on
- enable `8.0.0-SNAPSHOT` versions to be tested
- metricbeats `8.0.0-SNAPSHOT` has to be created on the fly with the docker import.
=> fix: 8.0.0 has not been released yet 

.ci/Jenkinsfile
We prefer generating the build artefacts on each git tag, not on each merge to master
=> Create releases on git tags

.ci/Jenkinsfile
The build script is located at `./cli`, so it will create the released artefacts at that path
=> (#15) Fix path for release artefacts

metricbeat-tests/elasticsearch.go, metricbeat-tests/runner_test.go
Let's use Golang's feature that overrides a type
=> (#22) Simplify searchResult interface

cli/build.sh
For some reason docker behaves differently on CI than it does locally.
My local version accepts running the `drud/golang-build-container:v1.12.7` directly, which seems to fail on CI build nodes.
```shell
Client: Docker Engine - Community
Version:           19.03.2
API version:       1.40
Go version:        go1.12.8
Git commit:        6a30dfc
Built:             Thu Aug 29 05:26:49 2019
OS/Arch:           darwin/amd64
Experimental:      false
Server: Docker Engine - Community
Engine:
Version:          19.03.2
API version:      1.40 (minimum version 1.12)
Go version:       go1.12.8
Git commit:       6a30dfc
Built:            Thu Aug 29 05:32:21 2019
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          v1.2.6
GitCommit: …
```
=> (#46) Use qualified name for packr builder's Docker Hub image

cli/services/manager.go, metricbeat-tests/runner_test.go, metricbeat-tests/test_utils.go
This PR adds the ability to use pseudo-randomised index name for a test suite, storing the index at test suite level.
It will allow to execute each test suite in a separated index, so there would be no document collisions from test suite to test suite.
=> (#44) random index name

metricbeat-tests/Makefile, metricbeat-tests/README.md
Remove the `FLAG` environment variable used in the Makefile, and
automatically add the `--tags` flag if a feature is specified when
running functional tests.
=> Automatically set the tags flags when needed

cli/config/compose/services/vsphere.yml, metricbeat-tests/configurations/vsphere.yml, metricbeat-tests/features/vsphere.feature
This PR adds vSphere to the list of services that could be used to run end-to-end tests. We decided to add it as an example of how easy is the addition of a new integration, without adding no code, just configuration.
It's important to start adding services to the POC, so that we can convert the POC into a real tool. Covering more services follows that path.
When running the tests, and because of the nature of the Docker image for vSphere, which takes too long to start up, we need to instrument test execution to wait for it longer. The test tool supports modifying default timeout via an environment variable.
- `OP_QUERY_MAX_ATTEMPTS`: number of attempts for a elasticsearch query
- `OP_RETRY_TIMEOUT`: seconds between each attempt
- `OP_METRICBEAT_FETCH_TIMEOUT`: seconds that metricbeat …
=> (#52) Add tests for vSphere

cli/cmd/run.go, cli/config/compose/stacks/metricbeat.yml, metricbeat-tests/features/apache.feature, metricbeat-tests/features/metricbeat.feature, metricbeat-tests/features/mysql.feature, metricbeat-tests/features/redis.feature, metricbeat-tests/features/vsphere.feature, metricbeat-tests/runner_test.go, metricbeat-tests/service_common_test.go
It adds the ability to run a Elastic stack with a specific version, using a flag in the CLI side of this tool.
Besides that, we are simplifying the test framework, moving the version matrix for metricbeat and elastic stack to the automation tool (local or on CI). We will read the metricbeat version from an environment variable (`OP_METRICBEAT_VERSION`).
It will allow iterating faster, as the test framework will just run tests for one single version of the stack and metricbeat. It will be a responsibility of the automation tool to define the values used for metricbeat and the stack.
=> 57 read stack from environment

.ci/functionalTests.groovy, .ci/scripts/functional-test.sh, .gitignore, metricbeat-tests/README.md
It adds support to passing stack and metricbeat versions when running the `functional-tests.sh` script.
It simplifies test execution, doing as the CI does
=> Support executing one-shot script for functional tests

.ci/scripts/golangci-lint.sh, .pre-commit-config.yaml, cli/services/manager.go, metricbeat-tests/go.mod
It ensures that for only one service it gets the proper compose file to operate it.
Besides that, it fixes a dependency issue (typo) and also fixes the precommit CI step, which was always failing on PRs (see #74)
Fixes #71 
Fixes #74
Fixes #75
=> (#71) Fix stop service, which is a compose with only one service

.ci/scripts/install-dependencies.sh
A dependency started to fail on CI and we enabled not using the network when fetching it.
From `go get` docs:
>The -u flag instructs get to use the network to update the named packages
and their dependencies. By default, get uses the network to check out
missing packages but does not use it to look for updates to existing packages
CI was not able to get dependencies, failing before any test execution
=> Do not use the network when fetching Go dependencies

cli/config/compose/services/apache.yml, cli/config/compose/services/kafka.yml, cli/config/compose/services/mysql.yml, cli/config/compose/services/redis.yml, metricbeat-tests/features/apache.feature, metricbeat-tests/features/mysql.feature, metricbeat-tests/features/redis.feature
It uses `integrations-ci` Docker registry in the integrations supported by this PoC.
Besides that, it adds the proper versions of those integrations, as seen in this Jenkins build: https://apm-ci.elastic.co/blue/organizations/jenkins/beats%2Fbeats-docker-images-pipeline/detail/beats-docker-images-pipeline/84/pipeline/58
We will be using the same images than those used in Beats development, so we will be testing the same.
- Closes #80
- Closes #81
=> Use versions from integrations-ci

cli/cmd/sync.go, cli/internal/io.go, cli/internal/state.go
It adds a method to sanitize the compose files that come from the Beats repo, removing the `build` section under any service.
Besides that, we fixed an issue that affected the creation of parent directories when copying files, also overridding the files and directories in this process.
The Integrations compose files come with a `build` section, because it's used in there to build the images, but we do not want to use that feature, as it forces the docker-compose commands to have access to the the file system paths that are present in the `build.context` block.
We proposed those paths to be configurables (https://github.com/elastic/beats/pull/16311), but we realised it's better/easier to remove them for our internal purpose.
- Superseds https://github.com/elastic/beats/pull/16311
- Closes …
=> feat: Support removing certain blocks from Beats Integrations compose files

.ci/Jenkinsfile
It installs Go in the each linux machine used for releasing each supported platform
If Go is not installed in the workers, then the Go build command will fail 🤷‍♂ 
See https://apm-ci.elastic.co/blue/organizations/jenkins/beats%2Fpoc-metricbeat-tests-poc-mbp/detail/v0.1.0-rc9/1/pipeline
- Closes #46
=> fix: make sure parallel release stages have Go installed

.ci/.package.yaml, .ci/Jenkinsfile, cli/Makefile, cli/scripts/build-cli.sh
It builds the CLI inside a Docker container from Makefile.
Besides that, we are removing Windows compilation because of:
>/go/pkg/mod/github.com/docker/docker@v0.7.3-0.20190506211059-b20a14b54661/pkg/system/filesys_windows.go:111:24: cannot use uintptr(unsafe.Pointer(&sd[0])) (type uintptr) as type *"golang.org/x/sys/windows".SECURITY_DESCRIPTOR in assignment
Using a Docker container for running tools avoid messing things up with the environment.
~~- [ ] Generation of windows binaries failing~~
=> fix: set proper Go environment on release

.ci/scripts/functional-test.sh, cli/Makefile, metricbeat-tests/Makefile, metricbeat-tests/README.md
It defines the environment in a proper manner so that the CI scripts AND the Makefile works properly.
It was not using the workspace for docker build after 300810ed0e8f0ed985216470ac2c15fb54fec9cc, so it was not possible to build the CLI from the tests side.
The CI error can be found here: as you can see here: https://apm-ci.elastic.co/blue/organizations/jenkins/beats%2Fpoc-metricbeat-functional-tests/detail/poc-metricbeat-functional-tests/131/pipeline/
=> fix: Functional tests execution in CI

.ci/scripts/functional-test.sh, e2e/Makefile, e2e/README.md, e2e/features/apm/helm.feature, e2e/features/filebeat/helm.feature, e2e/features/metricbeat/apache.feature, e2e/features/metricbeat/helm.feature, e2e/features/metricbeat/metricbeat.feature, e2e/features/metricbeat/mysql.feature, e2e/features/metricbeat/vsphere.feature, e2e/metricbeat-poc.md, e2e/runner_test.go
It uses `go test` instead of the godog binary, so we are removing its installation in the Makefile.
We also remove all gherkin tags supporting godog's filters, creating a configuration layer (a map) with the supported modules. This is needed because at this moment godog is executing all life cycle methods (befores and afters), even when filtering by tag.
We are replacing the usage of tags with the arguments passed to the `go test` command:
```shell
$ go test -v --godog.format pretty redis mysql apache
```
With this configuration we are able to define which FeatureContext functions are contributed to the test runner, so inspecting the arguments we will be able to check if it's a supported module. This way, only those contributors of interest will be added to the test suite, only executing …
=> Use "go test" as test runner

e2e/elasticsearch.go
It exports a struct that is used as a return type in an exported method
Although it's possible, and we do not use that type outside the package, it is weird
=> chore: export return type of an exported function

e2e/_suites/ingest-manager/features/ingest_manager.feature, e2e/_suites/ingest-manager/stand-alone.go
It simplifies the specs for the Deploy stand-alone agent, removing the steps that are already part of the test framework.
To make it even clearer, we mention it in the description of the Feature, so any casual reader would understand it.
We make sure that Kibana and Elasticsearch are running, because are part of the BeforeSuite life cycle hook of the godog (cucumber) test runner. On the other hand, we could keep the step and perform a quick check that both instances are running. I'd see this valid, although redundant, as they represent the explicit runtime dependencies for the agent.
Once approved (and merged) we can continue with the implementation steps
=> chore: simplify deploy stand-alone specs

e2e/_suites/ingest-manager/README.md, e2e/_suites/ingest-manager/ingest-manager_test.go
It adds to the ingest-manager docs the instructions on how to setup the local computer for running the tests
Knowledge sharing!
- Closes #138
Document install steps for Windows
=> docs: Document how to install the development tools

.ci/Jenkinsfile
It uses the `isGitRegionMatch` step to run those test suites that were modified by a PR
It will also check that the provisioning library is modified. This way,
a test suite will be added to the parallel execution in the following
conditions:
1) the "e2e/_suites/${suite}" has been modified
2) the ".ci" dir has been modified
3) the "cli" dir has been modified
4) any of the test helper files have been modified+
=> feat(ci): only run test suites when modified

.ci/e2eTestingIngestManagerDaily.groovy, .ci/jobs/defaults.yml, .ci/jobs/e2e-testing-beats.yml, .ci/jobs/e2e-testing-ingest-manager-daily.yml, .ci/jobs/e2e-testing-mbp.yml
It adds a regular Jenkins pipeline that triggers the already existing job for the e2e tests, customising the execution with predefined input parameters, setting the ingest-manager test suite to be run.
It's also possible to manually run this job with different configurations:
- Go version
- Stack version
- Retry timeout
- Log level
If not set, it will use the triggered build's defaults for configuration
Besides that, all JJBB definitions have been added here, as we opened a request to infra to discover JJBB jobs in this repo.
We want to schedule the execution of the ingest-manager tests in a daily manner.
JJBB definitions in the same repo ==> self-content repo ==> 👍 
- Closes #142
=> chore(ci): add a pipeline for the daily trigger of the ingest manager tests

.ci/Jenkinsfile, .ci/e2eTestingIngestManagerDaily.groovy
It adds a boolean param to control if the isGitRegionMatch takes effect. This param, which is defined in the downstream job, will be set as TRUE by the scheduled caller job, bein FALSE by default
We will trigger the job from the scheduled one setting the parameter to TRUE
Otherwise the isGitRegionMatch won't detect any change for triggered, scheduled builds.
- Fixes #144
=> fix(ci): control git checks using a parameter

.ci/Jenkinsfile, .ci/e2eTestingIngestManagerDaily.groovy
It renames the variables using the `force` prefix, as it's a common pattern of us.
Consistency matters
- Relates #144
=> chore(ci): rename variable for controlling git checks

.ci/e2eTestingHelmDaily.groovy, .ci/e2eTestingIngestManagerDaily.groovy, .ci/jobs/e2e-testing-helm-daily.yml
It adds a JJBB descriptor for the scheduled job, using a groovy file for the pipeline.
In this pipeline we define the input arguments needed by the Helm charts test suite: Kind version, Kubernetes version, Helm version and Helm charts version
We want daily feedback about this test suite
- Closes #151
=> feat: schedule running Helm charts once a day

.ci/jobs/defaults.yml, .ci/jobs/e2e-folder.yml, .ci/jobs/e2e-testing-beats.yml, .ci/jobs/e2e-testing-helm-daily.yml, .ci/jobs/e2e-testing-ingest-manager-daily.yml, .ci/jobs/e2e-testing-mbp.yml
It creates a folder in the beats-ci to have all e2e jobs in a single view
The core business for this project is to support the Beats team in triggering the e2e tests directly from the Beats CI, and that was not possible, or difficult to achieve hosting the tests in the APM CI
- Closes #155
=> chore: move jobs to the Beats-CI

.ci/scripts/functional-test.sh, cli/Makefile, cli/shell/shell.go, e2e/Makefile, e2e/README.md
It directly uses Go instead of the compiled binary when running the tests, and for that we use a docker image to ensure the proper version of Go. Therefore, the Make command that downloaded the Beats repo (sync-integrations) has been moved from the "e2e" dir to the "cli".
This Make target will mount a volume to the Git download dir, under CLI's workspace (~/.op), so that the Docker image shares it to put there the files.
Running the synchronisation process from the binary is not needed, because we can invoke Go directly. We only used it to download Beats git repo, so we can reduce complexity because of removing that build time. As a consequence, the build time will be reduced.
=> chore: do not build the binary when running tests

.ci/Jenkinsfile, .ci/functionalTests.groovy
It switches to use a fixed version of the OS when requesting a CI worker.
Using linux on Beats CI could retrieve Debian or Ubuntu in different OS versions, which could come with different runtime setups. And this is causing some randomw errors in the builds, i.e. not finding Go installation.
=> fix(ci): use fixed versions for CI workers

.ci/Jenkinsfile, .ci/functionalTests.groovy
Replaces the `ubuntu-1804` label with `ubuntu-18.04` one.
The first label does not exist
=> fix(ci): use proper labels

.ci/jobs/e2e-testing-helm-daily.yml, .ci/jobs/e2e-testing-ingest-manager-daily.yml, .ci/jobs/e2e-testing-mbp.yml
It replaces old credentials with the new ones, which are for a dedicated Beats CI account.
Github quotas
- Relates https://github.com/elastic/beats/pull/19852
=> chore(ci): use credentials for the new Beats CI GH app

.ci/Jenkinsfile, .ci/scripts/functional-test.sh, cli/Makefile, cli/cmd/sync.go, cli/config/config.go, cli/go.mod, cli/shell/shell.go, e2e/Makefile, e2e/README.md
~~It expands the volume used to download the Beats repo, so the entire workspace fir is used, making possible for the integrations compose files to be present in the host.~~
It reverts back all commits to the change that replaced using the binary.
~~The sync command was getting compose files out of the container. This was causing the CI, and local execution using the Make command, to not find the compose files for the integrations, causing consistent failures.~~
We realised that using Docker to run Go will cause that any file generated inside the Docker container will have same permissions as inside the container (root). We tried to use same user than in the host inside the container, but we found this error: https://github.com/golang/go/issues/26280.
Applying this code …
=> Revert to using the binary to generate integrations files

.ci/jobs/e2e-testing-helm-daily.yml, .ci/jobs/e2e-testing-ingest-manager-daily.yml, .ci/jobs/e2e-testing-integrations-daily.yml, .ci/jobs/e2e-testing-mbp.yml
We introduced in 0ed1a29963465aa730cdd30c228c180180bd1b84 the new beats-ci GH user, but it should apply only to MBP. In this PR we are partially reverting that commit to keep the new credential only in the MBP.
Besides, we detected the notification context for the MBP should include information about the project itself, not only the instance.
We hit GH API quotas, and projects were not built. Related to the notification context, we want to provide more context in the github checks, avoiding being overriden by other checks.
- Relates https://github.com/elastic/e2e-testing/pull/166
=> fix: use proper GH credentials

.ci/jobs/e2e-testing-mbp.yml
It uses the previous Beats-CI token, instead of the new github app one.
The webhooks for the github app token are not delivered so the CI is not notified about new PRs and changes. Besides that, scheduled builds triggering the MBP will fail with an error: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/57/pipeline:
```json
{"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
```
=> fix: move back to using the beats-ci token

e2e/_suites/ingest-manager/features/fleet_mode_agent.feature
It adds an existing step to the unenroll scenario, checking the elastic-agent process is there.
We want to ensure the elastic-agent process is still running in the host, as described in the original test script
- Relates #149
=> feat: enrich the unenroll scenario

cli/config/compose/services/centos/docker-compose.yml, e2e/_suites/ingest-manager/fleet.go, e2e/_suites/ingest-manager/ingest-manager_test.go
It changes the compose file for the vanilla box defining a volume to mount the elastic-agent binary on it. We will use environment variables to configure the src and target of the volume.
That way, we will download the agent binary to a temporary dir before the test suite runs (only once), and will remove it from the file system after the tests suite runs.
It will reduce the number of HTTP connections to download the binary to 1, compared to one for each scenario installing an agent. It usually takes from 5 to 10 seconds, so the gain will be (in average) 7'5 times the number of scenarios (6 at this moment).
It will also bring reliability, because the download of the binary is done from the test runner, so it has the retry-with-backoff capabilities, instead of running it from inside the …
=> feat: download the agent once, mounting it as a volume

e2e/_suites/ingest-manager/fleet.go, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/stand-alone.go
It uses the hostname to get the status of the agent, because the hostname value is used as agentID. That way we are able to look up the status of the agent in the response of the API call, which returns a JSON with the list of agents including their active status.
We also revoke/remove the token that is created for the enrollment process (we create it on each scenario)
It moves from a testing approach that is based in the existence of only one agent, to an approach that is based in the status of a specific agent (identified by hostname). We need this change because the API should be able to unenroll/remove an agent whenever the container representing it is removed (docker-compose down), and this is not currently happening.
- Relates https://github.com/elastic/beats/issues/20006
- Relates …
=> fix: use the status of the agent by hostname

.ci/e2eTestingHelmDaily.groovy, .ci/e2eTestingIngestManagerDaily.groovy, .ci/e2eTestingIntegrationsDaily.groovy
It forces the downstream job to skip for git changes
Because otherwise the triggered job, which uses master, won't discover changes in the execution, not triggering the e2e jobs. I.e. https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/69/pipeline/173/
- Fixes #182
=> fix: do not check for modifications in the downstream job

.ci/Jenkinsfile, e2e/_suites/ingest-manager/README.md, e2e/utils.go
This PR adds a new parameter to the Jenkinsfile, which will set an environment variable to the pipeline. This new parameter will allow the user to configure which version of the Agent will be installed during a build. By default, this variable will be empty, which means the tests will use the agent for the current version (i.e. 8.0.0-SNAPSHOT)
In this PR we are refactoring the logic to get that variable, and instead of partially expecting a hash and build the download URL from it, we expect the entire download URL to be configurable.
This flexibility in the definition of the download URL will help in executing the job with multiple values, also simplifying the calculation of the URL.
Besides that, triggering a job with a specific version of the agent will be simpler, as it would be just a …
=> chore(ci): support overriding the Elastic Agent binary to be used on CI

.ci/Jenkinsfile, e2e/_suites/ingest-manager/ingest-manager_test.go
It adds a Jenkins param and environment variable per test suite using this variable, so that the execution of the e2e tests is able to use the current test suite to read the proper environment variable.
We want to decouple the versions used for metricbeat and ingest-manager, as the second one uses 8.0.0-SNAPSHOT by default.
- Closes #199
=> chore: support setting stack version per test suite on Jenkins

.ci/Jenkinsfile, .ci/e2eTestingHelmDaily.groovy, .ci/e2eTestingIngestManagerDaily.groovy, .ci/e2eTestingIntegrationsDaily.groovy
It adds a boolean input parameter to the MBP job, to skip the exeuction of the pre-submit stage: unit tests and pre-commit. We will set this parameter as `false` by default, but the sheduled jobs will set it as `true`.
Besides that, we are simplifying the usage of stash/unstash, having only one element: source.
We want to speed up the build for the scheduledd jobs, and the pre-commit stage takes a big part of the entire build time, mosty fetching Go depenencies.
- Closes #184 
```gherkin
Scenario: skip pre-submit checks on scheduled jobs
When a scheduled job is triggered
Then the downstream pipeline must skip the pre-submit stage
```
=> chore: do not run pre-submit tests on scheduled builds

.ci/Jenkinsfile, e2e/_suites/ingest-manager/README.md, e2e/_suites/ingest-manager/stand-alone.go, e2e/utils.go
First, this PR renames the env var for the agent version, as it could be consumed by both the stand-alone mode and fleet mode.
Then, the calculation of the bucket is modified to prepend the ID of the PR, identified by the value of the above environment value.
This will enable the CI to test for PRs, triggering the build and setting the following input arguments:
- ELASTIC_AGENT_USE_CI_SNAPSHOTS="true"
- ELASTIC_AGENT_VERSION="pr-123"
- runTestsSuite=ingest-manager
And this will enable contributing a GH check in the PR for the e2e test suite, executing the tests right after the binaries are pushed by the packaging job.
Execute:
```shell
$ OP_LOG_LEVEL=DEBUG ELASTIC_AGENT_USE_CI_SNAPSHOTS=true ELASTIC_AGENT_VERSION=pr-20356 godog -t "fleet && enroll"
```
- Relates #204
=> chore: support downloading snapshots for PRs in fleet mode

cli/config/compose/services/centos-systemd/docker-compose.yml, cli/config/compose/services/debian-systemd/docker-compose.yml, cli/config/compose/services/debian/docker-compose.yml, e2e/_suites/ingest-manager/features/fleet_mode_agent.feature, e2e/_suites/ingest-manager/fleet.go, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/services.go, e2e/utils.go
It adds a new Cucumber scenario for restarting an agent, checking for backend proccesses (elastic-agent, filebeat and metricbeat) are back to life.
Because of the benefits of BDD, we are reusing all steps but one, the one to restart a container (we used the word `host` to mean whatever type of host, in our case a container). This new step is invoking `docker-compose restart` for the service representing the agent (a Centos container).
This restart scenario caused a big, major change: instead of using TAR as the installation process, we want to test packages (RPM and DEB), called persistent installers. For that reason we have abstracted the installer to a separate struct, which will manage the life cycle of the installation process. There will be an installer for Centos, Centos using …
=> feat: add a step for restarting the elastic-agent in fleet-mode

e2e/_suites/ingest-manager/README.md
totally fixes the word 'coulf' to be 'could'.
=> typo - not urgent - but totally fun to fix

e2e/_suites/ingest-manager/fleet.go
If I'm reading this err code right, then this fixes a small typo / omission in the relating debug line.
I was actually debugging this are and found the line... and it confused me, but only for a second as I was sure it must be inverted!  :)  Easy fix.
here is what the log line looks like:
=> fix typo in token delete debug statement

e2e/_suites/ingest-manager/fleet.go
- chore: increase timeout for listing online agents (4e357c90)
=> chore: increase timeout for listing online agents (4e357c90) backport for 7.9.x

e2e/_suites/ingest-manager/fleet.go, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/services.go
It uses systemctl to stop the elastic-agent service
Thanks to @michalpristas, we also noticed that the order of the execution matters. In the test framework we did (in this particular order):
1. a centos container is spun up
2. we copied the RPM installer and install it
3. we execute systemctl enable
4. we execute systemctl start
5. we create a fleet token
6. we enrol the agent with that token
7. we check the online status <- here it fails
We moved 4. after 6., so that the service is actually started AFTER the enrollment process. Can we check with @dedemorton if this is documented?
Let's stop services using the process manager, and fix a possible issue with how the service must be installed/configured.
- Relates https://github.com/elastic/beats/issues/20759
=> fix: use systemctl to stop the agent process, otherwise pkill

e2e/_suites/ingest-manager/fleet.go, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/services.go
- fix: use systemctl to stop the agent process, otherwise pkill (f64c1cbe)
- fix: start the agent service ater the enrollment (c6b8d858)
=> [7.9.x] fix: use systemctl to stop the agent process, otherwise pkill (f64c1cbe) | fix: start the agent service ater the enrollment (c6b8d858)

cli/services/manager.go, e2e/_suites/ingest-manager/README.md, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
This PR allows the ingest-manager services to be alive after a test run when DEVELOPMENT_MODE variable is set to TRUE.
As a side effect, we are optimising the logs for the removeService method, removing duplicated logs
This will allow inspecting services after a test is run without modifying the code adding a long sleep. On the other hand, we will have to stop/remove those services manuallly. If a new test is run, the service will be recreated (because we use "docker-compose up" under the hood)
Export DEVELOPMENT_MODE=true and run godog tests for ingest manager: the Centos/Debian agent must be present after test run.
- Relates #229
=> chore: optimise removing services

.ci/Jenkinsfile, .ci/e2eTestingIngestManagerDaily.groovy, cli/services/manager.go, e2e/_suites/ingest-manager/README.md, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: use debug in CI by default (6341a9a7)
- chore: support notifying on green builds using a param (dac43608)
- chore: notify green builds for ingest management scheduled builds (e9bbb2c3)
- chore: optimise removing services (#241)
=> [7.9.x] notify green builds for ingest-manager

.ci/Jenkinsfile
It catches any error in the pre-commit stage, marking the stage as UNSTABLE but not failing the build.
Because of the project layout, with two different projects under the same repo, the pre-commit step catches lint errors with a lot of frequency, even though the local lint and compilation process passes. We want the build to have more reliability, and the lint flakiness could reduce it.
=> fix: fail the stage but not the build with pre-commit failures

.ci/Jenkinsfile
- fix: fail the stage but not the build with pre-commit failures (#247)
=> fix: fail the stage but not the build with pre-commit failures (#247) backport for 7.9.x

e2e/_suites/ingest-manager/features/fleet_mode_agent.feature, e2e/_suites/ingest-manager/fleet.go, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/services.go, e2e/_suites/ingest-manager/stand-alone.go, e2e/utils.go
- feat: run fleet scenarios for both Centos and Debian (#246)
- fix: use Scenario Outline (#250)
=> feat: run fleet scenarios for both Centos and Debian (#246) | fix: use Scenario Outline (#250) backport for 7.9.x

.ci/Jenkinsfile
- fix: do not update state status when catching lint errors (#255)
=> fix: do not update state status when catching lint errors (#255) backport for 7.9.x

.ci/Jenkinsfile, e2e/.gitignore, e2e/Makefile, e2e/README.md
This PR generates a website with the HTML representation of the gherkin feature files, so that it's easier to consume them.
The generation is done using picklesdoc (http://docs.picklesdoc.com), a Windows application that parses Gherkin files and generates an HTML output. We have wrapped the Windows binary into a Docker image (using mono), and pushing this image to our registry:
- docker.elastic.co/observavbility-ci/picklesdoc:2.21.0 (Dockerfile here: https://github.com/Xeli/picklesdoc-docker/blob/master/Dockerfile)
Because this image uses a Windows binary, we wrapped the execution into a Make target, which massages the output to remove bad slashes in the generated paths (i.e. the root index.html file).
We want to provide an easy way to consume the specification, shareable and …
=> docs: generate a website with the specs

.ci/jobs/e2e-testing-helm-daily-mbp.yml
- fix: suppress scm triggering for all branches (#265)
=> fix: suppress scm triggering for all branches (#265) backport for 7.9.x

.ci/Jenkinsfile, e2e/.gitignore, e2e/Makefile, e2e/README.md
- docs: generate a website with the specs (#261)
=> docs: generate a website with the specs (#261) backport for 7.9.x

.ci/jobs/e2e-testing-integrations-daily-mbp.yml
- fix: typo in job name (#276)
=> fix: typo in job name (#276) backport for 7.9.x

e2e/_suites/ingest-manager/features/agent_endpoint_integration.feature, e2e/_suites/ingest-manager/fleet.go
This PR updates the specs/scenarios removing any reference to the default policy, because since #279 we are creating a policy for each scenario.
This change does not affect the tests, as we are internally using the policyID, so it should work as expected.
Run:
```shell
$ cd e2e/_suites/ingest-manager
$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true godog -t "agent_endpoint_integration"
```
- Relates #279
=> fix: remove references to the default policy

e2e/_suites/ingest-manager/features/agent_endpoint_integration.feature, e2e/_suites/ingest-manager/fleet.go, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/stand-alone.go, e2e/go.mod
- feat: support creating (and removing) a policy for each scenario (#279)
- fix: remove references to the default policy (#281)
=> feat: support creating (and removing) a policy for each scenario (#279) | fix: remove references to the default policy (#281) backport for 7.9.x

e2e/_suites/ingest-manager/features/agent_endpoint_integration.feature, e2e/_suites/metricbeat/features/apache.feature, e2e/_suites/metricbeat/features/metricbeat.feature, e2e/_suites/metricbeat/features/mysql.feature, e2e/_suites/metricbeat/features/redis.feature, e2e/_suites/metricbeat/features/vsphere.feature
It removes the "Check" word froom scenario names, using a higher level of asbtraction.
The words test, verif, check are considered  bad words by gherkin-lint
See https://www.rubydoc.info/gems/gherkin_lint/0.1.2/GherkinLint%2FBadScenarioName:lint
```shell
$ make -C e2e lint
BadScenarioName - Prefer to rely just on Given and When steps when name your scenario to keep it stable
e2e/_suites/metricbeat/features/vsphere.feature (5): vSphere.Check vSphere-<vsphere_version> is sending metrics to Elasticsearch without errors
BadScenarioName - Prefer to rely just on Given and When steps when name your scenario to keep it stable
e2e/_suites/metricbeat/features/redis.feature (5): Redis.Check Redis-<redis_version> is sending metrics to Elasticsearch without errors
BadScenarioName - Prefer to rely just …
```
=> fix: do not use bad words in scenarios

.ci/Jenkinsfile
- chore: use base name for flaky reporter (#292)
=> chore: use base name for flaky reporter (#292) backport for 7.9.x

e2e/_suites/ingest-manager/stand-alone.go
- fix: use not hidden index name (#289)
- Needs #285
=> fix: use not hidden index name (#289) backport for 7.9.x

e2e/_suites/ingest-manager/features/agent_endpoint_integration.feature, e2e/_suites/metricbeat/features/apache.feature, e2e/_suites/metricbeat/features/metricbeat.feature, e2e/_suites/metricbeat/features/mysql.feature, e2e/_suites/metricbeat/features/redis.feature, e2e/_suites/metricbeat/features/vsphere.feature
- fix: do not use bad words in scenarios (#286)
=> fix: do not use bad words in scenarios (#286) backport for 7.9.x

.ci/Jenkinsfile
- chore: cancel previous running builds when a PR is updated (#300)
=> chore: cancel previous running builds when a PR is updated (#300) backport for 7.9.x

cli/docker/docker.go, e2e/_suites/ingest-manager/fleet.go, e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/services.go, e2e/_suites/ingest-manager/stand-alone.go
As the native `docker logs CONTAINER` is not retrieving the agent logs, we have to inspect the internals of the agent too fetch the log. For that reason this PR adds a function to retrieve the logs from the internals of the elastic-agent structure, and to achieve it we have to get the build hash of the agent, using a short version of that hash to calculate the path to the log file.
It will be the installer struct the responsible for doing these tasks, as it knows the internals of the agent.
The way we consume this logs is in the afterScenario test life cycle hook, right before removing the docker service representing the agent.
We want to troubleshoot problems on CI
```shell
$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true godog -t "fleet_mode && start-agent"
```
- Closes #298
The backport to …
=> feat: log elastic-agent logs before terminating its container

.ci/Jenkinsfile
Uses the new channel for bot notifications
Less noise in a human-friendly channel
- Closes #307
=> chore: update slack channel

e2e/_suites/ingest-manager/services.go, e2e/_suites/ingest-manager/stand-alone.go, e2e/utils.go
As a result of https://github.com/elastic/beats/pull/20903, we detected the URLs to get the snapshots needed to be updated. This PR is addressing this need, including some refactors:
- move code specific to the elastic-agent to the downloadAgentBinary method, instead of overloading the generic one that uses the artifactory to get the artifacts (separation of concerns). This change will enable using a default value for the version, because snapshots for PRs hardcode the target version in the file name (i.e. `/pull-requests/pr-21100/elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm`).
- fix the download process from a GCP bucket: we only used the first page in the response, being now possible to paginate over the different  pages in the response following the `nextPageToken` attribute in the …
=> chore: update GCP bucket calculation

.ci/Jenkinsfile
It adds three input parameters to the Jenkinsfile, empty by default, which will be populated by upstream jobs (more specifically PRs triggering this job).
It will post the check after the job is finished, using the upstream parameters to configure the check.
It will allow Beats PRs to be notified about the E2E tests, providing a fast feedback about the status of the original PR.
>We'd like to warn about the risks of merging the upstream PR without checking the results: we must wait for all checks to be green/passing.
- Closes #314 
- Relates https://github.com/elastic/beats/pull/21100
=> feat: support contributing a GH check to the upstream job that triggered the build

.ci/Jenkinsfile
- feat: support contributing a GH check to the upstream job that triggered the build (#315)
=> feat: support contributing a GH check to the upstream job that triggered the build (#315) backport for 7.9.x

e2e/_suites/ingest-manager/services.go
It uses the agent base version (defined by the target branch) as file name of the cloud-bucket-stored artifact
The calculation was wrong after a minor (==wrong) refactor
```shell
$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true ELASTIC_AGENT_USE_CI_SNAPSHOTS=true ELASTIC_AGENT_VERSION=pr-21100 godog -t "fleet_mode && enroll"
```
- Relates #306
=> fix: calculate bucket path properly

e2e/_suites/ingest-manager/services.go
- fix: calculate bucket path properly (#318)
=> fix: calculate bucket path properly (#318) backport for 7.9.x

e2e/_suites/ingest-manager/services.go
It fails test execution (error level > 0) if the runtime dependencies represented by the agent binaries cannot be downloaded.
If this error is not handled, the test ramework will continue using an empty file as the binary, causing not real errors.
Try to download a non existing binary:
```shell
$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true ELASTIC_AGENT_USE_CI_SNAPSHOTS=true ELASTIC_AGENT_VERSION=pr-21asdasd godog -t "fleet_mode && enroll"
```
Expected output:
```
ERRO[0034] Could not download the binary for the agent   arch=x86_64 artifact=elastic-agent error="Reached the end of the pages and the pull-requests/pr-21asdasd/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm object was not found for the beats-ci-artifacts bucket" extension=rpm os=linux version=pr-21asdasd
FATA[0036] Sorry, we …
```
=> chore: fail warm-up if the installers could not be downloaded

.ci/Jenkinsfile
- fix: rename variable after typo (#331)
=> fix: rename variable after typo (#331) backport for 7.9.x

.ci/scripts/clean-docker.sh, Makefile, e2e/_suites/ingest-manager/README.md, e2e/_suites/metricbeat/README.md
It adds three Make goals to clean up the local state:
- make clean-workspace, which removes the HOME directory for the compose files
- make clean-docker, which refreshes certain docker images that are usually consumed in a SNAPSHOT manner (kibana, elasticsearch, elastic-agent)
- make clean, which invokes the two above goals
Sometimes it's possible to get undesired results when working with the test framework, changing from a maintenance branch to another.
From project's root dir:
```shell
$ make clean
$ make clean-workspace
$ make clean-docker
```
It will remove $HOME/.op/compose directory and will refresh the docker images.
Developers executing the tests between different maintenance branch will use these new goals to clean up the local state
We wil backport this to 7.9.x, updating the …
=> chore: add make goals to clean up local workspace and docker

.ci/scripts/clean-docker.sh, Makefile, e2e/_suites/ingest-manager/README.md, e2e/_suites/metricbeat/README.md
- chore: add make goals to clean up local workspace and docker (#354)
=> chore: add make goals to clean up local workspace and docker (#354) backport for 7.9.x

cli/config/compose/profiles/metricbeat/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, e2e/Makefile
- fix: preset default values for stack and metricbeat (#360)
=> fix: preset default values for stack and metricbeat (#360) backport for 7.9.x

.ci/Jenkinsfile
- Use credentials with user and pass rather than the ssh ones.
- Use `setEnvVar` to get rid of the `script` closure
To send GH check notifications
=> [CI] Use user-pass credentials

e2e/_suites/metricbeat/metricbeat_test.go
- fix: do not pass TRACE log level to metricbeat (#366)
=> fix: do not pass TRACE log level to metricbeat (#366) backport for 7.9.x

e2e/_suites/ingest-manager/fleet.go
It uses the word `policy` instead of `config` when matching the security events for an agent
Even thought we are in 7.9, the rename of the configs to policies does not affect to this log entry
```shell
$ SUITE=ingest-manager DEVELOPER_MODE=true TAGS="agent_endpoint_integration && set-policy-and-check-changes" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
- Closes #371
The evvent is now obtained, but in the DEGRADED state:
>"Application: endpoint-security--7.9.2[ab9e7d89-a285-4cf2-be3b-65d9d87ee096]: State changed to DEGRADED: Protecting with policy {b89ee120-1045-11eb-a219-ff34b6e24c16}"
=> fix: use policy instead of config

cli/services/manager.go
It adds the `--remove-orphans` flag to the `docker-compose down` command.
When adding services oon the fly to a running compose, using `AddServicesToCompose` method, those services/containers are not attached to the destroyed unless it's passed the compose file for each of them. With this flag we won't let containers to be kept running, destroying them alongside its parent compose (the one they are attached to)
We should see:
>Stopping fleet_kibana_1           ... done
Stopping fleet_package-registry_1 ... done
Stopping fleet_elasticsearch_1    ... done
Removing orphan container "fleet_centos-systemd_elastic-agent_1"
Removing orphan container "fleet_debian-systemd_elastic-agent_1"
Removing fleet_kibana_1           ... done
Removing fleet_package-registry_1 ... done
Removing …
=> chore: remove orphan containers when shutting down the compose

cli/services/manager.go
- chore: remove orphan containers when shutting down the compose (#381)
=> chore: remove orphan containers when shutting down the compose (#381) backport for 7.9.x

.ci/Jenkinsfile
- fix: wrong variable name (#390)
=> fix: wrong variable name (#390) backport for 7.10.x

.ci/Jenkinsfile
- fix: wrong variable name (#390)
=> fix: wrong variable name (#390) backport for 7.9.x

e2e/_suites/fleet/fleet.go
It doubles the time used to wait for security events. We are currently checking these conditions:
```go
applicationName := "endpoint-security"
agentID := ""                           // calculated
packagePolicyID := ""                   // calculated
//...
matches := (strings.Contains(message, applicationName) &&
strings.Contains(message, "["+agentID+"]: State changed to") &&
strings.Contains(message, "Protecting with policy {"+packagePolicyID+"}"))
```
This should fix the CI, as we have seen 3-4 mins delay to get those events.
```shell
$ SUITE="fleet" TAGS="set-policy-and-check-changes" DEVELOPER_MODE=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
- Fixes #388
We are noticing that the events are always in the `DEGRADED` state (verified in 7.9.x and master), when …
=> fix: double the timeout to check security events

e2e/_suites/fleet/fleet.go
- fix: double down the timeout to check security events (#389)
=> fix: double down the timeout to check security events (#389) backport for 7.10.x

e2e/_suites/ingest-manager/fleet.go
- fix: double down the timeout to check security events (#389)
=> fix: double down the timeout to check security events (#389) backport for 7.9.x

e2e/utils.go
- chore: use URL parameter to avoid adding test stats (#398)
=> chore: use URL parameter to avoid adding test stats (#398) backport for 7.9.x

e2e/utils.go
- chore: use URL parameter to avoid adding test stats (#398)
=> chore: use URL parameter to avoid adding test stats (#398) backport for 7.10.x

e2e/_suites/metricbeat/features/apache.feature, e2e/_suites/metricbeat/features/metricbeat.feature, e2e/_suites/metricbeat/features/mysql.feature, e2e/_suites/metricbeat/features/redis.feature, e2e/_suites/metricbeat/features/vsphere.feature, e2e/_suites/metricbeat/metricbeat_test.go
It removes the steps that hardcoded the amount of seconds for waits, delegating it to the existing steps that already waited using backoff strategy.
>In fact we are moving the active wait from the specs to the code, as it's an implementation detail. We are waiting 30 secs right before starting metricbeat, so that the target integration service is able to start-up, and metricbeat does not discover errors that are previous to the service gets to the healthy status.
With these changes the wait timeout is configurable with the TIMEOUT_FACTOR variable (default is 3), being the real value 10 times that variable.
It simplifies the feature files, and the code, removing hardcoded values. Besides that, it reduces execution time for the metricbeat test suite.
```shell
$ SUITE="metricbeat" …
```
=> chore: simplify metricbeat waits

.ci/e2eTestingIntegrationsDaily.groovy, e2e/_suites/metricbeat/features/apache.feature, e2e/_suites/metricbeat/features/metricbeat.feature, e2e/_suites/metricbeat/features/mysql.feature, e2e/_suites/metricbeat/features/redis.feature, e2e/_suites/metricbeat/features/vsphere.feature, e2e/_suites/metricbeat/metricbeat_test.go
- chore: use the proper beats slack channel (#405)
- chore: simplify metricbeat waits (#406)
=> chore: use the proper beats slack channel (#405) | chore: simplify metricbeat waits (#406) backport for 7.10.x

.ci/e2eTestingIntegrationsDaily.groovy, e2e/_suites/metricbeat/features/apache.feature, e2e/_suites/metricbeat/features/metricbeat.feature, e2e/_suites/metricbeat/features/mysql.feature, e2e/_suites/metricbeat/features/redis.feature, e2e/_suites/metricbeat/features/vsphere.feature, e2e/_suites/metricbeat/metricbeat_test.go
- chore: use the proper beats slack channel (#405)
- chore: simplify metricbeat waits (#406)
=> chore: use the proper beats slack channel (#405) | chore: simplify metricbeat waits (#406) backport for 7.9.x

.ci/Jenkinsfile
- fix: send slack notifications to the proper channel (#421)
=> fix: send slack notifications to the proper channel (#421) backport for 7.10.x

.ci/Jenkinsfile
- fix: send slack notifications to the proper channel (#421)
=> fix: send slack notifications to the proper channel (#421) backport for 7.9.x

e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go, e2e/utils.go
- feat: calculate latest version for Beats (#426)
=> feat: calculate latest version for Beats (#426) backport for 7.10.x

e2e/_suites/ingest-manager/ingest-manager_test.go, e2e/_suites/ingest-manager/services.go, e2e/_suites/ingest-manager/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go, e2e/utils.go
- feat: calculate latest version for Beats (#426)
=> feat: calculate latest version for Beats (#426) backport for 7.9.x

.ci/Jenkinsfile
It sets `failfast true` for all subsequent parallel stages in the pipeline, in this case the e2e tests.
It will fail the build, releasing CI resources, as soon an error occurs.
- Relates https://github.com/elastic/beats-tester/pull/186 
Backport to 7.9.x and 7.0.x
=> chore(ci): fail fast the  parallel execution for the e2e tests

.ci/Jenkinsfile
- chore(ci): fail fast the  parallel execution for the e2e tests (#429)
=> chore(ci): fail fast the  parallel execution for the e2e tests (#429) backport for 7.9.x

.ci/Jenkinsfile
- chore(ci): fail fast the  parallel execution for the e2e tests (#429)
=> chore(ci): fail fast the  parallel execution for the e2e tests (#429) backport for 7.10.x

.ci/Jenkinsfile
- chore(ci): fail fast the  parallel execution for the e2e tests (#429)
=> chore(ci): fail fast the  parallel execution for the e2e tests (#429) backport for 7.x

.ci/Jenkinsfile
- chore: calculate reporter name from isPR or isBranch (#457)
=> chore: calculate reporter name from isPR or isBranch (#457) backport for 7.9.x

.ci/Jenkinsfile
- chore: calculate reporter name from isPR or isBranch (#457)
=> chore: calculate reporter name from isPR or isBranch (#457) backport for 7.10.x

.ci/Jenkinsfile
- chore: calculate reporter name from isPR or isBranch (#457)
=> chore: calculate reporter name from isPR or isBranch (#457) backport for 7.x

e2e/_suites/helm/helm_charts_test.go
It adds a global variable setting the max timeout factor to 2. This variable could be modified by an environment variable, set on CI to 3.
It will make the backoff strategies configurable on test time, because it's now fixed to 1 minute.
After a few builds with the new Helm 3 code, it seems to randomly fail for metricbeat, that's why we are allowing this configuration.
Besides that, we noticed that installing the Elasticsearch helm chart took a lot. We found that there was a hardcoded value for the timeout, so we are reusing the new variable here to build the max timeout, also reducing the value from 900s to 200s by default (300 on CI).
```shell
SUITE="helm" TAGS="metricbeat" DEVELOPER_MODE=true TIMEOUT_FACTOR=1 LOG_LEVEL=TRACE make -C e2e functional-test
```
If using TIMEOUT_FACTOR=1, …
=> chore: double Helm max timeout

.ci/Jenkinsfile
- fix: move evaluation out of post section (#465)
=> fix: move evaluation out of post section (#465) backport for 7.x

.ci/Jenkinsfile
- fix: move evaluation out of post section (#465)
=> fix: move evaluation out of post section (#465) backport for 7.10.x

.ci/Jenkinsfile
- fix: move evaluation out of post section (#465)
=> fix: move evaluation out of post section (#465) backport for 7.9.x

e2e/utils.go
- fix: use full process name to match in pgrep (#475)
=> fix: use full process name to match in pgrep (#475) backport for 7.9.x

e2e/utils.go
- fix: use full process name to match in pgrep (#475)
=> fix: use full process name to match in pgrep (#475) backport for 7.x

e2e/utils.go
- fix: use full process name to match in pgrep (#475)
=> fix: use full process name to match in pgrep (#475) backport for 7.10.x

e2e/_suites/fleet/stand-alone.go
It doubles the maxtimeout when waiting for agent documents in stand-alone mode
We are observing that the CI jobs started to fail with the error:
>Step there is new data in the index from agent: Not enough hits in the logs-elastic_agent-default index yet. Current: 45, Desired: 50
So:
a. we double down the maxtimeout, giving more time to the test to find 50 docs, or
b. we reduce the expected docs count from 50 to a lower number.
With b) the initial number was set after experimenting with data, so I'd prefer having this number defined by product team, choosing a) because of that.
- Closes #482
With the following logs we observe the following:
- it takes 6 seconds in reaching 29 docs in the index -> 6s diff +29 docs
- it takes 23 seconds (total) in reaching 30 docs in the index -> 17s diff +1 …
=> fix: double max timeout when waiting for docs in stand-alone mode

e2e/_suites/ingest-manager/stand-alone.go
- fix: double max timeout when waitin for docs in standalone mode (#483)
=> fix: double max timeout when waitin for docs in standalone mode (#483) backport for 7.9.x

e2e/_suites/fleet/stand-alone.go
- fix: double max timeout when waitin for docs in standalone mode (#483)
=> fix: double max timeout when waitin for docs in standalone mode (#483) backport for 7.x

e2e/_suites/fleet/stand-alone.go
- fix: double max timeout when waitin for docs in standalone mode (#483)
=> fix: double max timeout when waitin for docs in standalone mode (#483) backport for 7.10.x

e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/fleet/services.go
It checks if the environment variable used to override Agent's version is set. If it's not set, then it will use the base version, which is obtained from:
a. the Elastic Artifacts URL for aliases (7.x, 7.10.x),
b. fixed to the maintenance branch
c. 8.0.0-SNAPSHOT in the master branch
I found that running:
```shell
SUITE="fleet" \
TAGS="fleet_mode && enroll" DEVELOPER_MODE=true \
ELASTIC_AGENT_VERSION="7.10.1" \
make -C e2e functional-test
```
was always downloading the version set to the maintenance branch, not honoring the version set in the environment variable.
Because we evaluated the version just once (init method for the test suite), then further calculations were tied to thee base version.
Download a different agent version (7.10.1)
```shell
git …
```
=> fix: honor ELASTIC_AGENT_VERSION when downloading the agent

e2e/_suites/fleet/services.go
- fix: update log path for TAR installer (#481)
=> fix: update log path for TAR installer (#481) backport for 7.x

e2e/_suites/fleet/services.go
- fix: update log path for TAR installer (#481)
=> fix: update log path for TAR installer (#481) backport for 7.10.x

.pre-commit-config.yaml
- fix: exclude images from non-breaking-spaces lint (#497)
=> fix: exclude images from non-breaking-spaces lint (#497) backport for 7.x

.pre-commit-config.yaml
- fix: exclude images from non-breaking-spaces lint (#497)
=> fix: exclude images from non-breaking-spaces lint (#497) backport for 7.10.x

.pre-commit-config.yaml
- fix: exclude images from non-breaking-spaces lint (#497)
=> fix: exclude images from non-breaking-spaces lint (#497) backport for 7.9.x

e2e/_suites/fleet/services.go, e2e/utils.go
It enriches the logs when querying the GCP storage bucket, also reducing the amount of entries to look up adding a filter in the form of a `prefix=PREFIX` query string parameter to limit results to objects that have the specific prefix (See https://cloud.google.com/storage/docs/listing-objects#rest-list-objects).
As a consequence, we noticed that the filename used for the TAR.GZ files for snapshots was incorrect, as it needs the OS after version and before architecture.
Beats packaging jobs were using wrong artifacts, because of several reasons:
1. Beats packaging job was setting the wrong parameter when triggering this job. It caused that the snapshot in the GCP bucket was never used, using the released artifacts from artifactory.
1. Once fixed, the file name for TAR.GZ artifacts was not …
=> fix: enhance GCP queries for PRs

e2e/_suites/fleet/features/fleet_mode_agent.feature
It uses proper Gherkin syntax for comments
The feature file cannot be parsed, failing the build
- Caused by #439
=> fix: use proper gherkin comments

.ci/scripts/functional-test.sh
- chore: simplify junit report name (#518)
=> chore: simplify junit report name (#518) backport for 7.9.x

.ci/scripts/functional-test.sh
- chore: simplify junit report name (#518)
=> chore: simplify junit report name (#518) backport for 7.x

.ci/scripts/functional-test.sh
- chore: simplify junit report name (#518)
=> chore: simplify junit report name (#518) backport for 7.10.x

e2e/_suites/fleet/ingest-manager_test.go
This PR adds a check for agent versions, determining if they are an alias, obtaining the proper artifact name from Elastic's artifactory.
We noticed that if setting the ELASTIC_AGENT_VERSION to an alias (i.e. 7.10-SNAPSHOT) and running the tests, they panic because it uses the alias to query the versions endpoint. With this change we will be normalising the version, which we already did it for the base version (we use base version for PRs targeting a version, i.e. to download binaries in the version: a PR to master will produce binaries with 8.0.0-SNAPSHOT on its name)
```shell
git checkout master
SUITE="fleet" ELASTIC_AGENT_VERSION="7.10-SNAPSHOT" \
TAGS="fleet_mode_agent && install" DEVELOPER_MODE=true \
make -C e2e functional-test
```
- Relates #480, …
=> fix: check if agent versions are aliases

e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/fleet/services.go
- fix: honor ELASTIC_AGENT_VERSION when downloading the agent (#480)
- fix: return base version for PRs (#502)
- fix: check if agent versions are aliases (#529)
Supersedes #489
=> fix: honor ELASTIC_AGENT_VERSION when downloading the agent (#480) | fix: return base version for PRs (#502) backport for 7.10.x

e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/fleet/services.go
- fix: honor ELASTIC_AGENT_VERSION when downloading the agent (#480)
- fix: return base version for PRs (#502)
- fix: check if agent versions are aliases (#529)
Supersedes #488
=> fix: honor ELASTIC_AGENT_VERSION when downloading the agent (#480) | fix: return base version for PRs (#502) backport for 7.x

e2e/Makefile
It double-quotes the tags in Makefile only when they are set
There was a corner case when using Make to run all scenarios (not filtering by tag)
Before this change, this command failed because godog was trying to evaluate "" as a feature path. Now it runs all scenarios (no TAGS set) but those skipped.
```shell
SUITE="fleet" DEVELOPER_MODE=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
This command runs all scenarios (no TAGS set), including skipped.
```shell
SUITE="fleet" SKIP_SCENARIOS=false DEVELOPER_MODE=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
This command runs some scenarios (TAGS is set), excluding skipped.
```shell
SUITE="fleet" TAGS="fleet_mode_agent" DEVELOPER_MODE=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e …
```
=> fix: double quote tags if they are set

e2e/_suites/fleet/features/fleet_mode_agent.feature
Disables upgrade tests 
Upgrade test fails on PR on 
```
[2020-12-10T17:53:01.565Z] time="2020-12-10T17:53:00Z" level=error msg="Could not download the binary for the agent" arch=x86_64 artifact=elastic-agent error="Reached the end of the pages and the snapshots/elastic-agent-7.10.0-x86_64.tar.gz object was not found for the beats-ci-artifacts bucket" extension=tar.gz os=linux version=7.10.0
[2020-12-10T17:53:01.565Z] time="2020-12-10T17:53:00Z" level=fatal msg="Sorry, we could not download the installer" error="Reached the end of the pages and the snapshots/elastic-agent-7.10.0-x86_64.tar.gz object was not found for the beats-ci-artifacts bucket" image=debian installer=tar
```
=> disable upgrade tests

e2e/utils.go
- fix: do not check artifacts API for PRs (#536)
=> fix: do not check artifacts API for PRs (#536) backport for 7.x

e2e/utils.go
- fix: do not check artifacts API for PRs (#536)
=> fix: do not check artifacts API for PRs (#536) backport for 7.10.x

e2e/_suites/fleet/features/fleet_mode_agent.feature
When this was fixed, we should have unskipped the relating tests that were recently re-added to test this.
issue here: https://github.com/elastic/beats/issues/22744
I plan to use the CI to test it.  Will report back after test run (hopefully) passes.
=> unskip deb and rpm test

e2e/_suites/fleet/features/fleet_mode_agent.feature
- unskip deb and rpm test (#542)
=> unskip deb and rpm test (#542) backport for 7.10.x

e2e/_suites/fleet/features/fleet_mode_agent.feature
- unskip deb and rpm test (#542)
=> unskip deb and rpm test (#542) backport for 7.x

e2e/_suites/fleet/configurations/kibana.config.yml
It renames IngestManager properties to Fleet.
They will be deprecated soon.
- Relates https://github.com/elastic/kibana/pull/79406
After removing deprecation messages for Fleet, we still see these messages:
>{"type":"log","@timestamp":"2021-01-04T16:45:00+00:00","tags":["info","plugins-service"],"pid":8,"message":"Plugin \"telemetryManagementSection\" has been disabled since the following direct or transitive dependencies are missing or disabled: [telemetry]"}
{"type":"log","@timestamp":"2021-01-04T16:45:00+00:00","tags":["info","plugins-service"],"pid":8,"message":"Plugin \"telemetry\" is disabled."}
{"type":"log","@timestamp":"2021-01-04T16:45:00+00:00","tags":["warning","config","deprecation"],"pid":8,"message":"Setting [elasticsearch.username] to \"elastic\" is deprecated. You should …
=> chore: update Fleet properties in Kibana

e2e/_suites/fleet/configurations/kibana.config.yml
- chore: update Fleet properties in Kibana (#555)
=> chore: update Fleet properties in Kibana (#555) backport for 7.x

cli/config/compose/services/elastic-agent/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
If the developer targets a CI snapshot, then it will use observavbility-ci,
otherwise beats will be the default
It makes the namespace of the docker image for the elastic-agent configurable, being it possible to set `beats` and `observability-ci`. The second one will be used for CI snapshots, setting the `ELASTIC_AGENT_USE_CI_SNAPSHOTS` env var.
For Beats PRs targetting a maintenance branch (7.x, 7.10.x) the namespace in the E2E is `beats`, always, which is wrong, as the snapshots are published under the `observvability-ci` namespace. With this changes, the image will be located properly. 
```shell
git checkout 7.x
SUITE="fleet" ELASTIC_AGENT_VERSION="pr-23142" \
ELASTIC_AGENT_USE_CI_SNAPSHOTS=true TAGS="stand_alone_agent" DEVELOPER_MODE=true \ 
make -C …
```
=> fix: make docker namespace configurable

cli/config/compose/services/elastic-agent/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- fix: make docker namespace configurable (#560)
=> fix: make docker namespace configurable (#560) backport for 7.10.x

cli/config/compose/services/elastic-agent/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- fix: make docker namespace configurable (#560)
=> fix: make docker namespace configurable (#560) backport for 7.x

.ci/Jenkinsfile, e2e/_suites/fleet/README.md, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/README.md, e2e/_suites/metricbeat/metricbeat_test.go, e2e/utils.go
It renames the ELASTIC_AGENT_USE_CI_SNAPSHOTS to USE_CI_SNAPSHOTS, which makes its scope wider, and easier to reuse across different test suites.
It also includes a small refactor in the logic to get the Docker namespace: if we use CI snapshots, let's use `observability-ci`, otherwise use `beats`.
We consume that variable in both metricbeat and elastic-agent test suites, so we prefer clarity when using it.
```shell
SUITE="metricbeat" METRICBEAT_VERSION="pr-23142" \
USE_CI_SNAPSHOTS=true TAGS="metricbeat" DEVELOPER_MODE=true \
make -C e2e functional-test
```
- Blocks elastic/beats#23382
We must merge a PR in Beats with the update, as I could not find a simple way of not breaking the downstream project (Beats) after this change
Needs backport to 7.x and …
=> chore: rename ELASTIC_AGENT_USE_CI_SNAPSHOTS

e2e/_suites/metricbeat/metricbeat_test.go
It switches the order of two operations: 1) setting the version for Metricbeat's docker image, and 2) defining which branch/tag will be used to download the configuration file.
It causes a bug in the tests for metricbeat configuration in the case it's triggered by a PR from Beats: it will use the CI snapshots but the version, as it starts with `pr-`, was replaced with the base version for the maintenance branch, when we still want to use the version of the PR (in the form of its Docker image, downloaded from `observability-ci` registry)
```shell
SUITE="metricbeat" METRICBEAT_VERSION="pr-23142" \
ELASTIC_AGENT_USE_CI_SNAPSHOTS=true TAGS="metricbeat" DEVELOPER_MODE=true \
make -C e2e functional-test
```
- Fixes #564
- Discovered while testing #560
We still …
=> fix: set image version before switching to the configuration file

.ci/Jenkinsfile, e2e/_suites/fleet/README.md, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/README.md, e2e/_suites/metricbeat/metricbeat_test.go, e2e/utils.go
- chore: rename ELASTIC_AGENT_USE_CI_SNAPSHOTS (#566)
- fix: set image version before switching to the configuration file (#565)
=> chore: rename ELASTIC_AGENT_USE_CI_SNAPSHOTS (#566) | fix: set image version before switching to the configuration file (#565) backport for 7.x

.ci/Jenkinsfile, e2e/_suites/fleet/README.md, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/README.md, e2e/_suites/metricbeat/metricbeat_test.go, e2e/utils.go
- chore: rename ELASTIC_AGENT_USE_CI_SNAPSHOTS (#566)
- fix: set image version before switching to the configuration file (#565)
=> chore: rename ELASTIC_AGENT_USE_CI_SNAPSHOTS (#566) | fix: set image version before switching to the configuration file (#565) backport for 7.10.x

.ci/jobs/e2e-testing-mbp.yml, e2e/_suites/metricbeat/metricbeat_test.go
- fix: monitor PRs and tags too (#571)
- fix: restore initial state (#570)
=> fix: monitor PRs and tags too (#571) | fix: restore initial state (#570) backport for 7.x

.ci/jobs/e2e-testing-mbp.yml, e2e/_suites/metricbeat/metricbeat_test.go
- fix: monitor PRs and tags too (#571)
- fix: restore initial state (#570)
=> fix: monitor PRs and tags too (#571) | fix: restore initial state (#570) backport for 7.10.x

cli/config/compose/profiles/fleet/docker-compose.yml, e2e/_suites/fleet/configurations/kibana.config.yml
See https://github.com/elastic/kibana/pull/87114
It updates the e2e tests after elastic/kibana#87114
Kibana fails to start and the container dies because of a wrong value of the `server.host` property.
```shell
SUITE="fleet" TAGS="fleet_mode_agent && unenroll" DEVELOPER_MODE=true TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
- Fixes #575
- Caused by elastic/kibana#87114
- Relates elastic/elastic-package#211
=> fix: use proper server.host in Kibana

e2e/_suites/fleet/services.go
It adds a subdirectory inside the `snapshots` bucket for beats-ci-artifacts.
After 7.9, around 5 months ago 🤦‍♀️ there was [a change in the bucket path](https://github.com/elastic/beats/pull/20903) to normalise the folder structure, using the artifact name (metricbeat, elastic-agent, filebeat, etc) as a parent directory under the snapshots main bucket dir. With this change, the artifacts will be located in the proper bucket folder.
> An example of a failed build not finding the artifact: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.x/90/pipeline
- Relates elastic/beats#20903
=> fix: add artifact name to the bucket URI

e2e/_suites/fleet/services.go
- fix: add artifact name to the bucket URI (#598)
=> fix: add artifact name to the bucket URI (#598) backport for 7.x

e2e/_suites/fleet/services.go
- fix: add artifact name to the bucket URI (#598)
=> fix: add artifact name to the bucket URI (#598) backport for 7.11.x

e2e/_suites/fleet/services.go
- fix: add artifact name to the bucket URI (#598)
=> fix: add artifact name to the bucket URI (#598) backport for 7.10.x

e2e/README.md
It provides a list of steps to trigger the tests for a Beats PR, including default values.
When the test fail on a Beats PR, we'd like the developer to manually retrigger the E2E using Jenkins UI.
- Closes #582
```gherkin
Given a Beats PR
When the E2E needs to be retriggered
Then the PR author knows how to trigger it manually 
``` 
We could add a `/run-e2e` command in Beats pipeline to retrigger them only if the package job was already in triggered.
=> docs: document how to trigger the tests for Beats PR

e2e/README.md
- docs: document how to trigger the tests for Beats PR (#608)
=> docs: document how to trigger the tests for Beats PR (#608) backport for 7.x

e2e/README.md
- docs: document how to trigger the tests for Beats PR (#608)
=> docs: document how to trigger the tests for Beats PR (#608) backport for 7.11.x

e2e/README.md
- docs: document how to trigger the tests for Beats PR (#608)
=> docs: document how to trigger the tests for Beats PR (#608) backport for 7.10.x

e2e/README.md
- docs: document how to trigger the tests for Beats PR (#608)
=> docs: document how to trigger the tests for Beats PR (#608) backport for 6.8.x

e2e/_suites/metricbeat/metricbeat_test.go, e2e/elasticsearch.go, e2e/utils.go
We are increasing the timeout when waiting for the Ceph integration to be up-and-running, as the Beats team already do in https://github.com/elastic/beats/blob/ef6274d0d1e36308a333cbed69846a1bd63528ae/metricbeat/module/ceph/mgr_osd_tree/mgr_osd_tree_integration_test.go#L35. Because testcontainers is not supporting (yet) a `waitFor` strategy (it's about to be merged), we have to sleep the thread. And we are increasing the timeout to 2 minutes only for Ceph, the rest of the services stay at 30 seconds.
In between, we refactored the Sleep method to simplify its usage, using time.Duration instead of string as input parameter.
As a result of this PR, we expect to **reduce the flakiness** detected by the E2E for Cep, causing noise in Beats PRs, which needed to be re-triggered.
```shell …
```
=> chore: increase timeout for Ceph

.ci/Jenkinsfile, README.md, e2e/README.md
- fix: typo in precommit docs (#623)
- chore: increase timeout in CI (#624)
=> fix: typo in precommit docs (#623) | chore: increase timeout in CI (#624) backport for 6.8.x

.ci/Jenkinsfile, README.md, e2e/README.md
- fix: typo in precommit docs (#623)
- chore: increase timeout in CI (#624)
=> fix: typo in precommit docs (#623) | chore: increase timeout in CI (#624) backport for 7.10.x

.ci/Jenkinsfile, README.md, e2e/README.md
- fix: typo in precommit docs (#623)
- chore: increase timeout in CI (#624)
=> fix: typo in precommit docs (#623) | chore: increase timeout in CI (#624) backport for 7.11.x

.ci/scripts/functional-test.sh
- fix: let godog handle the creation of the junit test file (#629)
=> fix: let godog handle the creation of the junit test file (#629) backport for 7.11.x

.ci/scripts/functional-test.sh
- fix: let godog handle the creation of the junit test file (#629)
=> fix: let godog handle the creation of the junit test file (#629) backport for 7.10.x

.ci/scripts/functional-test.sh
- fix: let godog handle the creation of the junit test file (#629)
=> fix: let godog handle the creation of the junit test file (#629) backport for 6.8.x

e2e/_suites/metricbeat/features/integrations.feature
It skip ceph tests to avoid confusion while we find the root cause of the flakiness.
It's causing noise in both merges and PRs, specially from Beats.
- Relates #607, #622, #630
- Relates elastic/beats#23602
=> chore: skip ceph tests

cli/cmd/_testresources/docker-compose-multiple.yml, cli/cmd/_testresources/docker-compose-single.yml, cli/cmd/sync.go, cli/cmd/sync_test.go
It moves the variable holding the references to a single service into the loop-for that is responsible of creating the service.
In the process, we added unit tests to the sanitize compose file feature, and for that we had to change method signature to support writing to a different file in the test side (adding testability).
We noticed that ceph was not receiving all the ports declared in its docker-compose file:
```yaml
version: '2.3'
services:
ceph:
image: docker.elastic.co/integrations-ci/beats-ceph:${CEPH_VERSION:-master-97985eb-nautilus-centos-7-x86_64}-2
build:
context: ./_meta
dockerfile: Dockerfile.${CEPH_CODENAME:-nautilus}
args:
CEPH_VERSION: ${CEPH_VERSION:-master-97985eb-nautilus-centos-7-x86_64}
ports:
- 5000
- 8003
- 8080
ceph-api:
image: …
```
=> fix: do not override compose configurations when syncing from beats

.ci/Jenkinsfile, README.md, e2e/README.md
- fix: typo in precommit docs (#623)
- chore: increase timeout in CI (#624)
=> fix: typo in precommit docs (#623) | chore: increase timeout in CI (#624) backport for 7.x

.ci/scripts/functional-test.sh
- fix: let godog handle the creation of the junit test file (#629)
=> fix: let godog handle the creation of the junit test file (#629) backport for 7.x

e2e/_suites/metricbeat/features/integrations.feature
- chore: skip ceph tests (#635)
=> chore: skip ceph tests (#635) backport for 6.8.x

e2e/_suites/metricbeat/features/integrations.feature
- chore: skip ceph tests (#635)
=> chore: skip ceph tests (#635) backport for 7.10.x

e2e/_suites/metricbeat/features/integrations.feature
- chore: skip ceph tests (#635)
=> chore: skip ceph tests (#635) backport for 7.11.x

e2e/_suites/metricbeat/features/integrations.feature
- chore: skip ceph tests (#635)
=> chore: skip ceph tests (#635) backport for 7.x

cli/cmd/_testresources/docker-compose-multiple.yml, cli/cmd/_testresources/docker-compose-single.yml, cli/cmd/sync.go, cli/cmd/sync_test.go
- fix: do not override compose configurations when syncing from beats (#630)
=> fix: do not override compose configurations when syncing from beats (#630) backport for 7.11.x

cli/cmd/_testresources/docker-compose-multiple.yml, cli/cmd/_testresources/docker-compose-single.yml, cli/cmd/sync.go, cli/cmd/sync_test.go
- fix: do not override compose configurations when syncing from beats (#630)
=> fix: do not override compose configurations when syncing from beats (#630) backport for 7.10.x

cli/cmd/_testresources/docker-compose-multiple.yml, cli/cmd/_testresources/docker-compose-single.yml, cli/cmd/sync.go, cli/cmd/sync_test.go
- fix: do not override compose configurations when syncing from beats (#630)
=> fix: do not override compose configurations when syncing from beats (#630) backport for 6.8.x

cli/cmd/_testresources/docker-compose-multiple.yml, cli/cmd/_testresources/docker-compose-single.yml, cli/cmd/sync.go, cli/cmd/sync_test.go
- fix: do not override compose configurations when syncing from beats (#630)
=> fix: do not override compose configurations when syncing from beats (#630) backport for 7.x

.ci/Jenkinsfile
It removes the call to `notifyBuildResult` from the cleanUp hook, merging its parameters into the final invocation.
We are also fixing the flaky analyser name, using base branch instead of always using master.
After review, we detected the post success/failure blocks were confusing: we decided to simplify them so that there is only one entrypoint for creating the GH comment, although the slack notification is controlled exclusively by the input parameter (false by default).
We detected two documents on Jenkins-Stats, only differentiating in the artifacts field.
=> fix: notify build result only once

.ci/Jenkinsfile
- fix: notify build result only once (#673)
=> fix: notify build result only once (#673) backport for 7.11.x

.ci/Jenkinsfile
- fix: notify build result only once (#673)
=> fix: notify build result only once (#673) backport for 7.10.x

.ci/Jenkinsfile
- fix: notify build result only once (#673)
=> fix: notify build result only once (#673) backport for 6.8.x

.ci/Jenkinsfile
- fix: notify build result only once (#673)
=> fix: notify build result only once (#673) backport for 7.x

e2e/Makefile, e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/services_test.go
- chore: refactor Fleet upgrade tests (#671)
=> chore: refactor Fleet upgrade tests (#671) backport for 7.x

.ci/Jenkinsfile, e2e/Makefile, e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/services_test.go
- chore: refactor Fleet upgrade tests (#671)
=> chore: refactor Fleet upgrade tests (#671) backport for 7.11.x

.ci/Jenkinsfile, e2e/Makefile, e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/services_test.go
- chore: refactor Fleet upgrade tests (#671)
=> chore: refactor Fleet upgrade tests (#671) backport for 7.10.x

.ci/Jenkinsfile, cli/docker/docker.go, e2e/Makefile, e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/services_test.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go, e2e/utils.go, e2e/utils_test.go
- chore: refactor Fleet upgrade tests (#671)
- chore: refactor build artifacts methods (#689)
=> chore: refactor Fleet upgrade tests (#671) | chore: refactor build artifacts methods (#689) backport for 6.8.x

.ci/Jenkinsfile, .ci/functionalTests.groovy, .ci/scripts/functional-test.sh, .ci/scripts/install-test-dependencies.sh, .ci/scripts/metricbeat-test.sh
Enable metricbeat script to delegate all the logic to this repo then the consumer only need to call the script
Simplify the consumer calls
- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have run the Unit tests for the CLI, and they are passing locally~~
Run the script `.ci/scripts/metricbeat-test.sh`
Relates https://github.com/elastic/beats/pull/23854/
=> Metricbeat goal

e2e/_suites/metricbeat/metricbeat_test.go
It forces metricbeat to look up the binaries from the x-pack directory.
@v1v detected a corner case, or a missing piece, where the OSS artifacts were not used in the tests, because we were not aware that metricbeat images that we use in the tests were x-pack.
```shell
cd /tmp/git
git clone https://github.com/elastic/beats.git
SUITE="metricbeat" TAGS="metricbeat" DEVELOPER_MODE="true" BEATS_LOCAL_PATH="/tmp/beats" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
=> fix: use x-pack dir for metricbeat binaries

e2e/_suites/metricbeat/metricbeat_test.go
- fix: use x-pack dir for metricbeat binaries (#718)
=> fix: use x-pack dir for metricbeat binaries (#718) backport for 7.x

e2e/_suites/metricbeat/metricbeat_test.go
- fix: use x-pack dir for metricbeat binaries (#718)
=> fix: use x-pack dir for metricbeat binaries (#718) backport for 7.10.x

e2e/_suites/metricbeat/metricbeat_test.go
- fix: use x-pack dir for metricbeat binaries (#718)
=> fix: use x-pack dir for metricbeat binaries (#718) backport for 6.8.x

e2e/_suites/metricbeat/metricbeat_test.go
- fix: use x-pack dir for metricbeat binaries (#718)
=> fix: use x-pack dir for metricbeat binaries (#718) backport for 7.11.x

.ci/Jenkinsfile, .ci/functionalTests.groovy, .ci/scripts/functional-test.sh, .ci/scripts/install-test-dependencies.sh, .ci/scripts/metricbeat-test.sh
=> Metricbeat goal (#705) backport for 6.8.x

cli/shell/shell.go, cli/shell/shell_test.go
- fix: cover fallback cases for shell.GetEnv (#723)
=> fix: cover fallback cases for shell.GetEnv (#723) backport for 7.10.x

cli/shell/shell.go, cli/shell/shell_test.go
- fix: cover fallback cases for shell.GetEnv (#723)
=> fix: cover fallback cases for shell.GetEnv (#723) backport for 7.11.x

cli/shell/shell.go, cli/shell/shell_test.go
- fix: cover fallback cases for shell.GetEnv (#723)
=> fix: cover fallback cases for shell.GetEnv (#723) backport for 7.x

cli/shell/shell.go, cli/shell/shell_test.go
- fix: cover fallback cases for shell.GetEnv (#723)
=> fix: cover fallback cases for shell.GetEnv (#723) backport for 6.8.x

.ci/Jenkinsfile, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: use alias for stale version (#731)
=> chore: use alias for stale version (#731) backport for 7.x

.ci/Jenkinsfile, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: use alias for stale version (#731)
=> chore: use alias for stale version (#731) backport for 7.11.x

.ci/Jenkinsfile, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: use alias for stale version (#731)
=> chore: use alias for stale version (#731) backport for 6.8.x

.ci/Jenkinsfile, .ci/e2eTestingFleetDaily.groovy, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: use alias for stale version (#731)
=> chore: use alias for stale version (#731) backport for 7.10.x

.ci/Jenkinsfile
- chore: add trace log level on CI (#741)
=> chore: add trace log level on CI (#741) backport for 7.x

.ci/Jenkinsfile
- chore: add trace log level on CI (#741)
=> chore: add trace log level on CI (#741) backport for 7.10.x

.ci/Jenkinsfile
- chore: add trace log level on CI (#741)
=> chore: add trace log level on CI (#741) backport for 7.11.x

.ci/Jenkinsfile
- chore: add trace log level on CI (#741)
=> chore: add trace log level on CI (#741) backport for 6.8.x

cli/config/compose/profiles/metricbeat/docker-compose.yml
- fix: use official repository for elasticsearch (#753)
=> fix: use official repository for elasticsearch (#753) backport for 7.11.x

cli/config/compose/profiles/metricbeat/docker-compose.yml
- fix: use official repository for elasticsearch (#753)
=> fix: use official repository for elasticsearch (#753) backport for 6.8.x

cli/cmd/sync.go, cli/cmd/sync_test.go, cli/config/compose/profiles/fleet/docker-compose.yml, cli/config/compose/profiles/metricbeat/docker-compose.yml, cli/config/compose/services/apm-server/docker-compose.yml, cli/config/compose/services/centos-systemd/docker-compose.yml, cli/config/compose/services/centos/docker-compose.yml, cli/config/compose/services/debian-systemd/docker-compose.yml, cli/config/compose/services/debian/docker-compose.yml, cli/config/compose/services/elastic-agent/docker-compose.yml, cli/config/compose/services/elasticsearch/docker-compose.yml, cli/config/compose/services/kibana/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, cli/config/compose/services/opbeans-go/docker-compose.yml, cli/config/compose/services/opbeans-java/docker-compose.yml, cli/config/compose/services/vsphere/docker-compose.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
It adds the `platform` element to the docker-compose files for metricbeat and the elastic-agent, so that we will be able to target AMD64 or ARM64 (last one in the near future). This change forced us to upgrade compose files versions from 2.3 to 2.4, which is the version where `platform` attribute appeared.
Because of that, all files in the execution must use the same version, so we are updating all compose files in consequence. And that means that when synchronising the Integrations from Beats, we must enforce the 2.4 version too.
We want to make sure we consume the proper platform. After Beats creating ARM images, we need to make sure we consume the proper platform.
- Relates #748
=> fix: support selecting the platform in docker-compose

cli/cmd/sync.go, cli/cmd/sync_test.go, cli/config/compose/profiles/fleet/docker-compose.yml, cli/config/compose/profiles/metricbeat/docker-compose.yml, cli/config/compose/services/apm-server/docker-compose.yml, cli/config/compose/services/centos-systemd/docker-compose.yml, cli/config/compose/services/centos/docker-compose.yml, cli/config/compose/services/debian-systemd/docker-compose.yml, cli/config/compose/services/debian/docker-compose.yml, cli/config/compose/services/elastic-agent/docker-compose.yml, cli/config/compose/services/elasticsearch/docker-compose.yml, cli/config/compose/services/kibana/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, cli/config/compose/services/opbeans-go/docker-compose.yml, cli/config/compose/services/opbeans-java/docker-compose.yml, cli/config/compose/services/vsphere/docker-compose.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- fix: support selecting the platform in docker-compose (#751)
=> fix: support selecting the platform in docker-compose (#751) backport for 7.x

cli/cmd/sync.go, cli/cmd/sync_test.go, cli/config/compose/profiles/fleet/docker-compose.yml, cli/config/compose/profiles/metricbeat/docker-compose.yml, cli/config/compose/services/apm-server/docker-compose.yml, cli/config/compose/services/centos-systemd/docker-compose.yml, cli/config/compose/services/centos/docker-compose.yml, cli/config/compose/services/debian-systemd/docker-compose.yml, cli/config/compose/services/debian/docker-compose.yml, cli/config/compose/services/elastic-agent/docker-compose.yml, cli/config/compose/services/elasticsearch/docker-compose.yml, cli/config/compose/services/kibana/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, cli/config/compose/services/opbeans-go/docker-compose.yml, cli/config/compose/services/opbeans-java/docker-compose.yml, cli/config/compose/services/vsphere/docker-compose.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- fix: support selecting the platform in docker-compose (#751)
=> fix: support selecting the platform in docker-compose (#751) backport for 7.10.x

cli/cmd/sync.go, cli/cmd/sync_test.go, cli/config/compose/profiles/fleet/docker-compose.yml, cli/config/compose/profiles/metricbeat/docker-compose.yml, cli/config/compose/services/apm-server/docker-compose.yml, cli/config/compose/services/centos-systemd/docker-compose.yml, cli/config/compose/services/centos/docker-compose.yml, cli/config/compose/services/debian-systemd/docker-compose.yml, cli/config/compose/services/debian/docker-compose.yml, cli/config/compose/services/elastic-agent/docker-compose.yml, cli/config/compose/services/elasticsearch/docker-compose.yml, cli/config/compose/services/kibana/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, cli/config/compose/services/opbeans-go/docker-compose.yml, cli/config/compose/services/opbeans-java/docker-compose.yml, cli/config/compose/services/vsphere/docker-compose.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- fix: support selecting the platform in docker-compose (#751)
=> fix: support selecting the platform in docker-compose (#751) backport for 6.8.x

cli/cmd/sync.go, cli/cmd/sync_test.go, cli/config/compose/profiles/fleet/docker-compose.yml, cli/config/compose/profiles/metricbeat/docker-compose.yml, cli/config/compose/services/apm-server/docker-compose.yml, cli/config/compose/services/centos-systemd/docker-compose.yml, cli/config/compose/services/centos/docker-compose.yml, cli/config/compose/services/debian-systemd/docker-compose.yml, cli/config/compose/services/debian/docker-compose.yml, cli/config/compose/services/elastic-agent/docker-compose.yml, cli/config/compose/services/elasticsearch/docker-compose.yml, cli/config/compose/services/kibana/docker-compose.yml, cli/config/compose/services/metricbeat/docker-compose.yml, cli/config/compose/services/opbeans-go/docker-compose.yml, cli/config/compose/services/opbeans-java/docker-compose.yml, cli/config/compose/services/vsphere/docker-compose.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- fix: support selecting the platform in docker-compose (#751)
=> fix: support selecting the platform in docker-compose (#751) backport for 7.11.x

.ci/scripts/functional-test.sh, .ci/scripts/install-metricbeat-test-dependencies.sh, cli/Makefile, e2e/Makefile
- chore: simplify synchronising the integrations (#761)
- chore: go version cannot be overriden (#762)
=> chore: simplify synchronising the integrations (#761) | chore: go version cannot be overriden (#762) backport for 6.8.x

.ci/scripts/functional-test.sh, .ci/scripts/install-metricbeat-test-dependencies.sh, cli/Makefile, e2e/Makefile
- chore: simplify synchronising the integrations (#761)
- chore: go version cannot be overriden (#762)
=> chore: simplify synchronising the integrations (#761) | chore: go version cannot be overriden (#762) backport for 7.x

.ci/scripts/functional-test.sh, .ci/scripts/install-metricbeat-test-dependencies.sh, cli/Makefile, e2e/Makefile
- chore: simplify synchronising the integrations (#761)
- chore: go version cannot be overriden (#762)
=> chore: simplify synchronising the integrations (#761) | chore: go version cannot be overriden (#762) backport for 7.11.x

.ci/scripts/functional-test.sh, .ci/scripts/install-metricbeat-test-dependencies.sh, cli/Makefile, e2e/Makefile
- chore: simplify synchronising the integrations (#761)
- chore: go version cannot be overriden (#762)
=> chore: simplify synchronising the integrations (#761) | chore: go version cannot be overriden (#762) backport for 7.10.x

cli/docker/docker.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/metricbeat/metricbeat_test.go
It uses the Go Docker client to tag the imported image with the original version as tag.
We noticed the e2e are downloading the right binary from GCP (always `AMD64`), BUT the docker load command creates the new image without the proper tag, using `agent:8.0.0-SNAPSHOT` instead of `agent:pr-12345`. Again but, the docker-compose file requires the second one, so it looks up the `observability-ci` namespace in the Docker registry, not honouring the physical file that was downloaded and imported, pulling `agent:pr-12345` instead.
- Relates #748
>DEBU[2021-02-17T18:10:21+01:00] Docker image tagged successfully              src="docker.elastic.co/beats/elastic-agent:8.0.0-SNAPSHOT" target="docker.elastic.co/observability-ci/elastic-agent:pr-24086"
=> chore: tag docker image after loading it from a file

cli/docker/docker.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: tag docker image after loading it from a file (#772)
=> chore: tag docker image after loading it from a file (#772) backport for 7.10.x

cli/docker/docker.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: tag docker image after loading it from a file (#772)
=> chore: tag docker image after loading it from a file (#772) backport for 6.8.x

cli/docker/docker.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: tag docker image after loading it from a file (#772)
=> chore: tag docker image after loading it from a file (#772) backport for 7.11.x

cli/docker/docker.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: tag docker image after loading it from a file (#772)
=> chore: tag docker image after loading it from a file (#772) backport for 7.x

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/installers.go
This PR forces symlink update for `update-ca-certificates` and reloads agent
Tests
=> e2e fleet: fixed upgrade scenario

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/installers.go
- e2e fleet: fixed upgrade scenario (#779)
=> e2e fleet: fixed upgrade scenario (#779) backport for 7.10.x

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/installers.go
- e2e fleet: fixed upgrade scenario (#779)
=> e2e fleet: fixed upgrade scenario (#779) backport for 7.11.x

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/installers.go
- e2e fleet: fixed upgrade scenario (#779)
=> e2e fleet: fixed upgrade scenario (#779) backport for 6.8.x

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/installers.go
- e2e fleet: fixed upgrade scenario (#779)
=> e2e fleet: fixed upgrade scenario (#779) backport for 7.x

.ci/scripts/fleet-test.sh
Enable metricbeat script to delegate all the logic to this repo then the consumer only need to call the script
Simplify the consumer calls
- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have run the Unit tests for the CLI, and they are passing locally~~
Run the script `.ci/scripts/fleet-test.sh`
Similar too https://github.com/elastic/e2e-testing/pull/705 and required by https://github.com/elastic/beats/pull/24112
=> Fleet goal

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
This PR appends the `-amd64` label when requesting Docker images to be pulled by Docker-Compose, but it only adds the suffix for GCP binaries (generated by the Beats CI ) and local images after a local build. At this moment we are hardcoding `-amd64`, as it's the only supported platform.
We discovered a bug in the DockerInstaller builder, as it was not setting the ubi8 image name properly.
We want to match the new naming schemma in Beats release process.
It should consume the stand-alone image, including the new tag.
**For a Beats PR**: fetching binaries from GCP.
```shell 
LOG_LEVEL=TRACE \
BEATS_USE_CI_SNAPSHOTS=true \
ELASTIC_AGENT_VERSION="pr-24019" \
.ci/scripts/functional-test.sh "fleet" "stand_alone_agent" "8.0.0-SNAPSHOT" "pr-24019"
```
**For a Beats Merge**: fetching binaries …
=> chore: append "-amd64" label for Docker images

.ci/scripts/fleet-test.sh
exclude the nightly tests
Nightly tests are running only on `nightly` basis, let's use the same logic in the script, similar to the one defined in the pipeline -> https://github.com/elastic/e2e-testing/blob/dcc950796120fabf0c85086823cef221cf3ecbcb/.ci/Jenkinsfile#L316-L323
Run the script itself
=> Fleet entrypoint to exclude the nightly tests

.ci/scripts/fleet-test.sh
=> Fleet goal (#784) backport for 6.8.x

e2e/_suites/fleet/installers.go
Fixing typo in update certs option
=> invalid option in update certificates cmd

.ci/scripts/fleet-test.sh
- Fleet entrypoint to exclude the nightly tests (#793)
=> Fleet entrypoint to exclude the nightly tests (#793) backport for 7.10.x

.ci/scripts/fleet-test.sh
- Fleet entrypoint to exclude the nightly tests (#793)
=> Fleet entrypoint to exclude the nightly tests (#793) backport for 7.11.x

.ci/scripts/fleet-test.sh
- Fleet entrypoint to exclude the nightly tests (#793)
=> Fleet entrypoint to exclude the nightly tests (#793) backport for 7.x

.ci/scripts/fleet-test.sh
- Fleet entrypoint to exclude the nightly tests (#793)
=> Fleet entrypoint to exclude the nightly tests (#793) backport for 6.8.x

e2e/_suites/fleet/installers.go
=> invalid option (#792) backport for 7.10.x

e2e/_suites/fleet/installers.go
=> invalid option (#792) backport for 7.11.x

e2e/_suites/fleet/services.go
This PR appends the `--url=` flag to the Kibana URL and the `--enrollment-token=` flag to the API token arguments when enrolling an agent using Fleet mode.
As it's used in three different places, we are extracting the array representing the arguments to a builder method (it requires a token), so that further updates will affect only one place.
The enrollment command changed in https://github.com/elastic/beats/pull/24155
```shell
SUITE="fleet" TAGS="fleet_mode_agent && install" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true ELASTIC_APM_ACTIVE=false make -C e2e functional-test
```
- Caused by https://github.com/elastic/beats/pull/24155
- Fixes #803
=> fix: update flags for the enroll command

e2e/_suites/fleet/services.go
- fix: update flags for the enroll command (#804)
=> fix: update flags for the enroll command (#804) backport for 7.x

e2e/_suites/fleet/services.go
- fix: update flags for the enroll command (#804)
=> fix: update flags for the enroll command (#804) backport for 6.8.x

e2e/_suites/fleet/installers.go
=> invalid option (#792) backport for 7.x

e2e/_suites/fleet/installers.go
=> invalid option (#792) backport for 6.8.x

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
This PR logs the error happened when the install certificates code fails. Adding this log, we noticed that the test scenario for the installation of the certificates was using an input parameter (`os`) that was not used, so we are removing it in consequence.
After that removal, we noticed that the TAR installer was not complete in the sense that the certs installation function was coupled to Debian only. This is working for the current implementation but could be misleading for future scenarios that would want to upgrade a Centos-based agent. For that reason, in this PR we are supporting the TAR installer package to know about the OS flavour that will be used to install the agent (centos or debian), and with that value, the install certs function will be able to call the proper package …
=> chore: add logs when OS certs are not installed for the upgrade scenario

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go
Instead of downloading all of them at the beginning of the test suite, this PR is moving the download code to when they are in fact used. In the same hand, the installers will be cached in the Installers map.
When debugging locally, the need of downloading all installers at the beginning of the test suite slows down the debug process, as they have to be downloaded every time (we use a temporary folder for the downloaded files). We could have reused those files, but we prefer doing this lazy load of the files instead, as the temporary files are in deed removed in an AfterSuite test life cycle hook.
```shell 
SUITE="fleet" TAGS="fleet_mode_agent && reenroll" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true ELASTIC_APM_ACTIVE=false make -C e2e functional-test
```
- Closes #774
The …
=> chore: download installers when they are used

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- chore: add logs when OS certs are not installed for the upgrade scenario (#809)
=> chore: add logs when OS certs are not installed for the upgrade scenario (#809) backport for 7.x

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- chore: add logs when OS certs are not installed for the upgrade scenario (#809)
=> chore: add logs when OS certs are not installed for the upgrade scenario (#809) backport for 7.11.x

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- chore: add logs when OS certs are not installed for the upgrade scenario (#809)
=> chore: add logs when OS certs are not installed for the upgrade scenario (#809) backport for 7.10.x

e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- chore: add logs when OS certs are not installed for the upgrade scenario (#809)
=> chore: add logs when OS certs are not installed for the upgrade scenario (#809) backport for 6.8.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go
- chore: download installers when they are used (#810)
=> chore: download installers when they are used (#810) backport for 7.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go
- chore: download installers when they are used (#810)
=> chore: download installers when they are used (#810) backport for 6.8.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go
- chore: download installers when they are used (#810)
=> chore: download installers when they are used (#810) backport for 7.11.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest-manager_test.go
- chore: download installers when they are used (#810)
=> chore: download installers when they are used (#810) backport for 7.10.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
It prints the elastic-agent logs at the end of each test suite, and for that we did a bit of the boy scout rule:
- first, we changed the agent log for the TAR installer: instead of using the default log (`/opt/Elastic/Agent/elastic-agent.log`), we used the JSON log (`/opt/Elastic/Agent/data/elastic-agent-$HASH/logs/elastic-agent-json.log`).
- moved code around the installer Go files, so that the responsibility for printing is clear. In the process, we removed a few attributes from the struct representing the installers, mainly used to calculate the log based on the Agent hash.
- we added a `resolveLogFile` method to the package installer, so that it's able to, with the commit file and the log dir, calculate the final log file.
- we also added a flag to signal when the elastic-agent can be …
=> feat: always print agent logs in Fleet mode

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: append "-amd64" label for Docker images (#787)
=> chore: append "-amd64" label for Docker images (#787) backport for 6.8.x

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: append "-amd64" label for Docker images (#787)
=> chore: append "-amd64" label for Docker images (#787) backport for 7.11.x

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: append "-amd64" label for Docker images (#787)
=> chore: append "-amd64" label for Docker images (#787) backport for 7.x

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/metricbeat/metricbeat_test.go
- chore: append "-amd64" label for Docker images (#787)
=> chore: append "-amd64" label for Docker images (#787) backport for 7.10.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- feat: always print agent logs in Fleet mode (#826)
=> feat: always print agent logs in Fleet mode (#826) backport for 7.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- feat: always print agent logs in Fleet mode (#826)
=> feat: always print agent logs in Fleet mode (#826) backport for 7.11.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- feat: always print agent logs in Fleet mode (#826)
=> feat: always print agent logs in Fleet mode (#826) backport for 7.10.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- feat: always print agent logs in Fleet mode (#826)
=> feat: always print agent logs in Fleet mode (#826) backport for 6.8.x

.ci/Jenkinsfile
- chore: notify upstream PR/branch the soonest (#839)
=> chore: notify upstream PR/branch the soonest (#839) backport for 7.x

.ci/Jenkinsfile
- chore: notify upstream PR/branch the soonest (#839)
=> chore: notify upstream PR/branch the soonest (#839) backport for 7.11.x

.ci/Jenkinsfile
- chore: notify upstream PR/branch the soonest (#839)
=> chore: notify upstream PR/branch the soonest (#839) backport for 7.10.x

.ci/Jenkinsfile
- chore: notify upstream PR/branch the soonest (#839)
=> chore: notify upstream PR/branch the soonest (#839) backport for 6.8.x

cli/cmd/run.go, cli/cmd/stop.go, cli/config/compose/profiles/helm/docker-compose.yml, cli/docker/docker.go, cli/services/helm.go, cli/services/kibana.go, cli/services/kubectl.go, cli/services/manager.go, cli/shell/shell.go, e2e/_suites/fleet/ingest-manager_test.go, e2e/_suites/helm/helm_charts_test.go, e2e/_suites/metricbeat/metricbeat_test.go, e2e/elasticsearch.go, e2e/steps/befores.go
It adds APM instrumentation to the Helm charts test suite, including spans for the following internal operations:
- running/stopping compose files
- waiting for Kibana to be healthy
- waiting for Elasticsearch to be healthy
- using kubectl command line
- using helm command line
- using shell command line
Besides, we created a new Go package for steps, where from now on we will be able to create shareable steps across different test suites.
Continuing with the efforts of instrumenting the test framework to detect bottlenecks.
```shell
SUITE="helm" DEVELOPER_MODE=true TIMEOUT_FACTOR=1 LOG_LEVEL=TRACE ELASTIC_APM_ACTIVE=true make -C e2e functional-test
```
- Relates #687
=> feat: instrument Helm charts test suite

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
It changes two things in how the enrollment flags are created:
1. uses `--enrollment-token=TOKEN` instead of `--enrollment-token TOKEN` for TAR installer when using the **install** command.
1. uses `--kibana-url=KIBANA_URL` flag name instead of `--url=KIBANA_URL` for RPM, DEB and TAR installers when using the **enroll** command.
We started to see consistent failures for the uninstall scenario. For some reason, and this is something @michalpristas @blakerouse @ericdavisx should confirm, I was able to reproduce the following unexpected behavior:
1. install the agent with old flags (i.e. `./elastic-agent install -f --kibana-url=http://kibana:5601 --enrollment-token TOKEN --insecure`)
1. the agent appears as enrolled in the UI, but there were no logs for the agent
1. uninstall the agent using …
=> fix: use proper flags

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- fix: use proper flags (#868)
=> fix: use proper flags (#868) backport for 6.8.x

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- fix: use proper flags (#868)
=> fix: use proper flags (#868) backport for 7.12.x

e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go
- fix: use proper flags (#868)
=> fix: use proper flags (#868) backport for 7.x

.ci/.e2e-tests.yaml, .ci/Jenkinsfile, e2e/_suites/fleet/features/agent_endpoint_integration.feature, e2e/_suites/fleet/features/backend_processes.feature, e2e/_suites/fleet/features/fleet_mode_agent.feature, e2e/_suites/fleet/features/stand_alone_agent.feature, e2e/_suites/metricbeat/features/integrations.feature
This PR refactors how the BDD feature files are structured, separating the existing examples for a scenario into multiple `Examples` block, annotated with the example type.
I.e., instead of:
```gherkin
Examples:
| image   |
| default |
| ubi8    |
```
we will have:
```gherkin
@default
Examples: default
| image   |
| default |
@ubi8
Examples: Ubi8
| image   |
| ubi8    |
```
To instruct the CI we are adding a new `pullRequestFilter` key in the E2E YAML descriptor for CI, which is read by the pipeline to configure the build, including the Gherkin tags to be appended for a PR. Therefore, the CI will append the `pullRequestFilter` tags to the tags to be added to the current execution, only for PRs.
For Fleet's endpoint integration, the PR filter will add ` ~debian`, indicating that debian …
=> feat: run most frequent flavours in the PR stage

.ci/Jenkinsfile
It uses the proper signature for the `isUpstreamTrigger` step.
Passing a simple string causes a signature error when running the pipeline. :facepalm:
- Caused by #873
Add backport commits to #880 #881 and #882
=> fix: proper usage of step

.ci/Jenkinsfile
Delete workspace
If we use static/permanent workers then we might suffer disk space issues
Closes https://github.com/elastic/e2e-testing/issues/884
https://github.com/elastic/e2e-testing/pull/707 can benefit from this :)
=> [CI] tear down the workspace

.ci/Jenkinsfile
- [CI] tear down the workspace (#885)
=> [CI] tear down the workspace (#885) backport for 7.x

.ci/e2eTestingFleetDaily.groovy
- chore: rename slack channel for Fleet's nightly build (#899)
=> chore: rename slack channel for Fleet's nightly build (#899) backport for 7.x

.ci/e2eTestingFleetDaily.groovy
- chore: rename slack channel for Fleet's nightly build (#899)
=> chore: rename slack channel for Fleet's nightly build (#899) backport for 7.12.x

.ci/e2eTestingFleetDaily.groovy
- chore: rename slack channel for Fleet's nightly build (#899)
=> chore: rename slack channel for Fleet's nightly build (#899) backport for 7.11.x

.ci/scripts/build-test.sh, cli/Makefile, commons.mk, e2e/Makefile
It creates a Make goal per test suite, so that each of them is able to generate its own jUnit report file. It uses gotestsum's `--junitfile` flag to generate the test report, using test suite name as report file name. Therefore, we are removing the `GOTESTSUM_JUNITFILE` environment variable from the script used by Jenkins.
Because Jenkins will archive all files under `outputs/TEST-unit-*.xml`, there is no need to update the Jenkinsfile.
The `GOTESTSUM_JUNITFILE` environment variable used in the CI script was the culprit of overriding the report file for multiple test suites, then the last unit test execution was the winner, overriding previous report files. With this PR, we are allowing the devveloper to have both formats: jUnit file and terminal output in the same execution of …
=> fix: generate a jUnit file per test suite

.ci/scripts/build-test.sh, cli/Makefile, commons.mk, e2e/Makefile
- fix: generate a jUnit file per test suite (#907)
=> fix: generate a jUnit file per test suite (#907) backport for 7.11.x

.ci/scripts/build-test.sh, cli/Makefile, commons.mk, e2e/Makefile
- fix: generate a jUnit file per test suite (#907)
=> fix: generate a jUnit file per test suite (#907) backport for 7.12.x

.ci/scripts/build-test.sh, cli/Makefile, commons.mk, e2e/Makefile
- fix: generate a jUnit file per test suite (#907)
=> fix: generate a jUnit file per test suite (#907) backport for 7.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest_manager_test.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/fleet/world.go, e2e/steps/befores.go, e2e/steps/processes.go, e2e/steps/services.go
- chore: follow Golang's best practices (#865)
=> chore: follow Golang's best practices (#865) backport for 7.x

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest_manager_test.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/fleet/world.go, e2e/steps/befores.go, e2e/steps/processes.go, e2e/steps/services.go
- chore: follow Golang's best practices (#865)
=> chore: follow Golang's best practices (#865) backport for 7.12.x

.ci/Jenkinsfile, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest_manager_test.go, e2e/_suites/fleet/installers.go, e2e/_suites/fleet/services.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/fleet/world.go, e2e/steps/befores.go, e2e/steps/processes.go, e2e/steps/services.go
- chore: follow Golang's best practices (#865)
=> chore: follow Golang's best practices (#865) backport for 7.11.x

e2e/_suites/fleet/README.md
For local development/testing we were missing a documented step that needed to
sync the integrations. Added this to the install dependencies section.
This updates our documentation for developers who wish to run the test suites on their local machines
The document was missing an important step for allowing the test suites to run without issue.
To verify, please follow the `Install Dependencies` section from the top down and then running:
`SUITE=metricbeat TAGS="apache" make --no-print-directory -C e2e functional-test`
=> Update missing instruction for functional-test

e2e/_suites/fleet/README.md
- Update missing instruction for functional-test (#916)
=> Update missing instruction for functional-test (#916) backport for 7.11.x

e2e/_suites/fleet/README.md
- Update missing instruction for functional-test (#916)
=> Update missing instruction for functional-test (#916) backport for 7.x

e2e/_suites/fleet/README.md
- Update missing instruction for functional-test (#916)
=> Update missing instruction for functional-test (#916) backport for 7.12.x

.mergify.yml
Quote branches
Otherwise `mergify` will complain with the str format
```
The new Mergify configuration is invalid
expected str @ pull_request_rules → item 1 → actions → backport → branches → item 0
```
=> mergify: quote the branches

.ci/Jenkinsfile
Use the new flaky analyser approach:
- elastic/apm-pipeline-library#1038
Flaky analyser has been reimplemented, let's use the new implementation
=> ci: use the new flaky analyser

e2e/_suites/metricbeat/metricbeat_test.go
It passes the platform version (amd64/arm64) to the metricbeat service, not to the integration service
It was causing failures for Beats PRs, as they downloaded the metricbeat Docker image from a GCP bucket, then it was loaded into the Docker engine and tagged. Because of this bug, the image for the platform was not correctly tagged, causing the build to fail because the Docker image was not found.
It was not discovered on master because the functionality is covered by the `BEATS_USE_CI_SNAPSHOTS` or the `BEATS_LOCAL_PATH`, and only the first one is executed on CI, for PRs.
In master:
```shell
SUITE="metricbeat" TAGS="integrations && apache" GITHUB_CHECK_SHA1="179917e2d3aa7263dd1e316b92ff87f83af4d38d" BEATS_USE_CI_SNAPSHOTS=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true make …
```
=> fix: pass platform version to metricbeat, not to the integration

cli/cmd/deploy.go, cli/cmd/run.go, cli/cmd/stop.go, cli/cmd/sync.go, cli/config/config.go
This PR adds back the log traces when a file was extracted from the box. While adding them, and testing it locally, I found that the initialisation order provided by Go init() method is not deterministic, because of that I checked that the logger init was not called at the right time. With change we ensure that the Init is:
1. called first
2. exiting if the config was already populated
It adds verbose messages about what files are bundled in the tool.
```shell
GO111MODULE=on OP_LOG_LEVEL=TRACE go run main.go run profile fleet
```
>TRAC[0037] 'op' workdirs created.                        profilesPath=/Users/mdelapenya/.op/compose/profiles servicesPath=/Users/mdelapenya/.op/compose/services
TRAC[0043] Extracting boxed file …
=> chore: add back traces when extracting the files from the box

cli/docker/docker.go, e2e/_suites/fleet/installers.go, e2e/_suites/metricbeat/metricbeat_test.go
It applies a backoff strategy for tagging a docker image, removing the active wait of 3 seconds that was sitting in front of its usages. Now the tag will be retried up-to 15 seconds, which is enough.
We detected that 3 seconds is sometimes not enough on CI, causing flakiness in the test exeuction for Beats PRs.
```shell
git checkout 7.x
SUITE="metricbeat" TAGS="integrations && haproxy" GITHUB_CHECK_SHA1="7657100c68c502b0ab2e6cc934f18a527c95d9f4" BEATS_USE_CI_SNAPSHOTS=true TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true make -C e2e functional-test
```
- Fixes #948
- Workaround until #942 is in place
See #942
=> fix: retry tagging the loaded docker image up-to 15 seconds

cli/cmd/run.go
This adds a length check on the string split for verifying that the
<service/image name>:\<tag> is defined when adding additional services to a
profile deployment.
This PR provides a simple length check during the splitting of services when being added to a profile run
Before there was no validation that a service was properly defined when being added to a profile run, so a command like the following would attempt to run:
`go run main.go run profile fleet -s elastic-agent`
We now check that at least 2 tokens exist for the <servicename-image>:<tag> and exit if not found with a helpful error message.
```
go run main.go run profile fleet -s elastic-agent
DEBU[0000] Docker compose executed.                      cmd="[up …
```
=> Add basic check on correct service is defined for profile runs

.ci/Jenkinsfile
Use the `withNode` step (https://github.com/elastic/apm-pipeline-library/blob/master/vars/withNode.groovy) 
Add self-resilience when the provisioner allocates an existing worker instead assigning a new one.
```
Step the file system Agent folder is empty
```
=> ci: use withNode step to avoid reusing workers

cli/config/compose/services/elastic-agent/docker-compose.yml, e2e/_suites/fleet/features/stand_alone_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/stand-alone.go
Starts Elastic Agent with Fleet Server and auto-enroll.
There seems to be an issue with https://github.com/elastic/e2e-testing/compare/master...jalvz:fleet-server-standalone?expand=1#diff-a6c6a3ad6fe70a90f2f59acfe75e589cd5aa7ca78361c2e26472bd2d0bb4f44eL15, removing that line the Agent enrolls correctly.
With that line, the error looks like: `/usr/share/elastic-agent/elastic-agent.yml: rename /usr/share/elastic-agent/elastic-agent.yml /usr/share/elastic-agent/elastic-agent.yml.2021-03-31T14-16-29.6932.bak: device or resource busy`
Not sure what that is.
For reference, the following also works:
`docker run --network fleet_default -e KIBANA_HOST=http://kibana:5601 -e KIBANA_USERNAME=elastic -e KIBANA_PASSWORD=changeme -e KIBANA_FLEET_SETUP=1 -e FLEET_SERVER_ENABLE=1 -e …
=> Add a standalone test scenario for fleet server mode

.ci/.package.yaml, .ci/Jenkinsfile, .goreleaser.yml
As a consequence of #977, this PR:
- Extends `goreleaser` configuration with release info. This will allow the creation of a Github release for the current git tag, also uploading `/dist` contents to the new Github release.
- Removes the parallel branch to build the binaries for multiple platforms when git tags are pushed to Github, and the custom metadata file used to branch the release process.
- Instead of using the convenient-for-local-development `make build` command on Jenkins, it uses an inline script to execute `goreleaser` (See https://goreleaser.com/ci/jenkins/).
- The Jenkins script is performed within a retry block to improve the reliability when downloading the script.
- It will make sure the `/dist` directory is empty, passing `--rm-dist` flags to the inline script.
- It …
=> chore: simplify release process on Jenkins

cli/README.md, cli/cmd/run.go
This provides ability to pass in `-e key=value` to allow applying additional
environment settings to the profiles/services
Also changes the way services are declared by allowing to pass in multiple `-s`
flags instead of doing the string parsing
Converts passing multiple services to utilize the `-s service_name:tag -s service_nam_2:tag` approach. Adds ability to pass in multiple `-e key=val` items when wanting to customize the variables within the docker-compose templates
Adds another layer of validation for parsing additional services via the cli without doing the `strings.Split(',')`. Adds additional customization options via environment variables and follows the same approach as both docker/docker-compose when …
=> cli: support passing in environment options and better service def

e2e/_suites/fleet/features/stand_alone_agent.feature, e2e/_suites/fleet/stand-alone.go
There were 2 steps identical in both the stand-alone and fleet test suites.
Running the stand-alone test suite was picking up the step from the fleet test
suite and trying to reference the FleetTestSuite structure which did not hold
any of the agent information (like the hostname) for the stand alone tests.
This fixes it so that the standalone test step is being referenced in the
correct test suite.
Makes the steps unique between stand-alone and fleet test suites
The stand-alone tests were incorrectly picking up steps from the fleet test suite
```
e2e/_suites/fleet/ > godog -t '@run_fleet_server'
```
- Closes #984
=> Uniquify the stand-alone step for checking agent status

cli/config/compose/services/elastic-agent/docker-compose.yml, e2e/_suites/fleet/stand-alone.go
This removes the volume mounting of elastic-agent.yml for fleet server stand alone. The side effect is that we will have to think about how we want to approach fleet mode outside of that. Currently in stand alone that config file is not useful and it causes device and resource errors when mounting inside of docker when operations within the elastic-agent occur.
I think for the other use cases we can tests integrations etc more dynamically than having elastic-agent.yml mounted as a volume. Thoughts?
Testing standalone fleet server will fail if this configuration and volume exists
- Closes #981
=> Remove the agent config file parameters for stand alone

cli/config/compose/services/elastic-agent/docker-compose.yml, e2e/_suites/fleet/features/stand_alone_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/stand-alone.go
It reverts the following PRs:
- Revert "Add a standalone test scenario for fleet server mode (#978) (#987)"
- Revert "Uniquify the stand-alone step for checking agent status (#993) (#996)"
Fleet Server is available from 7.13 and beyond, so it does not apply to 7.12.x
=> chore: revert standalone scenario for fleet server in 7.12

.mergify.yml
Mergify now supports the original author assignation. https://docs.mergify.io/actions/backport/#options. Besides, use the `merged` condition to avoid waiting GH commit status checks while this should be a post-merge event based.
To help with the tracking when mergify creates backports
=> [mergify] assign the original author

e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest_manager_test.go, e2e/_suites/helm/helm_charts_test.go, e2e/_suites/metricbeat/metricbeat_test.go, e2e/utils.go
It moves the initialisation of the stale agent version from the setup suite phase (before any scenario) to the only step it's used (deploying an stale agent to      Fleet).
Besides that, we detected that the namespace for the custom kibana image was not properly set, so we are making sure the custom version starts with "pr" (it's a PR)
to use the proper Docker namespace.
Finally, we are changing the signature of the method to check if a version is an alias, returning the error so that the caller handles it in whatever manner it needs, instead of handling it in the internal method.
It will avoid failing all scenarios if the stale agent version is not found. Instead it will fail the step. Therefore setup methods will fail the setup with `log.Fatal`, and steps will simply return the error, …
=> fix: delay checking stale agent version until it's used

.ci/e2eKibana.groovy
It uses an ubuntu 20 agent to build the job.
It fixes the following error on CI:
>ERROR: Attempted to execute a step that requires a node context while ‘agent none’ was specified. Be sure to specify your own ‘node { ... }’ blocks when using ‘agent none’.
=> fix: use an agent when building kibana

.ci/e2eKibana.groovy
It verifies that the base ref for the Kibana PR is master, keeping the e2e branch name equals to the base ref in the case it's "master". For other base refs, it will append the '.x' suffix, to keep consistency with e2e maintenance branches.
PRs against master were not covered, as the suffix was always appended.
- Relates #1035
=> fix: apply X version for non-master branches

.ci/e2eKibana.groovy
- fix: add NodeJS to PATH (#1035)
- fix: apply X version for non-master branches (#1037)
=> fix: add NodeJS to PATH (#1035) | fix: apply X version for non-master branches (#1037) backport for 7.x

.ci/e2eKibana.groovy
- fix: add NodeJS to PATH (#1035)
- fix: apply X version for non-master branches (#1037)
=> fix: add NodeJS to PATH (#1035) | fix: apply X version for non-master branches (#1037) backport for 7.12.x

.ci/e2eKibana.groovy
- fix: add NodeJS to PATH (#1035)
- fix: apply X version for non-master branches (#1037)
=> fix: add NodeJS to PATH (#1035) | fix: apply X version for non-master branches (#1037) backport for 7.11.x

cli/config/compose/services/elastic-agent/docker-compose.yml, e2e/_suites/fleet/features/stand_alone_agent.feature
Changes the Elastic Agent service in the docker compose file to use Elasticsearch instead of Kibana
Because of updates on Fleet Server
=> Update Elastic Agent to not use Kibana

.ci/e2eKibana.groovy
Uses the right variable interpolation in groovy:
```groovy
// incorrect
if ($env.VAR == "true") {}
//correct
if (env.VAR == "true") {}
```
Fix error:
>java.lang.NoSuchMethodError: No such DSL method '$' found among steps
- Completes #1037
=> fix: wrong interpolation

.ci/e2eKibana.groovy
It updates the buid cause string including HEAD_SHA, BASE_REF and PR_ID
I'd like to verify that the `pull_request` JSON object is returned in the weebhook payload.
We found the original error:
>hudson.AbortException: No item named e2e-tests/e2e-testing-mbp/null.x found
So this groovy block always evals to true, appending '.x' to the branch name, in this case `null`:
```groovy
def branchName = "${env.GT_BASE_REF}"
if (env.GT_BASE_REF != "master") {
branchName = "${env.GT_BASE_REF}.x"
}
```
=> chore: add debug traces for the webhook payload

.ci/e2eKibana.groovy
It renames variable not to pollute variable namespace, adding log traces for getting the payload
It seems the `pull_request` field is not present in the payload when a comment is added to a PR, and this field is used to calculate the target branch and the current SHA of the PR
-
=> chore: add debug info for the payload

.ci/e2eKibana.groovy
It adds a comma separating parameters for the generic webhook trigger
My fault...
- Caused by #1044
=> fix: typo in parameters

.ci/e2eKibana.groovy
It creates a global env var for repo name (`elastic/kibana`), which will be used instead of the usages of GT_REPO.
We noticed that, although the webhook event was properly captured by `regexpFilterText: '$GT_REPO$GT_BODY'`, at the moment we used it later in the pipeline, **for a manual trigger**, the `GT_REPO` variable was `null`. I.e.:
```groovy
def pullRequest = githubApiCall(token: token, url: "https://api.github.com/repos/${env.GT_REPO}/pulls/${prID}")
```
See https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-kibana-fleet/detail/e2e-testing-kibana-fleet/19/pipeline/
>githubApiCall: The REST API call https://api.github.com/repos/null/pulls/97041 return the message : java.lang.Exception: httpRequest: Failure connecting to the service …
=> fix: do not use GT_REPO variable, use fixed repo name instead

e2e/_suites/fleet/ingest_manager_test.go
It removes the initialisation of the stale agent in the fleet test suite, as it's already checked in the specific step for the stale agent. We delayed fetching the stale version in #1016
It fails fast when the version is not present, and for the stale agent, which is only executed on nightlies, we don't want to fail fast.
- Caused by #1008
- Relates #1016
=> chore: initialise stale agent only when used

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, internal/kubernetes/kubernetes.go
This is mainly a cleanup to keep all internal related code that could be
reusable in our `internal` directory layout.
Next steps would be to take what's in `internal/kubectl` and merge with this code.
This is mainly moving files around and placing the kubernetes/kubectl/kind specific information under a `kubernetes` namespace
Keep the project structure consistent
```
cd e2e/_suites/kubernetes-autodiscover
OP_LOG_LEVEL=TRACE godog
```
=> Move kubernetes/kubectl/kind code to internal project layout

.ci/build-docker-images.groovy, .ci/jobs/build-docker-images.yml
It reverts dddba263159f3fa8b30bd7f973d7e75ead6ce22b, as the branch_specifier is required, although failing the first time the build is executed (params are not there).
We are changing the schedued trigger to daily
- Caused by #1093
=> fix: branch_specifier is needed

.pre-commit-config.yaml, cli/config/kubernetes/README.md, cli/config/kubernetes/base/elasticsearch/configmap.yaml, cli/config/kubernetes/base/elasticsearch/deployment.yaml, cli/config/kubernetes/base/elasticsearch/kustomization.yaml, cli/config/kubernetes/base/elasticsearch/service.yaml, cli/config/kubernetes/base/fleet-server/cluster-role-binding.yaml, cli/config/kubernetes/base/fleet-server/cluster-role.yaml, cli/config/kubernetes/base/fleet-server/deployment.yaml, cli/config/kubernetes/base/fleet-server/kustomization.yaml, cli/config/kubernetes/base/fleet-server/role-binding.yaml, cli/config/kubernetes/base/fleet-server/role.yaml, cli/config/kubernetes/base/fleet-server/service.yaml, cli/config/kubernetes/base/kibana/configmap.yaml, cli/config/kubernetes/base/kibana/deployment.yaml, cli/config/kubernetes/base/kibana/kustomization.yaml, cli/config/kubernetes/base/kibana/service.yaml, cli/config/kubernetes/base/kustomization.yaml, cli/config/kubernetes/base/package-registry/deployment.yaml, cli/config/kubernetes/base/package-registry/kustomization.yaml, cli/config/kubernetes/base/package-registry/service.yaml, cli/config/kubernetes/kind.yaml, cli/config/kubernetes/overlays/local/ingress.yaml, cli/config/kubernetes/overlays/local/kustomization.yaml, cli/config/kubernetes/overlays/local/nginx-ingress.yaml
Adds ability to deploy Elasticsearch, Kibana, Fleet Server (bootstrapped) into a Kubernetes cluster
Adds necessary manifests to deploy a full EKF stack with optional ingress support for local development and testing
Would like to utilize this deployment tactic to run our e2e test suites against local and remote kubernetes clusters
=> Kubernetes Deployment

cli/config/compose/profiles/fleet/configurations/kibana.config.yml, cli/config/compose/profiles/fleet/docker-compose.yml, e2e/_suites/fleet/ingest_manager_test.go
This makes fleet server automatically available in bootstrapped mode so that additional agents just need to enroll in the default policy for tests.
Speeds up the test scenarios by having a working environment to test the additional elastic-agents
=> Auto bootstrap fleet during initialize scenario

e2e/_suites/fleet/ingest_manager_test.go, e2e/_suites/helm/helm_charts_test.go, e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, internal/common/retry.go
It initialises the timeout factor in the common package, avaoiding the multiple initialisation performed in all test suites.
Besides that, we removed a local version of the timeout factor variable for the Helm test suite, using the default one.
DRY and KISS
- Suggested by @jsoriano in https://github.com/elastic/e2e-testing/pull/1115#discussion_r625185882
=> chore: initialise timeout factor next to the declaration

e2e/_suites/fleet/features/apm_integration.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest_manager_test.go, e2e/_suites/fleet/stand-alone.go, e2e/_suites/fleet/world.go
Unifies fleet and stand alone suites
This makes steps reusable 
Closes https://github.com/elastic/e2e-testing/issues/1109
=> Unify fleet and stand-alone suites

.ci/Jenkinsfile, internal/common/defaults.go
It uses one minor version for the stale agent
For master branch, using 8.0.0-SNAPSHOT, it's incorrect to use 7.11-SNAPSHOT as stale agent, as that version has disappeared from the artifactory.
Thinkg about upgrade processes, what if we want to test the upgrade of an old version? Using the artifact repository won't be enough, as versions disappears after 2 minor versions of the stack.
Maybe this is something to ask infra, about allowing accessing those old versions from another repository.
=> fix: bump stale agent to 7.13-SNAPSHOT

internal/utils/utils.go
It renames the Beats binary downloaded from a GCP bucket, using the artifact name (i.e. elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm) that was calculated before that.
I added the following test, but removed it as it's very dependendant on the network and the availability of GCP:
```golang
func TestFetchBeatsBinary(t *testing.T) {
os.Setenv("BEATS_USE_CI_SNAPSHOTS", "true")
os.Setenv("GITHUB_CHECK_SHA1", "b989478a3003c1b41722b7245586d58d832748a4")
f, err := FetchBeatsBinary("elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm", "elastic-agent", "8.0.0-SNAPSHOT", "8.0.0-SNAPSHOT", 3, true)
assert.Nil(t, err)
defer os.Remove(filepath.Dir(f))
defer os.Unsetenv("BEATS_USE_CI_SNAPSHOTS")
defer os.Unsetenv("GITHUB_CHECK_SHA1")
// name has been sanitised
assert.True(t, strings.HasSuffix(f, …
```
=> fix: rename downloaded file using artifact name

e2e/_suites/fleet/features/backend_processes.feature, e2e/_suites/fleet/features/stand_alone_agent.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/ingest_manager_test.go, e2e/_suites/fleet/world.go, internal/docker/docker.go
It creates a new step that abstract the logic to get the number of processes in a desired state, calling this new step in the existing one (with 1 as number of ocurrences).
We had to refactor the existing code to wait for processes, as it only checked that a process existed in the host using `pgrep -n -l`, which only checks for the existence of the latest process for a process.
With this new approach, we are switching to `pgrep -d , $THE_PROCESS`, which separates each pid for the process with the comma delimiter. Having that list of pids for a process we execute `ps -q $PID -o state --no-headers` (linux only) to get the current state of that pid, to discard zombie processes (we detected that the elastic-agent on Centos creates 3 processes, 2 of them in the zombie state cc/ …
=> feat: check how many processes of a process are running in the host

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, internal/deploy/docker_client.go
This PR does two things:
- uses the timeout factor to tag images, as we showed an error in #1165 in the first scenario ot being able to tag the image on time.
- uses the initialisation of versions from the common package
The beat version was not resolved when it was an alias (i.e. in maintenance branches), and the Docker image loaded from Beats CI was too slow, for that reason we are using test framework's timeout factor, which multiplies by 5 the default timeout.
Run a test suite for Beats, in this case a PR against master:
```shell
SUITE="kubernetes-autodiscover" TAGS="heartbeat" TIMEOUT_FACTOR=3 BEATS_USE_CI_SNAPSHOTS=true GITHUB_CHECK_SHA1=de9f51b9dc4c297e0df2f946d5ada9ee739ca147 LOG_LEVEL=TRACE BEATS_USE_CI_SNAPSHOTS=true ELASTIC_APM_ACTIVE=false DEVELOPER_MODE=true make -C e2e …
```
=> fix: resolve issues in k8s-autodiscover test suite

.ci/docker/debian-systemd/Dockerfile
It makes sure the Debian image contains the tools used in the tests, in particular installing `procps`, which installs pgrep and ps, used in the project to do operations on backend processes.
We need the images to contain this package, otherwise debian tests will fail for both AMD and ARM.
Verified that the Debian image does not contain that package, so building the image with this PR will result in a container where it's possible to run `pgrep`.
- Needed by #707
- Relates #864
We need to build the images first before running the tests for #707, so that the images get refreshed with the new code
=> fix: make sure debian boxes have the right tools for testing

cli/config/compose/profiles/fleet/configurations/kibana.config.yml
It uses a proper format for the value of kibana's server host, matching that value with other maintenance branches (master, 7.13, 7.12, 7.11)
Kibana cannot start, therefore the runtime dependencies for the tests are not satisfied, causing the entire test suite to fail.
- Fixes #1194
=> fix: use proper format for kibana's server host

.ci/Jenkinsfile
It avoids using the `platform` variable out of its Groovy scope.
The pipeline will fail whenever the else branch of the isGitRegionMatch is false. This bug will appear whenever there is a replay in the pipeline, or there are no changes in the git-regions defined by the regex. Before these changes, the log entry in the else branch would try to print the platform, which was declared in the if branch of the evaluation.
- Caused by #707
Backport to 7.x and 7.13.x
=> fix: do not use variable out of its scope

.ci/Jenkinsfile
- fix: do not use variable out of its scope (#1231)
=> fix: do not use variable out of its scope (#1231) backport for 7.x

.ci/Jenkinsfile
Backports the following commits to 7.13.x:
- fix: do not use variable out of its scope (#1231)
=> fix: do not use variable out of its scope (#1231) backport for 7.13.x

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, internal/kubernetes/kubernetes.go
This PR adds APM traces for the k8s autodiscover test suite, and for that we had to basically pass the Go context through all API methods. We are:
- starting a transaction before the test scenario
- adding a span for each internal operation/method, passing the current context as parent
- each operation defers the close of the span
- closing the transaction after the test scenario
- using Godog's `beforeStep/afterStep` life cycle hooks to automatically create/close spans per scenario step, which will serve as parent span for the internal operations within it. This life cycle hook will be used to capture step errors, sending APM errors to the Cloud.
- using Godog's `beforeScenario/afterScenario` life cycle hooks to start/flush the transaction for each scenario. The transaction will receive …
=> feat: instrument k8s-autodiscover with APM

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, e2e/_suites/metricbeat/metricbeat_test.go, internal/common/defaults.go, internal/installer/elasticagent_deb.go, internal/installer/elasticagent_docker.go, internal/installer/elasticagent_rpm.go, internal/installer/elasticagent_tar.go, internal/utils/utils.go, internal/utils/utils_test.go
It uses the BEAT_VERSION variable as fallback when provided. For that reason, upstream jobs must provide the Beat version, as they must know in which version they want to run the tests.
On the same hand, we are simplifying the methods to calculate the paths, removing the need to pass a fallback version, as this is already calculated at the initialisation of the configuration/environment, within the InitVersions method.
Builds triggered by Beats maintenance branches are not able to calculate the right paths to fetch binaries from GCP, and this is caused because the Beats version is a moving target that cannot be calculated without inspecting Beats code (libbeat/version/version.go). I.e., last 7.13 commit is using 7.13.2 as version, which created 7.13.2-SNAPSHOT artifacts in GCP.
```shell …
```
=> fix: use beat_version as fallback if it's provided

.ci/e2eKibana.groovy
It removes an unnecessary `deleteDir` step.
This delete dir wipe the workspace, so it deletes the `.ci` folder with all the content, the content there is needed in the `Push multiplatform manifest`
```
[2021-06-21T16:17:28.547Z] + .ci/scripts/push-multiplatform-manifest.sh kibana pr101828
[2021-06-21T16:17:28.547Z] /var/lib/jenkins/workspace/e2e-tests/e2e-testing-kibana-fleet/src/github.com/elastic/kibana@tmp/durable-85846351/script.sh: 1: .ci/scripts/push-multiplatform-manifest.sh: not found
[2021-06-21T16:17:28.753Z] Terminated
script returned exit code 127
```
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have …
=> fix: .ci/scripts/push-multiplatform-manifest.sh: not found

cli/config/compose/profiles/fleet/docker-compose.yml
Currently there is a bug in the way kibana docker image is built that doesnt
pull in all the environment variables:
https://github.com/elastic/kibana/issues/103084
We can revert back to using environment vars once this bug is resolved
Goes back to bind mounting the kibana config
There currently is a bug in the way Kibana docker image is built when converting environment variables found in docker-compose to be passed along to the kibana cli.
- Closed #1273
=> Re-use bind mounts for kibana docker image

.ci/.e2e-tests.yaml, e2e/_suites/fleet/features/running_on_top_of_beats.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, e2e/_suites/metricbeat/metricbeat_test.go, e2e/steps/configurations.go, internal/deploy/base.go, internal/deploy/base_test.go, internal/installer/base.go, internal/installer/elasticagent_deb.go, internal/installer/elasticagent_docker.go, internal/installer/elasticagent_rpm.go, internal/installer/elasticagent_tar.go, internal/utils/utils.go, internal/utils/utils_test.go
This PR reuse existing building blocks to create a new scenario in which the elastic-agent installer is installed on a vanilla systemd linux box (Centos and Debian) which has already installed certain Beats processes (filebeat, metricbeat).
For that reason, we are adding the ability to add background processes to the ServiceRequest struct, so that the installer code for a service is able to also install those processes before installing the agent. We are installing these beats processes using the same mechanism as the one used to install the agent, which means fetching the DEB, RPM files from the artifactory, and then using local tools (APT, YUM) to install them in the aforementioned vanilla linux container.
We are installing the beat in a linux container instead of using the official …
=> feat: support running elastic-agent alongside Beats

internal/installer/elasticagent_zip.go
Backports the following commits to 7.14.x:
- fix: use new method to calculate binary paths in ZIP installer (#1297)
=> fix: use new method to calculate binary paths in ZIP installer (#1297) backport for 7.14.x

.ci/.e2e-tests.yaml, e2e/_suites/metricbeat/features/integrations.feature, internal/sanitizer/sanitizer.go, internal/sanitizer/sanitizer_test.go
This PR adds the recently added "x-pack's MSSQL integration for metricbeat" to the Metricbeat test suite. We need to massage the configuration files a bit, that's why we are adding a new sanitizer for the incoming config files from Beats repo, whic basically means applying MSSQL Server's default credentials: (user: `sa`, password `1234_asdf`).
We found that the MSSQL Server integration was broken in Beats (see elastic/beats#26440) , and for that reason we want to add this test as part of the regression test suite.
To run the unit tests:
```shell
make unit-test
```
To run the E2E tests for the new integration:
```shell
TAGS="integrations && mssql" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true make -C e2e/_suites/metricbeat functional-test
```
- Relates elastic/beats#26440
=> feat: support MSSQL Server integration in tests

cli/config/compose/services/elastic-agent/centos/docker-compose.yml, cli/config/compose/services/elastic-agent/cloud/docker-compose.yml, cli/config/compose/services/elastic-agent/debian/docker-compose.yml, cli/config/compose/services/elastic-agent/docker-compose.yml, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/stand-alone.go
This PR avoids overridding the `container_name` of the elastic-agent service in a Docker Compose file, which avoids not needed calculations.
I found an error while running the tests against a local version of the stack, and after debugging, found that if the DEV_MODE is enabled (services are not destroyed) the local Docker daemon is not able to recreate the containers properly.
I've not found an open issue related to this in the Compose repo, but I upgraded my local Docker engine very recently.
```shell
$ docker --version
Docker version 20.10.7, build f0df350
$ docker-compose --version
Docker Compose version v2.0.0-beta.6
```
I could have downgraded my local version and have tested again, but I consider this change (delegating the container name to Docker) should cover this use case.
On …
=> fix: apply container name to elastic-agent Docker services

.ci/Jenkinsfile
It forces `centos-8-arm` as the label used by Jenkins to grab the CI workers when the tests need to be run on ARM.
We are seeing certain flakiness in one single scenario for Debian (See https://github.com/elastic/e2e-testing/issues/1271) and we'd like to narrow down the issue: because we have multiple ARM CI workers under the `arm` label, we want to always use the same.
- Relates https://github.com/elastic/e2e-testing/issues/1271
- Relates https://github.com/elastic/e2e-testing/issues/1340
=> chore(ci): be more specific about the underlying ARM OS

internal/installer/base.go, internal/installer/elasticagent_deb.go, internal/installer/elasticagent_rpm.go, internal/installer/elasticagent_tar.go, internal/installer/elasticagent_tar_macos.go, internal/installer/elasticagent_zip.go, internal/systemd/cmds.go
This PR adds a method to read Linux's service manager (systemd) logs. In particular for Linux it uses `journalctl` CLI.
For Mac and Windows, we are adding a TODO until we clarify how do we want to read the log files: using native tools or directly reading the log files.
For agents installed in plain Centos/Debian, using deb, rpm, tar files as installer, the elastic-agent log is not the container log. For that reason we need to have a manner to read agent logs and expose them to the developer (on CI or local).
Simply run any fleet test:
```shell
TAGS="fleet_mode_agent && install"   TIMEOUT_FACTOR=3    LOG_LEVEL=INFO    DEVELOPER_MODE=true    ELASTIC_APM_ACTIVE=false make -C e2e/_suites/fleet functional-test
```
The log of the elastic-agent service must be printed in the console.
- Closes …
=> chore: read elastic-agent logs using native OS' log manager

internal/installer/base.go, internal/installer/elasticagent_deb.go, internal/installer/elasticagent_rpm.go, internal/installer/elasticagent_tar.go, internal/installer/elasticagent_tar_macos.go, internal/installer/elasticagent_zip.go, internal/systemd/cmds.go
- chore: read elastic-agent logs using native OS' log manager (#1368)
=> chore: read elastic-agent logs using native OS' log manager (#1368) backport for 7.x

.ci/e2eTestingK8SAutodiscoveryDaily.groovy, .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml, README.md
- feat: add scheduled pipeline for k8s autodiscovery test suite (#1100)
=> feat: add scheduled pipeline for k8s autodiscovery test suite (#1100)

.backportrc.json, .ci/jobs/e2e-testing-fleet-daily-mbp.yml, .ci/jobs/e2e-testing-helm-daily-mbp.yml, .ci/jobs/e2e-testing-integrations-daily-mbp.yml, .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml, .ci/jobs/e2e-testing-mbp.yml
- chore(ci): listen for 7.14 branch, retiring 7.12 (#1300)
=> chore(ci): listen for 7.14 branch, retiring 7.12 (#1300) backport for 7.x

.ci/e2eKibana.groovy, .ci/e2eTestingFleetDaily.groovy, .ci/e2eTestingHelmDaily.groovy, .ci/e2eTestingIntegrationsDaily.groovy, .ci/e2eTestingK8SAutodiscoveryDaily.groovy
- chore(ci): propagate downstream build result to upstream (#1377)
=> chore(ci): propagate downstream build result to upstream (#1377)

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, e2e/_suites/kubernetes-autodiscover/features/filebeat.feature, e2e/_suites/kubernetes-autodiscover/testdata/templates/filebeat.yml.tmpl
Add test case for add_kubernetes_metadata with autodiscover as suggested in https://github.com/elastic/e2e-testing/pull/1361#discussion_r676322993.
Even if this configuration is not recommended, there is nothing preventing it.
-
=> Add test case for add_kubernetes_metadata with autodiscover

.ci/e2eKibana.groovy, .ci/e2eTestingFleetDaily.groovy, .ci/e2eTestingHelmDaily.groovy, .ci/e2eTestingIntegrationsDaily.groovy, .ci/e2eTestingK8SAutodiscoveryDaily.groovy
It forces the scheduled pipelines to wait for the downstream job.
Setting `propagate: true` is not enough, as it seems Jenkins is not able to update the state of a build once it has finished. Adding `wait: true` we expect to achieve what we want.
- Completes #1377
- Closes #1376
=> fix(ci): wait for downstream jobs on scheduled jobs

internal/utils/utils.go, internal/utils/utils_test.go
When checking the version using Elastic's versions API, this PR adds a verification for the version to have a commit sha between the semver version and the SNAPSHOT suffix. If it does contain it, then the API is not looked up. To achieve it we added a helper method as an utility, where we use a regex that checks for `X.Y.Z-sha-SNAPSHOT`. We added unit tests verifying the new behaviour.
On the same hand, we noticed that the existing `IsCommit` method would return true for this hashed snapshots, so when checking Kibana version we used that method to change the Docker namespace for the image. With the previous implementation the method would return true, changing the namespace to `observability-ci`. For that reason we improved the regex in there to check for commits from the first position …
=> fix: check if the snapshot version contains a commit

internal/utils/utils.go
It removes the SNAPSHOT suffix when downloading artifacts from Elastic's artifacts API for a version containing a commit (i.e. 8.0.0-abcdef-SNAPSHOT)
The artifacts API supports passing the version and the commit, but removing the SNAPSHOT (i.e. 8.0.0-abcdef).
To complete an automated bump of the version, we have to include this check, which was not included in previous patches.
Passing a BEAT_VERSION that is available in the Artifacts API:
```shell
TAGS="apm_server" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE BEAT_VERSION=8.0.0-cf3e6139-SNAPSHOT DEVELOPER_MODE=true ELASTIC_APM_ACTIVE=false make -C e2e/_suites/fleet functional-test
```
- Completes #1406
=> fix: parse hashed version to download artifacts from Elastic

.ci/.e2e-tests.yaml, e2e/_suites/fleet/ingest_manager_test.go
This PR does two things:
1. removes the endpoint security scenarios from CI
1. when the provider is "remote", it avoids dealing with runtime deps (the stack) before and after the fleet test suite
1. as per @EricDavisX's comment: 
>Regarding this, Endpoint is not supported in a Docker container. The wisest move is to stop testing until such time as they have it implemented (it is a priority and being heavily staffed, and developed immediately, fyi - it could be months or a year or more before support is confirmed tho)
We could maybe move all tests to a remote approach, where all binaries are installed on CI workers, dealing with real systems.
2. avoid consuming non-needed resources: we are skipping the provisioning/destruction of runtime deps (the stack) when the provider is remote, which …
=> chore: skip endpoint scenarios from CI

e2e/_suites/metricbeat/metricbeat_test.go, internal/installer/elasticagent_tar.go, internal/installer/elasticagent_tar_macos.go, internal/installer/elasticagent_zip.go, internal/utils/utils.go, internal/utils/utils_test.go, internal/versions.go, internal/versions_test.go
Backports the following commits to 7.13.x:
- chore: calculate version in context (#1459)
=> chore: calculate version in context (#1459) backport for 7.13.x

.ci/Jenkinsfile
It moves the usage of the filebeat step to a place before the `dir(BASE_DIR)` step.
We have detected that, since #1330, we are not archiving the container logs produced by filebeat, and these files are key for troubleshooting stack problems (es, kibana, fleet-seerver)
Verify in Jenkins UI that the files are stored without errors
- Caused by #1330 
The CI log when archiving the container logs files:
>[2021-08-19T18:55:09.022Z] Archiving artifacts
[2021-08-19T18:55:09.736Z] ‘**/docker_logs_amd64_fleet_APM Integration.log*’ doesn’t match anything: ‘**’ exists but not ‘**/docker_logs_amd64_fleet_APM Integration.log*’
[2021-08-19T18:55:09.736Z] No artifacts found that match the file pattern "**/docker_logs_amd64_fleet_APM Integration.log*". Configuration error?
script returned exit code 2
=> fix: proper usage of filebeat step

.stack-version
Bump stack version with the latest one. 
[start_time:Mon, 13 Sep 2021 05:14:31 GMT, release_branch:7.x, prefix:, end_time:Mon, 13 Sep 2021 11:50:59 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-f4fa0a64, build_duration_seconds:23788]
=> [automation] update elastic stack version for testing 7.16.0-f4fa0a64

.ci/e2eFleetServer.groovy, .ci/e2eKibana.groovy, .ci/jobs/fleet-server-e2e-tests.yml, e2e/_suites/fleet/stand-alone.go, e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, internal/deploy/docker.go, internal/versions.go, internal/versions_test.go
This PR adds a regular pipeline listening for Fleet Server repository's webhook, extracting from that payload the information to build the code.
It will detect a GH comment with `/run-fleet-e2e-tests`, triggering a build right after the comment is submitted. Besides that, it's possible to manually run this job using the PR ID as input parameter.
Once the FS PR is extracted it:
- fetches Fleet Server code for that PR, building the binaries, copying the binaries to the AGENT_DROP_PATH, a special folder used to build the agent with anything on it.
- in parallel with the above, fetches Beats repo and builds Elastic Agent's dependencies (building the agent, basically). It will copy Heartbeat, Filebeat and Metricbeat binaries from x-pack dirs to the AGENT_DROP_PATH.
- after the above parallel …
=> feat: run E2E tests for Fleet Server

.ci/e2eFleetServer.groovy
This PR builds the affected repos in the right branches:
- fleet-server: if there is a payload comming from a PR in the repo (via GH comment), it will build the 'PR/#ID' branch. Same if it's manually triggered using a PR ID as input     paramenter. If a branch is used as input parameter (i.e. `master`, `7.16`, `7.x`) the the branch will be used as is.
- beats: it will use what comes in the `$BASE_REF` variable, which is set in the first stage of the pipeline, within the `getE2EBaseBranch()` helper method. This method will       internally set the env var to the baseRef attribute of the payload retrieved by our API call, which uses what comes from the webhook or in the input parameter. If a branch is used as an input parameter, it will build the same Beats branch.
Build what is right …
=> fix: build each repository in the right branch

.ci/e2eKibana.groovy
It uses the right variable when logging what PR to use
We were using a variable that was not defined, causing the pipeline to fail:
```stacktrace
[2021-10-01T14:26:25.738Z] ERROR: Unable to run e2e tests
[2021-10-01T14:26:25.739Z] groovy.lang.MissingPropertyException: No such property: prID for class: groovy.lang.Binding
[2021-10-01T14:26:25.739Z] 	at groovy.lang.Binding.getVariable(Binding.java:63)
[2021-10-01T14:26:25.739Z] 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:271)
[2021-10-01T14:26:25.739Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
[2021-10-01T14:26:25.739Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
[2021-10-01T14:26:25.739Z] 	at …
```
=> fix(ci): use the right variable

.ci/e2eKibana.groovy
It sets the `BASE_REF` variable using the branch name if it's not a PR ID, or the baseRef attribute of the payload retrieved from the API call representing the PR ID.
Again, that variable was used but not set, failing with this stacktrace:
```stacktrace
[2021-10-01T16:01:54.982Z] ERROR: Unable to run e2e tests
[2021-10-01T16:01:54.983Z] groovy.lang.MissingPropertyException: No such property: baseRef for class: groovy.lang.Binding
[2021-10-01T16:01:54.983Z] 	at groovy.lang.Binding.getVariable(Binding.java:63)
[2021-10-01T16:01:54.983Z] 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:271)
[2021-10-01T16:01:54.983Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
[2021-10-01T16:01:54.983Z] 	at …
```
=> fix(ci): set base ref for kibana build

cli/config/compose/profiles/fleet/default/package-registry.config.yml, cli/config/compose/profiles/fleet/docker-compose.yml, cli/config/compose/profiles/fleet/preconfigured-policies/package-registry.config.yml
It adds the package-registry to the compose file used by the Docker provider, copying the configurations of the elastic-package profiles to current kibana configs.
The elastic-package provider is starting the registry locally, but we removed it from our own implementation in #707.
In the ARM flavour of the test suite, where we cannot use elastic-package, we need to add it back, to bypass the issues we found for the staging/snapshot/production package registry and kibana's recent breaking changes, where no packages are retrieved for 8.0.
For that reason, we need the local package registry in the Docker compose.
- Relates #1738
=> fix: run local package registry with docker provider

cli/config/compose/profiles/fleet/default/kibana.config.yml, cli/config/compose/profiles/fleet/preconfigured-policies/kibana.config.yml, internal/deploy/elastic_package.go
It uses the staging environment of EPR, as it contains the system package in 7.16
FOr the elastic-package provider, we are removing the package-registry service from the startup list.
Keep consistent and clean deployments, without using the local package registry at all.
- Relates #1737
=> fix: use staging env for package registry

internal/deploy/elastic_package.go
This PR reverts the SRC/TARGET file paths used to check and copy the kibana configs from our compose config dir when copying that kibana config to a newly created elastic-package profile.
The src file, which the code checks its existence, must always follow the `kibana.config.yml` file name, and the target file, where the code copies the src file to, must always follow the elastic-package naming-schema for the config: `kibana.config.8x.yml` for master or `kibana.config.default.yml`.
Whenever an scenario is using a profile different than `default`, as we do in the preconfigured-policies feature file, the code will incorrectly check for the existence under the compose config dir of a '8x' file, which does not exist, causing in the following error thrown by elastic-package:
```shell …
```
=> fix: properly copy files from compose to elastic-package

.mergify.yml
PoC regarding the mergify notifications when backported PRs created by `mergify` have not been merged yet. 
This will verify only those PRs created by `mergify` every day and in case they have not been merged yet, then a GitHub comment will be added.
Ensure the notifications regarding missing merged backports are addressed.
- ~~Do we wanna enable this only after a certain period of time? -> See [example](https://docs.mergify.com/configuration/#relative-timestamp)~~ No, for the time being and we can use the `"#check-success>0"`
- ~~Does the `assignee` works in the comment template?~~ Yes
=> [mergify] notify to the assignee if PR was not merged yet

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, e2e/_suites/kubernetes-autodiscover/testdata/templates/filebeat.yml.tmpl, e2e/_suites/kubernetes-autodiscover/testdata/templates/heartbeat.yml.tmpl, e2e/_suites/kubernetes-autodiscover/testdata/templates/metricbeat.yml.tmpl
Since https://github.com/elastic/beats/pull/28927, Beats file output appends a suffix to all files, that can be also rotated.
This PR makes the following changes to address this issue:
* Tries to get files with the suffix if they don't exist without it.
* Configures rotation to try to avoid it.
To fix autodiscover tests.
- Follow up of https://github.com/elastic/beats/pull/28927.
=> Get output files when they have a suffix

.stack-version
Bump stack version with the latest one. 
[start_time:Tue, 30 Nov 2021 17:22:06 GMT, release_branch:7.15, prefix:, end_time:Tue, 30 Nov 2021 23:20:38 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-ac0a2edb, build_duration_seconds:21512]
=> [automation] update elastic stack version for testing 7.15.3-ac0a2edb

e2e/_suites/fleet/fleet.go, internal/kibana/integrations.go
It does two things: 
1. changes log.Fatal to log.Error on failures when adding an integration to a policy
1. adds a retry with maxTimeout option to the addIntegrationToPolicy method, so that we are covered on errors in the staging environment of the package-registry
```
[2021-12-16T05:41:55.069Z] FATA[2021-12-16T05:41:53Z] Unable to add integration to policy           err="could not add package to policy; API status code = 500; response body = {\"statusCode\":500,\"error\":\"Internal Server Error\",\"message\":\"'502 Bad Gateway' error response from package registry at https://epr-staging.elastic.co/package/endpoint/1.4.0\"}" packageDS="{ endpoint-50fff084-9495-4633-b1a7-0a817b61d6bc Endpoint Security default cdd3d370-5e32-11ec-9ece-534be1f506d0 true  [] { endpoint Endpoint Security …
```
=> fix: add resiliency when an integration cannot be added to a policy

.ci/Jenkinsfile
Use the APM specific endpoint rather than the one provided by the Jenkins OpenTelemetry plugin.
The Jenkins OTEL plugin uses the OpenTelemetry Collector, therefore it's OTEL specific, while in the past it was APM Server (which allows dual protocols: elastic apm specific and otel). 
Let's fallback to the APM specific approach.
- If the instrumentation should be elastic specific or otel?
=> ci: use withAPMEnv

.backportrc.json, .ci/jobs/e2e-testing-fleet-daily-mbp.yml, .ci/jobs/e2e-testing-helm-daily-mbp.yml, .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml, .ci/jobs/e2e-testing-mbp.yml, .mergify.yml
This PR is retiring 7.15 branch from any service, adding 7.17 as a replacement: Jenkins pipelines (JJBB), mergify and backport (manual).
7.17 is live!
- Relates #1916
=> chore: retire 7.15 adding 7.17

.ci/Jenkinsfile
It adds a retry-wih-sleep when executing the installation of the Ansible roles to provision the stack (docker, kubectl...)
We have seen certain instability accessing the network recently, and we hope to mitigate those issues with the retry strategy.
=> chore: add resiliency when provisioning the stack

.ci/Jenkinsfile, internal/common/defaults.go
It bumps the stale agent for main to 7.17, which is current version -1
Use an existing version to upgrade
- Relates #2012
=> chore: bump stale agent for main

.ci/.e2e-tests-for-elastic-agent.yaml, .ci/.e2e-tests.yaml, .ci/Jenkinsfile, .ci/ansible/playbook.yml, .ci/ansible/tasks/copy_test_files.yml, .ci/ansible/tasks/install_deps.yml, .ci/ansible/tasks/runners.yml, .ci/ansible/tasks/setup_test_script.yml
This is an automatic backport of pull request #2007 done by [Mergify](https://mergify.com).
---
<details>
<summary>Mergify commands and options</summary>
<br />
More conditions and actions can be found in the [documentation](https://docs.mergify.com/).
You can also trigger Mergify actions by commenting on this pull request:
- `@Mergifyio refresh` will re-evaluate the rules
- `@Mergifyio rebase` will rebase this PR on its base branch
- `@Mergifyio update` will merge the base branch into this PR
- `@Mergifyio backport <destination>` will backport this PR on `<destination>` branch
Additionally, on Mergify [dashboard](https://dashboard.mergify.com/) you can:
- look at your merge queues
- generate the Mergify configuration with the config editor.
Finally, you can contact us on …
=> [7.17](backport #2007) SLES15 enablement

.ci/Jenkinsfile, .ci/README.md, .ci/ansible/github-ssh-keys, .ci/ansible/playbook.yml, .ci/ansible/tasks/install_deps.yml, .ci/ansible/tasks/install_ssh_keys.yml, .ci/ansible/tasks/runners.yml, .ci/aws-instances-reaper.groovy, .ci/jobs/aws-instances-reaper.yml, .ci/scripts/import-ssh-keys.sh, e2e/TROUBLESHOOTING.md
- chore: install ssh-import-id from pip
- feat: do not destroy cloud resources if DEVELOPER_MODE is true
- feat: install public SSH keys into the cloud instances
- chore: enable @mdelapenya in SSH access
- chore: mark EC2 instances with a proper label to be reaped
- feat: add a pipeline that removes AWS cloud resources on Sundays
This PR does a few things:
- it enables DEVELOPER_MODE as a Jenkins parameter: if checked, cloud instances won't be destroyed and a log will be shown
- it adds a file where developers interested in SSH'ing into the cloud instances shuold place their Github usernames, so that we are able to get their public SSH keys from Github using `ssh-import-id` (see https://github.com/dustinkirkland/ssh-import-id)
- it adds a shell script to execute the previous tool: the …
=> feat: enable SSH access to users for debugging cloud instances

.ci/ansible/playbook.yml
It separates the configuration of the files and the start of the stack into two Ansible task
We are seeing the following error:
CI Build: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/PR-2043/1/pipeline/
>[2022-01-19T05:28:42.603Z] fatal: [18.221.0.131]: FAILED! => {"changed": true, "cmd": "sed -i '' -e 's,http://elasticsearch,http://18.221.0.131,g' /home/admin/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml\nsed -i '' -e 's,http://fleet-server,http://18.221.0.131,g' /home/admin/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml\nsed -i '' -e 's,http://package-registry:8080,https://epr-staging.elastic.co,g' /home/admin/e2e-testing/cli/config/compose/profiles/fleet/default/kibana.config.yml\nsudo …
=> chore: split stack configuration and start into two tasks

.ci/Jenkinsfile, .ci/ansible/github-ssh-keys, .ci/ansible/playbook.yml, .ci/ansible/tasks/install_deps.yml, .ci/ansible/tasks/install_ssh_keys.yml, .ci/ansible/tasks/runners.yml, .ci/aws-instances-reaper.groovy, .ci/jobs/aws-instances-reaper.yml, .ci/scripts/import-ssh-keys.sh, e2e/TROUBLESHOOTING.md
Backports the following commits to 7.16:
- feat: enable SSH access to users for debugging cloud instances (#2001)
=> feat: enable SSH access to users for debugging cloud instances (#2001) backport for 7.16

.ci/ansible/playbook.yml
Instead of sed, it uses Ansible's built-in command for replacing strings in Kibana config file
We are seeing sed errors in Ansible execution
- Completes #2044
=> chore: use Ansible's built-in replace instead of sed

.ci/aws-instances-reaper.groovy
It passes the AWS region in which the e2e testing is creating VMs, so that the CLI is able to connect and remove the zombie instances.
We'd like to remove running instances in a weekly basis, but we saw this error:
```
[2022-01-25T10:15:12.001Z] + aws ec2 describe-instances --filters Name=tag:ReaperMark,Values=e2e-testing-vm --query Reservations[].Instances[].InstanceId --output text
[2022-01-25T10:15:12.945Z]
[2022-01-25T10:15:12.945Z] You must specify a region. You can also configure your region by running "aws configure".
[2022-01-25T10:15:12.945Z] + aws ec2 terminate-instances --instance-ids
[2022-01-25T10:15:13.895Z]
[2022-01-25T10:15:13.895Z] You must specify a region. You can also configure your region by running "aws configure".
script returned exit code 253
```
=> fix: set default region for AWS cli

.ci/Jenkinsfile, .ci/ansible/ansible.cfg, .ci/ansible/tasks/wait_for_ssh.yml
It seems that for CentOS machines, SSH takes more than 1min to come
It doubles the timeout period when waiting for SSH to come after the AWS instance has been created, from 60 seconds to 120
We have noticed that it takes more than 1 minute only for CentOS, and I've double checked that SSH is enabled for the AMI used for CentOS, launching it from AWS console manually
```
[2022-01-28T05:09:35.845Z] TASK [Wait for SSH to come up] *************************************************
[2022-01-28T05:10:43.578Z] failed: [localhost] (item={'id': 'i-0c532060aaefd5c30', 'ami_launch_index': '0', 'private_ip': '172.31.13.135', 'private_dns_name': 'ip-172-31-13-135.us-east-2.compute.internal', 'public_ip': '3.145.48.242', 'dns_name': 'ec2-3-145-48-242.us-east-2.compute.amazonaws.com', 'public_dns_name': …
```
=> chore: double wait time for SSH

.ci/ansible/playbook.yml, .ci/ansible/tasks/install_deps.yml
This PR makes a wider evaluation of variables to decide when to update APT's cache: instead of simply checking for Ansible Distribution == Debian, we are checking that the package manager is APT or the distribution is Debian OR Ubuntu
We noticed that there were situations in which the AWS machine failed to receive the Docker role because of this failure:
```
[2022-02-08T08:49:41.951Z] TASK [geerlingguy.docker : Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems).] ***
[2022-02-08T08:49:42.901Z] fatal: [3.14.83.35]: FAILED! => {"changed": false, "msg": "No package matching 'gnupg2' is available"}
```
There is a closed issue in the Ansible role for that: https://github.com/geerlingguy/ansible-role-docker/issues/263
- Relates …
=> fix: update APT cache for both Debian and Ubuntu

cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
The backport updated the version to 8.1, which is incorrect
Uses 7.16 version for fleet-server
The current value was added by a backport, so it's wrong
- Caused by #2103
=> fix: use valid version for fleet-server-7.16

.ci/ansible/playbook.yml, e2e/_suites/fleet/fleet.go, internal/kibana/policies.go
From the Ansible deployment standpoint, it bumps Go version to 7.17
It was added as part of a backport, that's why we are adding it here
=> chore: bump Go version

cli/config/compose/profiles/fleet/default/kibana.config.yml, cli/config/compose/profiles/fleet/preconfigured-policies/kibana.config.yml, e2e/_suites/fleet/fleet.go, internal/kibana/policies.go
This reverts commit 9b00e4115e146f4b676bc99c346febf1b86d7cba.
@ph mentioned that the pre-configured policies for fleet-server should be available only for 8.1, not 8.0
- Reverts #2116
=> Revert "[8.0](backport #2111) chore: use preconfigured policy for fleet-server's default policy (#2116)"

.ci/Jenkinsfile
To help with troubleshooting, let's relax the log rotation a bit so, consumers can access those logs if needed
=> ci: increase log rotation

.ci/Jenkinsfile
It updates the build timeout from 60 mins to 90.
With the move to VMs, we are very close now to the 60 mins max build time. Increasing it to 90, although not desired as a long term solution, could help as to not let certain builds fail.
=> chore: increase build timeout to 90 minutes

e2e/_suites/kubernetes-autodiscover/testdata/templates/elastic-agent.yml.tmpl
Tests for `elastic-agent` were failing because of:
```
(23) Failed writing body
/etc/writer.sh: 12: jq: not found
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 13884  100 13884    0     0  1129k      0 --:--:-- --:--:-- --:--:-- 1129k
curl: (23) Failed writing body (0 != 13884)
```
Closes https://github.com/elastic/e2e-testing/issues/1992
=> Install jq tool in elastic-agent container to parse ES output

.ci/jobs/e2e-testing-fleet-daily-mbp.yml, .ci/jobs/e2e-testing-helm-daily-mbp.yml, .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml, .ci/jobs/e2e-testing-mbp.yml
`7.16` is not an active branch.
`8.1` is an active branch.
Otherwise consumers cannot test the e2e
Notifies https://github.com/elastic/beats/pull/30404
=> jjbb: enable 8.1 and disable 7.16

.ci/Jenkinsfile
It separates the single, current shell script execution for provisioning the stack VM in three parts:
1. check if virtualenv is created if the `.venv-installed` file is not present, create virtualenv and create the file
1. install Python and Ansible dependencies if the `python-dependencies` file is not present, install them and create the file
1. execute the command passed to `pyrun`
We have added a retry logic for the first two scripts, so that we can control and locate possible network issues for each part of the provisioning code
Decouple provisioning from execution
As @adam-stokes mentioned, having a cache/mirror for the Ansible dependencies could improve the resiliency
=> chore: decouple ansible install from execution

.ci/Jenkinsfile
Backports the following commits to 7.17:
- chore: increase build timeout to 90 minutes (#2139)
- ci: increase log rotation (#2138)
=> chore: increase build timeout to 90 minutes (#2139) backport for 7.17

.ci/Jenkinsfile
Backports the following commits to 8.0:
- chore: increase build timeout to 90 minutes (#2139)
- ci: increase log rotation (#2138)
=> chore: increase build timeout to 90 minutes (#2139) backport for 8.0

.ci/Jenkinsfile
I wanna explore if a smaller CI workers for the existing parallel stages work as expected since the heavy-lift is done in the remote workers instead.
From `n1-highmem-8` to `e2-small`
Cheaper builds.
=> ci: provision e2-small workers

README.md
Wrong link in markdown
Caused by #2213
=> fix: wrong link

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go, e2e/_suites/kubernetes-autodiscover/features/elastic_agent_standalone.feature, e2e/_suites/kubernetes-autodiscover/testdata/templates/elastic-agent.yml.tmpl, e2e/_suites/kubernetes-autodiscover/testdata/templates/elasticsearch.yml.tmpl
Separate ES workload from Agent spec and make it a requirement for the scenarios so as to ensure that deadlines because of download time are not hidden inside the scenario execution.
=> Separate ES workload from Agent spec and make it req for the scenarios

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
It excludes elasticsearch CI artifacts from being processed when a PR from beats/elastic-agent triggers the e2e tests.
We detected that PRs from Beats/Elastic-Agent triggering the e2e AND running the kubernetes-autodiscover test suite, which is the only one affected by this regression.
- Caused by #2203
=> fix: never process elasticsearch CI artifacts

.ci/e2eTestingFleetDaily.groovy, .ci/e2eTestingHelmDaily.groovy, .ci/e2eTestingK8SAutodiscoveryDaily.groovy
It increases the build timeout of the scheduled, nightlky builds to 90 min
Although the pipeline helper times out at 90 min, the trigger build (the nightly) is using 1h, so it dies before expected.
- Completes #2139
=> fix: increase scheduled build timeouts to 90 min

.ci/Jenkinsfile
It refactors the way we are sending slack notifications, which was using a Jenkins argument to control it. If the pipeline received a `false` value in the `notifyOnGreenBuilds` parameter, it was directly used.
With this change, we are always forcing a Slack notification, but if the build is successful, then delegate the notification to the parameter.
- a build is successful and the parameter is true -> send slack
- a build is successful and the parameter is false -> do not send slack
- a build is failed and the parameter is true or false -> send to slack
We noticed that recent failures were not posted to the elastic-agent channel. Hopefully this will bring them back to work
=> fix: send slack notifications for failed builds

e2e/TROUBLESHOOTING.md
Add link to users used to SSH into the Cloud EC2s to e2e/TROUBLESHOOTING.md
To know which user to use
- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have run the Unit tests (`make unit-test`), and they are passing locally~~
- ~~[ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally~~
=> Add link to the users used to SSH into the Cloud EC2s

.ci/Jenkinsfile, .ci/ansible/playbook.yml, .ci/ansible/tasks/runners.yml, .ci/aws-instances-reaper.groovy
Standardise the below tags/labels in the terraform resources for AWS/GCP:
- `environment` => static value
- `repo`.              => static value
- `branch`           => dynamic value
- `build`              => dynamic value 
- `created_date` => dynamic value
Help with tearing down any of the ephemeral resources which were not successfully removed as part of the system tests.
* Those tag/labels are lowercase based to be [GCP](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements)/[AWS](https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html#tag-conventions) compliance
* `environment=ci` will allow to filter all those cloud resources which were created in the CI
* While `created_date` will help to filter those which were older than X days or X hours, …
=> Add metadata tags

.ci/Jenkinsfile
Rename special chars
Avoid issues with some special chars if the provider is Google
See https://github.com/elastic/elastic-package/pull/799
=> ci: transform branch to allow the Google Labels naming

cli/config/compose/profiles/fleet/docker-compose.yml, e2e/templates/profile.yml.tmpl
It uses an empty string (`"0.0.0.0"`) instead of the null value for `network.host` in the elasticsearch confioguration.
We detected that 8.3-SNAPSHOT is not able to start because of that:
```java
Exception in thread "main" org.elasticsearch.ElasticsearchParseException: null-valued setting found for key [network.host] found at line number [5], column number [14]
at org.elasticsearch.common.settings.Settings.validateValue(Settings.java:767)
at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:743)
at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:687)
at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1189)
at org.elasticsearch.node.InternalSettingsPreparer.loadOverrides(InternalSettingsPreparer.java:143)
at …
```
=> fix: use "0.0.0.0" string instead of null for ES' network.host

internal/common/defaults.go
Keep backward compatibility to query the artifacts-api if a version is an alias
Cornercase when bumping the patch version, since the artifacts-api is not yet available. So the alias detection should not be needed if no passing an alias.
Closes https://github.com/elastic/e2e-testing/issues/2500
=> avoid aliases if no major.minor format

.ci/schedule-daily.groovy, internal/common/defaults.go
Aliases for releases are defined in the apm-pipeline-library, those versions are automatically bumped, but the apm-pipeline-library releases are not based on CD but manually released.
So by using the main then versions will be the correct one
Closes https://github.com/elastic/e2e-testing/issues/2515
=> ci: daily pipeline to use main branch

internal/deploy/base.go, internal/installer/base.go, internal/installer/elasticagent_deb.go, internal/installer/elasticagent_docker.go, internal/installer/elasticagent_rpm.go, internal/installer/elasticagent_tar.go, internal/installer/elasticagent_tar_macos.go, internal/installer/elasticagent_zip.go
- chore: store agent pat into the metadata struct of the agent package
- chore: create agent directories for UNIX-based agent installers
It adds a new field in the struct representing the agent metadata to store the base path where the agent will be installed under Linux/Darwin systems.
This path will be created in the target system at the PreInstall phase, so that it has the right permissions beforehand.
This agent path, according to https://github.com/elastic/elastic-agent/pull/398, must belong to `root`. And this applies only to 8.3 and main.
- Consequence of https://github.com/elastic/elastic-agent/pull/398
- Discovered while testing #2585 and #2586
=> fix: agent directories must belong to root

e2e/_suites/fleet/features/upgrade_agent.feature
It retires 8.1-SNAPSHOT from the stale versions used to upgrade an agent in the main branch. Instead of using that snapshot, we are using the latest released version for 8.1, which is 8.1.3
The 8.1-SNAPSHOT dissapeared from the Elastic artifacts.
- Relates #2615
=> fix: retire 8.1 snapshot from upgrades

.ci/e2eTestingMacosDaily.groovy
Add Mac OS 12 as part of the tested Operating system
Originally requested https://github.com/elastic/e2e-testing/pull/2336 but closed since the implementation was change to use Orka ephemeral workers in https://github.com/elastic/e2e-testing/pull/2626
This [build](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-macos-daily-mbp/detail/PR-2684/2/pipeline)
=> ci: support MacOS12

pkg/downloads/releases.go
Hello from the elastic-agent team. I recently had an issue with `FetchElasticArtifact` where it tired to fetch an artifact that didn't exist, and rather than erroring out, it threw a really difficult to trace typecast panic. This appears to be an issue with how the API itself behaves when you ask for a non-existent package:
```
curl https://artifacts-api.elastic.co/v1/search/8.4.0-SNAPSHOT/elastic-agent-shipper\?x-elastic-no-kpi\=true
{"packages":[],"manifests":{"last-update-time":"Thu, 23 Jun 2022 17:38:20 UTC","seconds-since-last-update":134}}
```
We don't get an error, just an empty list. When we try to cast to string, we get an error. Not sure if there's a better way to do this, but I figured it would be at least nice to have.
This produces a very difficult to debug error. …
=> Add error checks to string typecast

.ci/e2eTestingMacosDaily.groovy
Notify if test failures to the `elastic-agent` team so they can track any MacOS test failures easily.
As requested by the team
=> ci: notify test failures for MacOS nightly builds

pkg/downloads/releases.go, pkg/downloads/versions.go
Previously, the returned values from NewArtifactURLResolver could be a
nil *ArtifactURLResolver. This was incorrectly being compared to nil in
the context of a DownloadURLResolver in getDownloadURLFromResolvers and
so being ignored, finally resulting in a nil pointer dereference when
the Resolve method was called. The change here makes the nil returned by
NewArtifactURLResolver be a nil DownloadURLResolver which will be
recognised in getDownloadURLFromResolvers and so not used.
This fixes an incorrect use of a nil in an interface context (equivalent to https://go.dev/doc/faq#nil_error).
The existing code can panic in tests.
```
[2022-06-29T08:13:17.490Z]   Scenario Outline: Deploying the Elastic-Agent with enroll and then run on top of metricbeat # …
```
=> pkg/downloads: make sure nil resolvers are interpretted correctly

.ci/Jenkinsfile
Don't take for granted the data structure is in a good shape.
There are some errors with null values.
The `Deploy Test Infra` stage printed some information:
=> ci: fix null for shell_type by throwing an error

.ci/Jenkinsfile, internal/common/defaults.go, pkg/downloads/versions.go
- fix: pass Git variables in Jenkinsfile
- fix: laxy initialisation of the Git variables
It passes the GITHUB_CHECK_SHA1 and GITHUB_CHECK_REPO variables to the Jenkinsfile, so that the Ansible code is able to pass them to the generated `.env` file in the remote machine.
This `.env` file is driving the execution, for that reason it's important it contains the right variables and values.
Besides that, we detected that the initialisation of those two variables was happening too early, before the `.env` was loaded (it was placed in the init() method, which has no deterministic order). Therefore, we are moving it to the initialisation of the default variables.
PRs from Beats, and eventually for the elastic-agent are not downloading the right artifacts, generated for the respective CIs when the …
=> fix: read Git variables

.ci/.e2e-tests-beats.yaml, .ci/Jenkinsfile
Fix the extra space in the configuration file
Force trim to avoid future issues
Fix a broken configuration
Backport is not required since the original PR was not backported -> https://github.com/elastic/e2e-testing/pull/2603
=> fix space in the configuration file 

.ci/ansible/tasks/runners.yml, internal/kibana/agents.go
- chore: log desired version on upgrade error
- fix: increase instance size to 15Gb
It increases the default AWS instance size from 10Gb to 15Gb
Besides, we are adding the desired version of an upgrade when logging an error
Ubuntu instances are hitting "no space left on device" error during tests
```
export NODE_LABEL=ubuntu_22_04_amd64
make -C .ci provision-node
make -C .ci ssh-node
```
Running a `df -h` command should show a size of 15Gb:
```
root@ip-172-31-43-67:~# df -h
Filesystem       Size  Used Avail Use% Mounted on
/dev/root        15G     1G   14G  10% /
tmpfs            7.8G     0  7.8G   0% /dev/shm
tmpfs            3.1G  876K  3.1G   1% /run
tmpfs            5.0M     0  5.0M   0% /run/lock
/dev/nvme0n1p15  105M  5.3M  100M   5% /boot/efi
tmpfs            1.6G  4.0K  1.6G   1% …
```
=> fix: increase instance size to 15Gb

.ci/.e2e-tests-beats.yaml, .ci/.e2e-tests-daily.yaml, .ci/.e2e-tests-for-elastic-agent.yaml, .ci/.e2e-tests.yaml, e2e/QUICKSTART.md, e2e/_suites/fleet/features/manage_integrations.feature
- chore: simplify CI matrix for integrations
- chore: rename feature file
This PR is removing all OSs platforms but one for the execution of the integrations.feature file in the CI.
Finally, we are giving a proper name to the feature file, to describe its real intention.
Because the scenarios in this feature file do not install the agent at all, we do not need to test it in multiple platforms: they simply verify that it's possible to add integrations to policies.
The tests will simply hit the Kibana APIs to add integrations to the policy using authenticated HTTP requests, and for that the underlying OSs is irrelevant. I kept Debian 11 AMD as the base image, but it could be any other else.
This change will decrease the number of CI workers and AWS instances created by each build:
- for …
=> chore: simplify CI matrix for managing integrations in policies

.backportrc.json, .mergify.yml
Merge as soon as 8.4 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
=> backport: Add 8.4 branch

e2e/_suites/fleet/api_keys.go
It adds a retry-with-backoff strategy when checking whether an API key changed or not
Before this change, the comparison was immediate, and because we are observing certain flakiness in the CI, we could identify a pattern: the tests run too fast and the change/no-change of the API key happens in the background asynchronously, that's why we are polling the resource for the default TimeOutFactor in minutes (3-5-7)
=> fix: poll for api key verification using backoff retry

.ci/.e2e-tests-daily.yaml, .ci/.e2e-tests-for-elastic-agent.yaml, .ci/.e2e-tests.yaml, .ci/ansible/playbook.yml, .ci/ansible/tasks/install_deps.yml, e2e/_suites/fleet/elastic_agent_deploy.go, e2e/_suites/fleet/elastic_agent_enroll.go, e2e/_suites/fleet/features/stand_alone_mode.feature, e2e/_suites/fleet/stand-alone.go
- chore: apply functional opts to agent deployment
- chore: rename deployment method
- chore: simplify stand-alone deployment removing flavour
- fix: revoke token scenario was outdated
- chore: simplify deploy stand-alone agent method
- chore: skip scenario for bootstrap fleet server agent in stand-alone
- chore: include stand-alone agent in CI
It adds the stand-alone agent scenarios to the CI including a few changes:
- the bootstrap fleet-server scenario is skipped, because it uses docker-compose to start the fleet-server in local, and the agent is using the already deployed stack
- uses a new functional approach (more Go idiomatic) when deploying an agent to Fleet. It uses optional functions instead of input parameters to configure the deployment (installer type, extra flags, etc)
- …
=> chore: bring back stand-alone agent

.ci/schedule-daily.groovy
Enable daily builds for certain scenarios targeting https://github.com/elastic/e2e-testing/tree/feature-arch-v2
If `feature-arch-v2` is not using the same functionality defined in `main`, both `e2e-testing` or the consumers (`beats`, `elastic-agent`
Otherwise, we don't need this feature
Requires https://github.com/elastic/e2e-testing/pull/2976
=> ci: schedule builds for the feature-arch-v2 branch

.github/workflows/sync-branches.yml
Use https://github.com/aormsby/Fork-Sync-With-Upstream-action to sync `feature-arch-v2` with the latest changes in main
Since `feature-arch-v2` and `main` are functional equivalent this automation will help to keep those branches in sync.
This particular action has been used at Elastic in some other repositories
=> action: Sync main with feature-arch-v2

.ci/e2eTestingFleetDaily.groovy, .ci/e2eTestingMacosDaily.groovy
Move away from elastic-agent slack channel and use the dedicated ingest-notifications one.
=> Update ingest notifications channel

e2e/_suites/fleet/api_keys.go, e2e/_suites/fleet/features/permission_output_change.feature, e2e/_suites/fleet/fleet.go, e2e/_suites/fleet/fleet_test.go, internal/elasticsearch/client.go, internal/kibana/agents.go
Addes support for bulk API key change which does not update api key for output
Removes Default API key and operates on api key on output level
Keep in par with fleet server
=> Added support for bulk api update change

.ci/.e2e-tests-beats.yaml, .ci/.e2e-tests-for-elastic-agent.yaml
Replicates the changes from https://github.com/elastic/e2e-testing/pull/3054 to the other pipelines
=> Turn off all tests but Fleet mode and upgrade for Beats and Agent pipelines

internal/installer/elasticagent_tar_macos.go
Use the detected version 
While working on https://github.com/elastic/e2e-testing/actions/runs/3288874303/jobs/5419734016
I've found
```
Check files aren't using go's testing package........(no files to check)Skipped
golangci-lint............................................................Failed
- hook id: golangci-lint
- exit code: 1
WARN [runner] Can't process result by diff processor: can't prepare diff by revgrep: could not read git repo: error executing git diff HEAD~: exit status 128 
internal/installer/elasticagent_tar_macos.go:176:4: ineffectual assignment to version (ineffassign)
version = v
^
```
=> fix ineffassign for the version when using tar on MacOS

.ci/jobs/e2e-testing-helm-daily-mbp.yml, .ci/jobs/e2e-testing-mbp-tmp.yml, .ci/jobs/e2e-testing-mbp.yml, .ci/jobs/e2e-testing-pr-mbp.yml, .ci/jobs/e2e-testing-pr-merge-mbp.yml
Creates 3 separate JJBB workflows:
1. `e2e-testing-mbp.yml` - For external e2e tests executions ONLY. When another pipeline triggers the tests
2. `e2e-testing-pr-mbp.yml` - For pull requests to this repo ONLY
3. `e2e-testing-pr-merge-mbp.yml` - For PR merges to `main` ,`8.x` or `7.17`
Single Jenkinsfile for all operations is overcomplicated
- Relates https://github.com/elastic/e2e-testing/pull/3169
=> CI: separate JJBB definitions for pull requests, PR merge and external e2e calls

e2e/TROUBLESHOOTING.md
Fixes https://github.com/elastic/e2e-testing/issues/3256
Shares some troubleshooting guide to resolve the errors encountered while provisioning aws VMs using CI jobs.
=> Fix: PR 3256 Set up nodes error is encountered while provisioning aws VMs using CI jobs.

.editorconfig
It add a [editconfig]() configuration to allow IDEs to follow the same format rules.
closes https://github.com/elastic/e2e-testing/issues/1794
=> feat: add edit config configuration file

e2e/_suites/fleet/features/fleet_mode.feature
revert https://github.com/elastic/e2e-testing/pull/1017
closes https://github.com/elastic/e2e-testing/issues/1022
=> fix: enable agent status check

e2e/_suites/fleet/features/upgrade_agent.feature, e2e/_suites/fleet/upgrades.go
The timeout for the upgrades is too tight. Increasing the global TimeoutFactor does not seem appropriate, so I have added a new constant in the upgrades.go file to manage the updates timeout.
=> fix: increase upgrades timeout

.ci/ansible/tasks/setup_test_script_windows.yml
=> fix: typo in the ansible playbook

.ci/bump-elastic-stack-snapshot.yml
Fix wrong replacement in the updatecli
Otherwise it adds ` = = value`
=> updatecli: fix pattern for updating the defaults.go

.mergify.yml
auto-merge bump automations using updatecli
## Why
Branch changed when enabled `updatecli`.
=> mergify: support for updatecli automation

e2e/_suites/kubernetes-autodiscover/testdata/templates/elastic-agent.yml.tmpl, e2e/_suites/kubernetes-autodiscover/testdata/templates/filebeat.yml.tmpl, e2e/_suites/kubernetes-autodiscover/testdata/templates/heartbeat.yml.tmpl, e2e/_suites/kubernetes-autodiscover/testdata/templates/metricbeat.yml.tmpl
Bug fix for the failing E2E tests that was found here: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/main/3080/pipeline
This PR updates the beats (filebeat, metricbeat, hearbeat) templates and agent templates of e2e test framework used in Autodiscovery scenarios. 
The mentioned templates did not have all the needed Clusteroles in order to allow monitoring of resources
It affects all the CI pipelines where we trigger the E2E tests with autodiscovery
1.Download the e2e framework
1.Navigate to `e2e/_suites/kubernetes-autodiscover`
Run the following
```bash
export BEAT_VERSION=8.9.0-SNAPSHOT                                                  
export GITHUB_CHECK_SHA1="22382ca036edce9827672013a0870df6f8583724"
export KIND_VERSION=“0.17.0”
export …
```
=> Updating beats Clusteroles to allow job,daemonset discovery

.github/workflows/k8s-autodiscovery-test.yml
Sets the matrix strategy `fail-fast` to `false`, so that the workflow still continues in case of an error.
=> Set fail-fast to false for k8s-autodiscovery-test

internal/utils/utils.go, pkg/downloads/releases.go, pkg/downloads/releases_test.go, pkg/downloads/versions.go
This PR fixes several bugs and makes it possible to download artifacts from the project specific staging areas that feed into the unified release process. This is necessary in the time between a feature freeze and the first snapshot being produced, which historically has been several days.
Examples of project specific URLs are:
* https://artifacts-snapshot.elastic.co/beats/latest/8.11.0-SNAPSHOT.json
* https://artifacts-snapshot.elastic.co/endpoint-dev/latest/8.11.0-SNAPSHOT.json
* https://artifacts-snapshot.elastic.co/fleet-server/latest/8.11.0-SNAPSHOT.json
* https://artifacts-snapshot.elastic.co/prodfiler/latest/8.11.0-SNAPSHOT.json
This also makes the following changes:
* Adds mutexes to shared caches to allow downloads to happen in parallel safely.
* Remove use of the curl package in …
=> Allow downloading artifacts from project specific locations

e2e/_suites/kubernetes-autodiscover/testdata/templates/a-short-living-cronjob.yml.tmpl
-- Bug
This PR updates the Cronjob template used for k8s autodiscovery especially in version 7.17
From https://github.com/elastic/e2e-testing/actions/runs/6138671269/job/16655778644#step:6:175 we can see that
```yaml
Run actions/checkout@v3
with:
ref: 7.17
repository: elastic/e[2](https://github.com/elastic/e2e-testing/actions/runs/6138671269/job/16655778644#step:2:2)e-testing
```
So github actions refers to 7.17 e2e testing framework. The kubernetes version is 1.26 and in this version the `batch/beatv1` api is no longer available (see more info [batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+](https://github.com/linkerd/linkerd2/issues/7852)) 
Fixes https://github.com/elastic/e2e-testing/issues/3642
- Closes  https://github.com/elastic/e2e-testing/issues/3642
=> Updating cronjon template for Elastic agent v7.17

.ci/bump-elastic-stack-snapshot.yml, .github/workflows/bump-elastic-stack-snapshot.yml
Avoid sending slack messages if any failure
Robots don't own this project and it's not in active development these days
-
=> updatecli: skip slack notifications

.github/workflows/opentelemetry.yml
=> github-action: opentelemetry use wildcards

.github/workflows/golangci-lint.yml, .github/workflows/pre-commit.yml, .github/workflows/pull-request.yml, .pre-commit-config.yaml
Remove support for golint -> it's frozen since 2021
Bump github action dependencies
Use .go-version
Remove support for golanglint on Windows -> there are some failures
Fix the build system
=> github-actions: bump versions, remove obsoleted tools and remove support for Windows linting

pkg/downloads/releases.go, pkg/downloads/versions.go
When downloading files, consider any HTTP response codes > 399, not just 404 response codes, as errors.
To be more resilient to HTTP failures.
=> Consider any HTTP response code > 399 as an error

pkg/downloads/releases.go, pkg/downloads/versions.go
The only expected code is 200, the rest should fail and the error message should contain the status code itself.
This is a follow up to https://github.com/elastic/e2e-testing/pull/3834
=> Report unexpected status codes as errors
