.ci/Jenkinsfile
.ci/scripts/functional-test.sh
.vscode/launch.json
Makefile

Enable feature selector on test scripts

---

.ci/Jenkinsfile
.ci/scripts/install-dependencies.sh

- See https://github.com/alecthomas/gometalinter/issues/521

fix: gometalinter got issues with go modules

---

README.md

chore: add build status in the README.md

---

.ci/functionalTests.groovy
metricbeat-tests/README.md

It documents the execution of Godog tests using Make
It adds clarity about the usage of the tool

Update docs on how to run the tests

---

e2e/Makefile
e2e/README.md
e2e/go.mod
e2e/go.sum
e2e/metricbeat-poc.md
e2e/metricbeat_test.go
e2e/runner_test.go

Uses the official repository for Godog, which has been adopted by Cucumber organisation
Housekeeping!

chore: Use official cucumber dependency for Godog

---

.ci/jobs/e2e-testing-beats.yml
.ci/jobs/e2e-testing-helm-daily.yml
.ci/jobs/e2e-testing-ingest-manager-daily.yml
.ci/jobs/e2e-testing-mbp.yml

Use proper folder name for the jobs

fix: use proper folder names

---

.ci/e2eTestingHelmDaily.groovy
.ci/e2eTestingIngestManagerDaily.groovy
.ci/jobs/e2e-testing-mbp.yml
README.md

It fixes the buildd that has to be triggered on scheduled jobs
Remove left-overs
- Relates #155

fix: trigger proper job on daily scheduled builds

---

.pre-commit-config.yaml
e2e/NOTICE.txt
e2e/go.sum

It updates the NOTICE.txt file after using the patched version of the go-license-detector.
We want to represent the local dependency in the NOTICE file
~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have run the Unit tests for the CLI, and they are passing locally~~
~~- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally~~
- See https://github.com/elastic/go-licence-detector/pull/13

chore: run notice with patched go-license-detector

---

.ci/Jenkinsfile
.ci/scripts/functional-test.sh
.ci/scripts/install-helm-test-dependencies.sh
.ci/scripts/install-metricbeat-test-dependencies.sh
.ci/scripts/install-test-dependencies.sh

When installing the test dependencies, it checks for the existence of a specialised script for installing the dependencies for the current test suite, identified by the $SUITE variable. This variable will be set on CI.
It will reduce the build time in those parallel branches that don't need to install some test deps.
- Closes #170

feat: install test dependencies for each test suite

---

.github/paths-labeller.yml

It uses botelastic's inrastructure to add automatically add labels when certain paths are modified.
It will help in the triage of PRs
~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have run the Unit tests for the CLI, and they are passing locally~~
~~- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally~~
~~- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)~~
- Closes 196

chore: automate GH labels for PRs based on modified paths

---

README.md
e2e/README.md
e2e/_suites/helm/README.md
e2e/_suites/ingest-manager/README.md
e2e/_suites/metricbeat/README.md
e2e/_suites/metricbeat/metricbeat-poc.md

This PR is simplifies the existing docs, creating a main README file per test suite, moving some of the sections to other docs, and removing others because they are outdated or even present in a more up-to-date doc.
~~Finally, we added the CI badges for the scheduled pipeline for each test suite~~~ Edited: See https://github.com/elastic/e2e-testing/pull/191#discussion_r459612392 
CCC: Clearness, Conciseness and Concreteness
We are also preparing the project for transferring it to the functional teams
~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have added tests that prove my fix is effective or that my …

docs: enhance documentation

---

e2e/_suites/helm/README.md
e2e/_suites/ingest-manager/README.md
e2e/_suites/metricbeat/README.md

It removes Travis' gimme from docs, linking to Golang's official site ffor installation instructions.
Remove old docs
~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have run the Unit tests for the CLI, and they are passing locally~~
~~- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally~~
~~- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)~~
- Relates #185

docs: remove gimme from docs

---

e2e/NOTICE.txt
e2e/README.md
e2e/_suites/helm/README.md
e2e/_suites/ingest-manager/README.md
e2e/_suites/metricbeat/README.md
e2e/go.sum

We are explicitly adding Docker configurations that are needed on Mac, plus some minor improvements in the existing docs.
Improve the user experience while using this framework
- Closes #201
Paste here output logs discovered while creating this PR, such as stack traces or integration logs, or any other output you consider important to be shared with the team.
-->
Add here any thought that you consider could be identified as an actionable step once this PR is merged.
-->

docs: enhance documents about docker errors

---

e2e/_suites/ingest-manager/README.md

It includes an example of a tag used for the binaries for a PR
Docs, docs, docs
- Relates #204

docs: be more explicit about PRs in snapshots

---

.ci/Jenkinsfile

It checks changesets with modified markdown files, only. If so, it will skip any test stage
Speed up the build, and removing potential errors for PRs or merges affecting just documentation
- Closes #210

feat(ci): skip test stages for changes in markdown files, only

---

.ci/Jenkinsfile
.ci/e2eTestingHelmDaily.groovy
.ci/e2eTestingIngestManagerDaily.groovy
.ci/e2eTestingIntegrationsDaily.groovy

This PR enables sending errors to Slack channels. We will send the errors to the `observability-robots` channel by default,
being a responsibility of the scheduled pipelines (Helm, Integrations and Ingest Manager) to configure the proper Slack channel.
We will send Helm and Integrations suite errors to the #integrations channel, and the Ingest-Manager errors to the #ingest-management one.
This behavior will affect only to merges to master, not to PRs
After discussing with @EricDavisX, we want to warn teams when a regression has appeared.
- As a developer, I want to be notified on my team's Slack channel when a failure occurs on the nightly test suite my team owns.
- As a robot, I want to be notified on my team's Slack channel (observablty-robots) when a failure occurs on merges to master.

feat: send errors for merges to Slack channels, depending on the suite

---

e2e/_suites/ingest-manager/fleet.go

It renames from configurations to policies:
- API calls and URLs
- attributes storing state (i.e. configID/policyID)
It will keep tests green, sync'ing with latest version of 8.0.0-snapshot
Simply run the ingest-manager test suite
- Closes #227
We must create maintenance branches supporting different code bases for different versions of the stack

fix: rename configuration to policy

---

e2e/_suites/ingest-manager/services.go
e2e/_suites/ingest-manager/stand-alone.go

It support overriding the version of the agent to install, using the env var mechanism that was already in place.
We noticed this version was hardcoded and we want the CI to be able to change it if needed
Run:
```shell
cd e2e/_suites/ingest-manager
ELASTIC_AGENT_VERSION=7.9.0 godog -t fleet_mode
```

fix: use agent version from the environment

---

e2e/_suites/ingest-manager/fleet.go

It doubles the time the backoff strategies are using for Fleet.
We agreed in increasing this waiting period for slow machines

chore: increase timeout for listing online agents

---

.backportrc.json

It adds backport configuration
Make it easy backports to maintenance branches
Install backport from https://github.com/sqren/backport
```shell
$ backport
```

chore: add backport configuration

---

README.md

It documents how to enable pre-commit for this repository
We want to enable the same experience working locally than running the CI
We would need to enhance the docs for contributions, maybe at the level of each test suite

docs: document pre-commit

---

cli/config/compose/profiles/ingest-manager/docker-compose.yml

It replaced the Docker images for the stack: from the observability-ci, to the official Docker registry.
Let's use released images to avoid sync issues

chore: use released versions

---

.ci/Jenkinsfile
.ci/e2eTestingIngestManagerDaily.groovy

It adds a boolean Jenkins input parameter to control if green, successfull builds must be sent to the slack channel.
To accomplish it we used a `whenTrue(!isPR() && params.notifyOnGreenBuilds)`.
Finally we enforced the value to TRUE for the scheduled job for Ingest Manager.
The team requested having the notification for green builds in their Slack channel.
- Supersedes #223, closes #223
```gherkin
Given the slack channel for Ingest Manager
When the scheduled build for the team passes
Then a Slack notification is sent to the channel
```
The rest of the use cases keep the same: only notify on red, failing builds

chore(ci): support notifying on green builds for ingest management builds

---

e2e/_suites/ingest-manager/features/fleet_mode_agent.feature
e2e/_suites/ingest-manager/fleet.go
e2e/_suites/ingest-manager/ingest-manager_test.go
e2e/_suites/ingest-manager/services.go
e2e/_suites/ingest-manager/stand-alone.go
e2e/utils.go

It converts all Scenarios into Scenarios Outline, so that it's possible to define Examples (Centos, Debian).
We had to fix some hardcoded names when getting the container name, to be able to execute commands in the proper container.
It increases coverage on different platforms
Running godog as usual will run tests for Centos and Debian
- Closes #245

feat: run fleet scenarios for both Centos and Debian

---

e2e/_suites/ingest-manager/features/fleet_mode_agent.feature

It uses the proper keyword for scenarios with multiple examples. I did not realised the lint failure becuase cucumber/godog still treats them as outline, iterating through the examples.
It fixes the gherkin lint, and follow best pratices
- Relates #246
The log error we want to fix is:
```log
/usr/local/bundle/gems/gherkin-5.0.0/lib/gherkin/parser.rb:84:in `parse': Parser errors: (Gherkin::CompositeParserException)
(10:1): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Examples:'
(20:1): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Examples:'
(31:1): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, …
```

fix: use Scenario Outline

---

.ci/Jenkinsfile

It removes the stage update when catching an error in the lint stage.
We want to avoid failing the build on false positives because of lint, mainly caused by project layout
- Relates #247
We need to backport this to 7.9.0

fix: do not update state status when catching lint errors

---

cli/config/compose/profiles/ingest-manager/docker-compose.yml

It uses the latest, valid version o fthe package registry that works with the 7.9.x branch
Keep branches in sync
```shell
rm -fr ~/.op/compose
OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true godog -t "stand_alone_mode"
```
- Relates #253

chore: use a ffixed version of package registry

---

.ci/jobs/e2e-testing-helm-daily-mbp.yml

Use proper definition for Jenkins' default script.
Otherwise Jenkins will try to locate a Jenkinsfile, which is incorrect
-

fix: use proper definition of the script path

---

.ci/jobs/e2e-testing-helm-daily-mbp.yml

It adds a JJB definition to suppress the SCM triggering
Without it, the MBP will respond to any merge commit in the repo, which in this case is not desired, as we planned a scheduled execution, only.
- Relates #263 #258

fix: suppress scm triggering for all branches

---

.ci/.e2e-tests.yaml
cli/cmd/sync.go
cli/config/config.go
cli/docker/docker.go
cli/internal/state.go
cli/services/helm.go
cli/services/manager.go
cli/shell/curl.go
cli/shell/shell.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/ingest-manager/README.md
e2e/_suites/ingest-manager/features/agent_endpoint_integration.feature
e2e/_suites/ingest-manager/features/fleet_mode_agent.feature
e2e/_suites/ingest-manager/fleet.go
e2e/_suites/ingest-manager/ingest-manager_test.go
e2e/_suites/ingest-manager/integrations.go
e2e/_suites/ingest-manager/services.go
e2e/_suites/ingest-manager/stand-alone.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/utils.go

This PR is the first part off the implementation of the Endpoint scenarios. We are going to consume existing scenarios, rephrasing some of those specific for the endpoint integration to reuse existing code.
We are enforcing the usage of systemd-based containers (Centos and Debian) which will install the elastic-agent as a Linux service.
We also commented those steps related to query the Security App, because it uses GraphQL and we do not have the proper API calls to query the data: i.e. the online hosts after applying a configuration incclcuding the endpoint integration.
Another improvement we have done is to support dev-mode, which means do not destroying runtime dependencies between test runs, so the ES, Kibana and package registry are not destroyed after the test suite runs. So we will …

feat: implement Endpoint scenarios

---

e2e/Makefile
e2e/NOTICE.txt
e2e/go.mod
e2e/go.sum

It bumps godog from 0.9.0 to 0.10.0
We want to be as close to this (https://github.com/cucumber/godog/issues/205) as possible, because we'll need the new xUnit format.

chore: bump godog to v0.10.0

---

.ci/jobs/e2e-testing-integrations-daily-mbp.yml

It renames the job name in JJB, as it was duplicated after a wrong copy&paste
It will hide other pipeline
- Relates #268 #275

fix: typo in job name

---

e2e/_suites/ingest-manager/fleet.go
e2e/_suites/ingest-manager/integrations.go

It removes the only one check for the `success` response field, which was removed here: https://github.com/elastic/kibana/pull/73223
Code will fail with panic because the used conversion was not captured
The scenario using that field is tagged with the `@endpoint-policy-check` annotation
```shell
$ cd e2e/_suites/ingest-manager
$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true godog -t "agent_endpoint_integration && endpoint-policy-check"
```
- Relates https://github.com/elastic/kibana/pull/73223

fix: "success" was removed from response

---

e2e/_suites/ingest-manager/fleet.go
e2e/_suites/ingest-manager/ingest-manager_test.go
e2e/_suites/ingest-manager/stand-alone.go

We are adding methods to create/remove a policy using existing APIs, so that each test scenario is using a separate policy.
As we have to remove the policy after each scenario, we refactored the tear down part, extracting code to methods repreenting the afterScenario life cycle hook.
We want each test to be independent from the others, supporting running test scenarios eventually in parallel.
- Closes #257 
We could enable the `--concurrency=2`, although it only supports the `progress` format. Another improvement could be running scenarios in random order (with godog's `--random` flag), so that we make sure tests don't depend on previous state.

feat: support creating (and removing) a policy for each scenario

---

cli/config/compose/profiles/ingest-manager/docker-compose.yml
e2e/_suites/ingest-manager/features/agent_endpoint_integration.feature
e2e/_suites/ingest-manager/fleet.go
e2e/_suites/ingest-manager/integrations.go

This PR bumps the package registry to `staging`. After the change, we noticed the title for the "Elastic Endpoint" integration changed to "Elastic Endpoint Security", so we renamed the feature files and other usages in consequence.
The staging tag is updated more frequently and, for master branch, we want to use latest code.
About the usage of the title instead of the name, we are using the title because the feature files have to be super readable, and the title is more readable than the name, which is usually an identifier that could bring less value from business side.
To run the endpoint integration scenarios:
```shell
$ cd e2e/_suites/ingest-manager
$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true godog -t "agent_endpoint_integration"
```
- Closes #253
```gherkin
Given the master branch
When …
```

chore: bump package registry to staging

---

e2e/_suites/ingest-manager/stand-alone.go

It renames the index used for storing the logs sent by the agent, used in the stand-alone mode test suite.
Stabilise the test suite, which is failing in master and 7.9.x (we have to backport this)
```shell
cd e2e/_suites/ingest-manager
OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true godog -t "stand_alone_mode"
```
- Closes #288

fix: use not hidden index name

---

.ci/Jenkinsfile

It uses the `JOB_BASE_NAME` environment variable to calculate the reporter name.
Simplifies backports
We need to backport this to 7.9.x

chore: use base name for flaky reporter

---

e2e/_suites/ingest-manager/fleet.go

It doubles (from 2 to 4) the max timeout in minutes for two scenarios, as we noticed they pass locally, but not on CI
It adds resiliency on CI for potentially slower machines

chore: increase more timeouts

---

.ci/Jenkinsfile

This reverts commit 43abdcc79e21b1d904bfccce3e390cc1764c798b.
It reverts using the environment variable, returning to the master branch.
It fails for PRs, because there is no flaky analiser for each PR.
- Relates #292, #293 
The backport to 7.9.x should be done manually, because the value is not `master` but `7.9.x`.
I think we could use an environment variable with the TARGET_BRANCH if it's a PR, or the JOB_BASE_NAME if it's a branch

Revert "chore: use base name for flaky reporter (#292)"

---

.ci/Jenkinsfile

This commit reverts 800409a6c4a39979f16061a1a8c8779ba46b993a
It reverts using the environment variable, returning to the 7.9.x branch.
It fails for PRs, because there is no flaky analiser for each PR.
- Relates #292, #293 
I think we could use an environment variable with the TARGET_BRANCH if it's a PR, or the JOB_BASE_NAME if it's a branch

Revert "chore: use base name for flaky reporter (#292) (#293)"

---

e2e/_suites/ingest-manager/fleet.go

Double max timeouts for slow machines
Reliability and pairing code with master branch

chore: increment timeouts

---

.ci/Jenkinsfile

It uses shared library to cancel previous builds for the same PR.
Reduce CI resources on multiple pushes

chore: cancel previous running builds when a PR is updated

---

e2e/_suites/ingest-manager/stand-alone.go

This PR changes the file to be downloaded as the agent config file, from the github branch to the github tag.
Otherwise, the agent won't find the configuration and will fail, shutting down the agent container
```
$ git checkout 7.9.x
$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true godog -t "stand_alone_mode"
```
- Closes #303

fix: use the tag instead of the branch

---

cli/docker/docker.go
e2e/_suites/ingest-manager/fleet.go
e2e/_suites/ingest-manager/ingest-manager_test.go
e2e/_suites/ingest-manager/services.go
e2e/_suites/ingest-manager/stand-alone.go

Backport of #299
- Backports #299  
When merging this PR, let's not squash the two commits, in the case they backport the new structure for the agent and we have to use the first commit, only

[7.9.x] chore: log agent logs before terminating the container

---

.ci/Jenkinsfile
e2e/_suites/ingest-manager/services.go
e2e/_suites/ingest-manager/stand-alone.go
e2e/utils.go

- chore: update slack channel (#308)
- chore: update GCP bucket calculation (#306)

chore: update slack channel (#308) | chore: update GCP bucket calculation (#306) backport for 7.9.x

---

e2e/_suites/ingest-manager/services.go

- chore: fail warm-up if the installers could not be downloaded (#320)

chore: fail warm-up if the installers could not be downloaded (#320) backport for 7.9.x

---

.ci/Jenkinsfile

It fixes a typo in a variable
Slack messages are not sent
- Relates #309
- Caused by #324

fix: rename variable after typo

---

cli/services/kibana.go
cli/services/kibana_test.go
e2e/_suites/ingest-manager/fleet.go
e2e/_suites/ingest-manager/ingest-manager_test.go
e2e/_suites/ingest-manager/integrations.go

It extracts existing integrations HTTP requests to Kibana to a dedicated client, which will handle any HTTP request (GET, POST, PUT) to Kibana APIs.
It basically moves the code responsible of creating the HTTP request from the e2e test suite to the client.
This approach will allow to unit-test the HTTP requests, supporting detecting API changes the soonest.
```shell
$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true TIMEOUT_FACTOR=3  godog -t "agent_endpoint_integration"
```
We are extracting only the inteegrations API calls, but we can move Fleet calls too.

chore: extract integrations' interactions with kibana to a dedicated client

---

cli/services/kibana.go
cli/services/kibana_test.go
e2e/_suites/ingest-manager/fleet.go
e2e/_suites/ingest-manager/ingest-manager_test.go
e2e/_suites/ingest-manager/integrations.go

It is not using `backport` tool because the APIs for 7.9.x must be changed, for that reason we cherry-picked the commits manually, updating variables and references in the first commit.
- Backports #333

[7.9.x] chore: extract integrations' interactions with kibana to a dedicated client (#333)

---

e2e/_suites/ingest-manager/features/fleet_mode_agent.feature

It moves the elastic-agent process up to be the first one in the Then clause.
It reorder steps to make it clearer the importance of the elastic-agent process to be started.
- Relates #312

chore: reorder steps by importance

---

cli/config/compose/services/elastic-agent/docker-compose.yml

We should check if we want to always use the 'observability-ci' namespace, even for the maintenance branches. For that we will need to publish there the released artifacts too. Thoughts?
It uses the observability-ci namespace in the Docker registry for the elastic-agent
Otherwise, PRs won't fetch the snapshots generated by the CI
- Discovered while testing https://github.com/elastic/beats/pull/21613
- Closes #352
- Needs https://github.com/elastic/beats/issues/21620

fix: use observabilty CI namespace for the elastic-agent image

---

e2e/_suites/ingest-manager/features/fleet_mode_agent.feature

Backport of #312 and #347
I did not use backport tool because #312 did not appear in the list of available commits :shrug:
-

[7.9.x] Reduce run time

---

cli/config/compose/profiles/metricbeat/docker-compose.yml
cli/config/compose/services/metricbeat/docker-compose.yml
e2e/Makefile

It adds a default version or the variables at the docker-compose level
Running make goals without setting the variables could cause undesired state, not being able to run the containers
See #358
- Closes #358
Backport to 7.9.x must change the default value

fix: preset default values for stack and metricbeat

---

.ci/Jenkinsfile

It uses the slack message from the shared library, which has nicer UI providing more information about the build result
Better experience communicating the build result on Slack
- 
An example of the new message:
Compared to the old one:

chore: use the enriched slack message from the shared library

---

.ci/Jenkinsfile

It builds the header string properly
The CI fails in the notify build step with the below log.
- Caused by #383
>[2020-10-22T14:01:52.243Z] groovy.lang.MissingPropertyException: No such property: testSuites for class: groovy.lang.Binding
[2020-10-22T14:01:52.243Z] 	at groovy.lang.Binding.getVariable(Binding.java:63)
[2020-10-22T14:01:52.243Z] 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:270)
[2020-10-22T14:01:52.243Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
[2020-10-22T14:01:52.243Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
[2020-10-22T14:01:52.243Z] 	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29) …

fix: proper variable interpolation

---

.ci/Jenkinsfile

- chore: use the enriched slack mesage from the shared library (#383)
- fix: proper variable interpolation (#384)

chore: use the enriched slack mesage from the shared library (#383) | fix: proper variable interpolation (#384) backport for 7.9.x

---

.backportrc.json

Adds 7.10.x maintenance branch to the backport tool. We are selecting both branches to simplify experience
Simplify backports
-

chore: add 7.10.x to backport tool

---

.ci/Jenkinsfile

Uses the right variable name.
I do not know how to read a stack trace and check that the variable name was wrong 🤦 
- Relates #383 #384 #386
Backport to 7.9.x and 7.10.x

fix: wrong variable name

---

e2e/_suites/ingest-manager/services.go

It bumps the version used to download the binaries fofr the agent, from 7.9.2 to 7.9.3
The artifact for 7.9.2 disappeared from https://artifacts-api.elastic.co/v1/search/7.9.2/elastic-agent. Current version for the snapshot is 7.9.3.
For docker images, we are generating the alias (i.e. 7.9-SNAPSHOT, 7.10-SNAPSHOT, 8.0-SNAPSHOT), but for the artifacts, where we use the binary URLs from above, we need the specific version to get the URL.
```shell
$ SUITE="ingest-manager" TAGS="" DEVELOPER_MODE=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
- Relates #395 (It does not close it yet, waiting for a possible follow-up, see below)
We could read https://artifacts-api.elastic.co/v1/versions/, and get the version for the alias
```json …
```

fix: bump minor version for the elastic-agent to 7.9.3

---

e2e/utils.go

It adds the "x-elastic-no-kpi=true" parameter to the download URL for artifacts
It will avoid adding download stats for tests
**master**
```shell
$ SUITE="fleet" TAGS="fleet_mode" DEVELOPER_MODE=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
**7.9.x**
```shell
$ SUITE="ingest-manager" TAGS="fleet_mode" DEVELOPER_MODE=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
- Closes #397 
Backport to 7.10.x and 7.9.x

chore: use URL parameter to avoid adding test stats

---

e2e/_suites/fleet/services.go

It uses the base version of the agent when preparing the layout dir after extracting the TAR file.
We use the base version for those situations where it's needed to know the real version behind the alias.
```shell
$ SUITE="fleet" TAGS="fleet_mode" DEVELOPER_MODE=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
- Forward-port of cf256adcae1ba1a706eeab15ccff34251cfcafdd
We should update master branch to use aliases too, as we already do for 7.9.x and 7.10.x. It would mean replacing 8.0.0-SNAPSHOT with 8.0-SNAPSHOT

fix: use base version to extract the TAR file

---

.ci/e2eTestingIntegrationsDaily.groovy

It uses the proper slack channel for Integrations test suite notifications, adding the ability to post a comment on greeen builds.
It uses the right channel
- Closes #402
Needs to be backported to 7.9.x and 7.10.x

chore: use the proper beats slack channel

---

e2e/_suites/fleet/configurations/kibana.config.yml

It adds a kibana setting to disable telemetry in tests
To skip any situation where telemetry is sent to real servers
- Closes #411 
Backport to 7.9.x and 7.10.x

chore: disable telemetry in tests

---

e2e/_suites/helm/README.md

It updates Helm version in docs
Consistency
- Discovered while backporting #129

docs: update helm versions

---

.ci/Jenkinsfile
cli/config/compose/services/elastic-agent/docker-compose.yml
cli/config/compose/services/metricbeat/docker-compose.yml
e2e/_suites/helm/README.md

It uses the `beats` namespace for metricbeat and the elastic-agent when running their docker images.
It also bumps Helm version
Older versions (i.e. 7.9.2) were not pushed in the CI namespace. Besides that, the 7.9.x branch uses this "released" namespace, so for consistency, we are using it here too.
- Discovered while testing #287

[7.10.x] chore: use official namespace for beats

---

.ci/Jenkinsfile

It compares strings to the empty string so that the evaluation of the channels variable is performed properly.
Besides that, we are removing an unused variable for the build status, as it's calculated in the shared library
As described in #420, the slack messages are not sent to the proper channels, using fallback one (the bots channel)
- Fixes #420

fix: send slack notifications to the proper channel

---

e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/fleet/services.go
e2e/_suites/fleet/stand-alone.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/utils.go

It retrieves the latest version from the endpoint holding latest builds and versions.
We haved the base version of the agent to the main test file, to join variable declaration and initialisation. The test runner will check this latest version at the beginning of the tests, only once, failing hard if the version cannot be reached.
In maintenance branches, we are maintaining the actual version under the alias, and we have to update it very frequently (7.9.2, 7.9.3, 7.9.4). With this new approach, it will be simpler to have maintenance branches (7.x and 7.11.x are coming), as we do not need to hardcode the internal values inside the alias.
```shell
SUITE="fleet" TAGS="fleet_mode && enroll" DEVELOPER_MODE=truee TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```
- Closes #425
We …

feat: calculate latest version for Beats

---

.backportrc.json

It adds the new 7.x branch to backport config
Important for maintenance branches

chore: add 7.x to backport config

---

.ci/packer_cache.sh

It adds picklesdoc and golang docker images in Packer
It will reduce build time
Identify new images and push updates in the script.
Question: is it possible to run the clean-docker.sh script at packer time? If so, would it be too much size to cache all those images?

chore(ci): cache docker images in packer

---

.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-integrations-daily-mbp.yml

It adds a regex to discover 7.x branch in the scheduled pipelines
It won't trigger any build for 7.x
- Fixes #436 
I guess this is not needed to be backported to maintenance branches, right? as the CI process to regen the jobs is using master branch

fix: discover 7.x branch in JJBB

---

cli/services/helm.go
cli/services/kubectl.go
cli/shell/shell_test.go
e2e/utils.go

It applies the recommendations for Go lint
The pre-commit stage is complaining, potentially affecting PRs
- Fixes #452

fix: apply golint recomendations

---

cli/services/helm.go
cli/services/kubectl.go
cli/shell/shell_test.go
e2e/utils.go

- fix: apply golint recomendations (#453)

fix: apply golint recomendations (#453) backport for 7.10.x

---

cli/services/helm.go
cli/services/kubectl.go
cli/shell/shell_test.go
e2e/utils.go

- fix: apply golint recomendations (#453)

fix: apply golint recomendations (#453) backport for 7.9.x

---

cli/services/helm.go
cli/services/kubectl.go
cli/shell/shell_test.go
e2e/utils.go

- fix: apply golint recomendations (#453)

fix: apply golint recomendations (#453) backport for 7.x

---

.ci/Jenkinsfile

It uses the isPR and isBranch steps to build the flaky test analyser reporter name
Will decouple the code from the branch
- Relates #404

chore: calculate reporter name from isPR or isBranch

---

e2e/_suites/helm/helm_charts_test.go

- chore: double Helm max timeout (#461)

chore: double Helm max timeout (#461) backport for 7.10.x

---

e2e/_suites/helm/helm_charts_test.go

- chore: double Helm max timeout (#461)

chore: double Helm max timeout (#461) backport for 7.9.x

---

.ci/Jenkinsfile

It moves the blocks to set the variable for the reporter name out of the post section, because scripts are not allowed there
It fails the build
- Caused by #465
Backport to 7.x, 7.9.x and 7.10.x

fix: move evaluation out of post section

---

e2e/_suites/helm/helm_charts_test.go

- chore: double Helm max timeout (#461)

chore: double Helm max timeout (#461) backport for 7.x

---

.ci/Jenkinsfile

It reverts #465 and #457, as we could not find why it fails on branches but passes on PRs. See #469 
We want to keep builds green avoiding to add noise in other teams' slack channels
- Reverts 457 #465
I'll send PRs reverting related commits on maintenance branches

fix: revert work for calculating reporter based on branch/pr

---

e2e/utils.go

It adds the `-f` flag to `pgrep` so that it matches against the full name of the process in the container.
Linux has a limit of 16 bytes for process names, and `pgrep` limits the process name to the 15 characters preent in the output of `/proc/pid/stat`.
See http://manpages.ubuntu.com/manpages/hirsute/en/man1/pgrep.1.html#notes
- Closes #474

fix: use full process name to match in pgrep

---

e2e/_suites/fleet/services.go

It removes the `logs/` path from the log file filepath.
We are _catting_ the log file when an step fails, and this was not failing, although not failing the build (as intended).
- Fixes #479

fix: update log path for TAR installer

---

.pre-commit-config.yaml

It adds exclusion rules to pre-commit hooks, using a proper Python regex, which is used in the hooks
When adding an image (gif or png) the lint error fails.
- Closes #496

fix: exclude images from non-breaking-spaces lint

---

e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/fleet/services.go

They set the ELASTIC_AGENT_VERSION on CI with a value the "pr-ID", so we
need to return the target version for each branch: the base version
It adds a check for Elastic agent versions starting with the "pr-" prefix, because they represent a PR (maybe sent from Beats package job).
PRs from Beats package job are broken: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/772/pipeline
- Caused by #480

fix: return base version for PRs

---

.ci/scripts/functional-test.sh
e2e/_suites/fleet/features/fleet_mode_agent.feature

It simplifies the name of the jUnit file name, because it's decoupled from parallel branch
At the moment we add complex tags leveraging Godog tags, something like `integrations && ~skip`, then the file name is broken
- Discovered on #439

chore: simplify junit report name

---

e2e/utils.go

It checks that the ELASTIC_AGENT_VERSION is a PR, to skip looking up the artifacts API, returning the PR IS used to retrieve the binaries from the GCP bucket.
PRs on beats are failing with the following error because of this bug:
>[2020-12-09T00:48:08.794Z] time="2020-12-09T00:48:06Z" level=debug msg="The Elastic artifacts API is available" elapsedTime=227.758682ms retries=1 statusEndpoint="https://artifacts-api.elastic.co/v1/versions/8.0.0-SNAPSHOT/?x-elastic-no-kpi=true"
[2020-12-09T00:48:08.794Z] time="2020-12-09T00:48:06Z" level=debug msg="Latest version for current version obtained" alias=8.0.0-SNAPSHOT version=8.0.0-SNAPSHOT
[2020-12-09T00:48:08.794Z] time="2020-12-09T00:48:06Z" level=warning msg="The Elastic artifacts API is not available yet" elapsedTime=5.247298ms error="GET …

fix: do not check artifacts API for PRs

---

.backportrc.json
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-integrations-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml
e2e/README.md

It adds 7.11.x to backport config, also setting a regex to monitor the valid branches in JJBB.
We want to retire 7.9.x and enable 7.11.x
- Closes #543
No need to backport this to maintenance branches. Once merged, we could create 7.11.x branch and update references to product versions

chore: prepare for 7.11.x release branch

---

.ci/jobs/e2e-testing-mbp.yml

It includes PRs and tags (format: v1.2.3) in the regex that defines which branches will be monitored by the JJBB job.
We broke the previous behaviour in #567, so no PRs nor tags are currently monitored
- Caused by #567

fix: monitor PRs and tags too

---

e2e/_suites/metricbeat/metricbeat_test.go

It adds a deferred function that restores the initial state for the metricbeat version variable, which is modified right after running the instance. Now this variable will return to its original value, which is originally set by the environment variable METRICBEAT_VERSION, if set.
Following executions will fail because the state is changed after running metricbeat, causing the second (and third) tests to fail, passing only the first one.
- Relates #565
Needs backport to 7.x and 7.10.x

fix: restore initial state

---

.ci/Jenkinsfile
e2e/_suites/fleet/features/fleet_mode_agent.feature
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/fleet/services.go
e2e/go.mod

It cherry-picks all commits in that PR, manually resolving conflicts.
Keep 7.10.x branch up-to-date
- Backports #537 to 7.10.x
- Relates #548
- Relates #558

[7.10.x] Backport #537

---

.backportrc.json
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml

It adds 6.8.x branch to the automation: master and PRs, and integrations' nightly builds.
We want to test integrations in Beats 6.8 branch
- Closes #574
We'll create the 6.8.x branch right after this PR is merged. In that branch, we'll remove any code not related to metricbeat integrations.

chore: support for 6.8.x branch

---

.backportrc.json

It adds the missing comma in the backport config JSON, which was not added by mistake.
To fix the lint stage.
- Caused by #578

fix: add missing comma

---

.ci/jobs/e2e-testing-integrations-daily-mbp.yml

It adds the 6.8.x branch into the nightly schedule for integrations
- Relates #574

chore: include 6.8 branch in the nightly build for integrations

---

.ci/jobs/e2e-testing-mbp.yml

Increase the shallow cloning, 
to force the JJBB run
~~- [ ] I have run the Unit tests for the CLI, and they are passing locally~~
~~- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally~~
~~- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)~~

[JJBB] Increase shallow cloning

---

.ci/Jenkinsfile
cli/shell/shell.go
cli/shell/shell_test.go
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/fleet/services.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/utils.go

- chore: store container logs in Jenkins (#577)

chore: store container logs in Jenkins (#577) backport for 6.8.x

---

.ci/Jenkinsfile
cli/shell/shell.go
cli/shell/shell_test.go
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/fleet/services.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/utils.go

- chore: store container logs in Jenkins (#577)

chore: store container logs in Jenkins (#577) backport for 7.11.x

---

e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/utils.go

- chore: increase timeout for Ceph (#618)

chore: increase timeout for Ceph (#618) backport for 7.x

---

e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/utils.go

- chore: increase timeout for Ceph (#618)

chore: increase timeout for Ceph (#618) backport for 7.11.x

---

e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/utils.go

- chore: increase timeout for Ceph (#618)

chore: increase timeout for Ceph (#618) backport for 7.10.x

---

e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/utils.go

- chore: increase timeout for Ceph (#618)

chore: increase timeout for Ceph (#618) backport for 6.8.x

---

README.md
e2e/README.md

It fixes the link to the configuration file for precommit.
Keeps contributing guide healthy

fix: typo in precommit docs

---

.ci/Jenkinsfile

It uses 5 as timeout_factor on CI, which means that instead of max 3 minutes of backoff wait,
it will be 5. The time magnitude will be the same: seconds, minutes.
We want to add reliability in the CI, and after further investigation from
the functional teams, we are adding this as a counter-measure to avoid
more flaky failures at CI time.
We ideally want to revert this commit once the team knows about the long
timeouts.
- Relates elastic/beats#23593

chore: increase timeout in CI

---

.ci/scripts/functional-test.sh

It removes a block of code in the script that triggers the tests on CI that was not removed when we bumped godog to the version where it handles internally the junit file.
It was causing that, after a test failure, the script exited with code 1, and possibly not allowing next stages to fetch the generated files.
- Relates #590

fix: let godog handle the creation of the junit test file

---

e2e/_suites/fleet/services.go
e2e/_suites/fleet/services_test.go

It prepends the artifact name (i.e. elastic-agent) to the object to calculate the GCP bucket path.
We detected that for merge commits from Beats, it uses the `commits` folder, and it needs to move to the proper beats binary directory.
```shell
make -C e2e unit-test
```
- Completes #641

fix: prepend artifact name in commits bucket

---

e2e/_suites/fleet/services_test.go

It uses current branch's base version as default value for unit tests.
This will make the tests easier to maintain, as there will be one single place to update the base version.
```shell
make -C e2e unit-test
```
- Relates #641

chore: initialiase version with branch's base version

---

e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go
e2e/_suites/fleet/services.go

This PR extracts all the code that is specific to the TAR/DEB/RPM installers to a separate file, defining the installation life cycle in a separate component.
For that reason we have moved code from the services.go file to a new file, where the responsabilities of each component are clearer. In this case, we are going to operate the OS packages:
- DEB: use `apt` to install the package
- RPM: use `yum` to install the package
- TAR: use `tar` to extract the package and then automatically install the agent
For the TAR installer, because it flattens the directory layout when extracting it, we need more data: artifact name, version, OS and arch.
This PR is not bringing new features but adding maintainability and keeping the code healthier, as we are decoupling basic installation process to a …

chore: decouple installer packages

---

e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go
e2e/_suites/fleet/services.go

- chore: decouple installer packages (#651)

chore: decouple installer packages (#651) backport for 7.11.x

---

e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go
e2e/_suites/fleet/services.go

- chore: decouple installer packages (#651)

chore: decouple installer packages (#651) backport for 7.10.x

---

e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go
e2e/_suites/fleet/services.go

- chore: decouple installer packages (#651)

chore: decouple installer packages (#651) backport for 7.x

---

e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go
e2e/_suites/fleet/services.go

- chore: decouple installer packages (#651)

chore: decouple installer packages (#651) backport for 6.8.x

---

.ci/e2eTestingFleetDaily.groovy

Recent changes in the slack channel

[CI] Change slack channel

---

.ci/e2eTestingFleetDaily.groovy

- [CI] Change slack channel (#682)

[CI] Change slack channel (#682) backport for 7.11.x

---

.ci/e2eTestingFleetDaily.groovy

- [CI] Change slack channel (#682)

[CI] Change slack channel (#682) backport for 7.10.x

---

.ci/e2eTestingFleetDaily.groovy

- [CI] Change slack channel (#682)

[CI] Change slack channel (#682) backport for 6.8.x

---

.ci/e2eTestingFleetDaily.groovy

- [CI] Change slack channel (#682)

[CI] Change slack channel (#682) backport for 7.x

---

e2e/_suites/fleet/services_test.go

It adds a bool value that was missing in different calls within test methods.
It fixes compile errors, which I did not discovered because I did not rebase the original PR (it was relatively old) and expected GH complaining because of merge conflicts, but it was not the case: instead it was a semantic conflict not detected by GH
make -C e2e unit-test
-

fix: update method args

---

.ci/Jenkinsfile
e2e/_suites/fleet/ingest-manager_test.go

It uses valid versions for the stale version in 7.10.x
We used 7.9.3, but this version is not valid anymore
-

fix: update stale version

---

e2e/_suites/fleet/features/fleet_mode_agent.feature

It skips the upgrade test for 7.10.x
We could have removed the entire scenario and related code in this branch, but let's keep it simple for now.
It should not trigger skipped tests.
```shell 
SUITE=fleet TAGS="fleet_mode_agent" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true make -C e2e functional-test
```
-

chore: skip upgrade tests for 7.10.x

---

cli/docker/docker.go
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/fleet/installers.go
e2e/_suites/fleet/services.go
e2e/_suites/fleet/services_test.go
e2e/_suites/fleet/stand-alone.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/utils.go
e2e/utils_test.go

- chore: refactor build artifacts methods (#689)

chore: refactor build artifacts methods (#689) backport for 7.x

---

cli/docker/docker.go
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/fleet/installers.go
e2e/_suites/fleet/services.go
e2e/_suites/fleet/services_test.go
e2e/_suites/fleet/stand-alone.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/utils.go
e2e/utils_test.go

- chore: refactor build artifacts methods (#689)

chore: refactor build artifacts methods (#689) backport for 7.11.x

---

cli/docker/docker.go
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/fleet/installers.go
e2e/_suites/fleet/services.go
e2e/_suites/fleet/services_test.go
e2e/_suites/fleet/stand-alone.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/utils.go
e2e/utils_test.go

- chore: refactor build artifacts methods (#689)

chore: refactor build artifacts methods (#689) backport for 7.10.x

---

.ci/Jenkinsfile
.ci/functionalTests.groovy
.ci/scripts/functional-test.sh
.ci/scripts/install-test-dependencies.sh
.ci/scripts/metricbeat-test.sh

Metricbeat goal (#705) backport for 7.x

---

.ci/Jenkinsfile
.ci/functionalTests.groovy
.ci/scripts/functional-test.sh
.ci/scripts/install-test-dependencies.sh
.ci/scripts/metricbeat-test.sh

Metricbeat goal (#705) backport for 7.11.x

---

.ci/Jenkinsfile
.ci/functionalTests.groovy
.ci/scripts/functional-test.sh
.ci/scripts/install-test-dependencies.sh
.ci/scripts/metricbeat-test.sh

Metricbeat goal (#705) backport for 7.10.x

---

cli/shell/shell.go
cli/shell/shell_test.go

It fixes the logic used to read environment variables when a fallback value wants to be used. It checks that the env var exists and it's not empty to retrieve its value, otherwise (non existing or empty) will return fallback.
It adds unit tests demonstrating the expected behaviour
Prior to this change, it did not consider empty value to require a fallback, and we used the method with that expected behavior, which never happpened.
```shell
make -C cli test
```

fix: cover fallback cases for shell.GetEnv

---

.ci/Jenkinsfile
.ci/jobs/defaults.yml
.ci/jobs/e2e-testing-beats.yml
.ci/jobs/e2e-testing-mbp.yml
.ci/scripts/install-dependencies.sh

Increase log rotation to help with test analysis

[JJBB] Increase log rotation

---

.ci/Jenkinsfile
.ci/jobs/defaults.yml
.ci/jobs/e2e-testing-beats.yml
.ci/jobs/e2e-testing-mbp.yml

- [JJBB] Increase log rotation (#724)

[JJBB] Increase log rotation (#724) backport for 6.8.x

---

.ci/Jenkinsfile
.ci/jobs/defaults.yml
.ci/jobs/e2e-testing-beats.yml
.ci/jobs/e2e-testing-mbp.yml

- [JJBB] Increase log rotation (#724)

[JJBB] Increase log rotation (#724) backport for 7.10.x

---

.ci/Jenkinsfile
.ci/jobs/defaults.yml
.ci/jobs/e2e-testing-beats.yml
.ci/jobs/e2e-testing-mbp.yml

- [JJBB] Increase log rotation (#724)

[JJBB] Increase log rotation (#724) backport for 7.11.x

---

.ci/Jenkinsfile
.ci/jobs/defaults.yml
.ci/jobs/e2e-testing-beats.yml
.ci/jobs/e2e-testing-mbp.yml

- [JJBB] Increase log rotation (#724)

[JJBB] Increase log rotation (#724) backport for 7.x

---

.ci/Jenkinsfile
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/metricbeat/metricbeat_test.go

It replaces the hardcoded 7.10.2 version for the stale agent with an alias, in this case for this branch 7.10-SNAPSHOT. For that, we are resolving the alias to the real version with the `GetElasticArtifactVersion` method.
The 7.10.2 artifact dissapeared from Elastic's artifactory, so we are consuming the alias instead, and this is causing master and 7.11.x to fail because of that.
- Closes #730
When backporting, we have to take care of the versions and aliases for each branch

chore: use alias for stale version

---

.ci/Jenkinsfile

It adds the TRACE log level on CI, keeping default to DEBUG
In the case we want to trigger the CI with more log level for debugging purpose

chore: add trace log level on CI

---

cli/config/compose/profiles/metricbeat/docker-compose.yml

It uses the official repository for Elasticseach, which contains latest snapshots.
Sometimes observability-ci is not up-to-date with the official snaphots. I.e. `elasticsearch:7.11.1-SNAPSHOT`.
- Closes #752
Backport to all maintenance branches

fix: use official repository for elasticsearch

---

.ci/packer_cache.sh

It caches filebeat:7.10.1 into Packer
It takes around 10s per parallel branch to fetch filebeat, which is always needed. It's a minor refinement, but helpful
- Closes #708
See https://github.com/elastic/apm-pipeline-library/issues/990

chore: cache filebeat in packer

---

.ci/scripts/functional-test.sh
.ci/scripts/install-metricbeat-test-dependencies.sh
cli/Makefile
e2e/Makefile

It directly uses Go to run the CLI code instead of building the CLI binary for the underlying platform. Therefore we have moved the Make goal from the e2e dir to the CLI, updating the exec command: instead of invoking the binary we are directly running Go source code.
It simplifies the process, avoiding to package the binary.
```shell
make -C cli sync-integrations
```
- Closes #740

chore: simplify synchronising the integrations

---

cli/Makefile

It makes the GO_VERSION variable to be not overridable.
This was a problem when a project downloads this one and runs the tests in an embedded manner, as it could be the case the project could use another Go version.
On the other hand, after #761, the build goal is not invoked anymore unless a release is performed, so the impact is very very low.
- Closes #703

chore: go version cannot be overriden

---

.ci/scripts/fleet-test.sh

Fleet goal (#784) backport for 7.10.x

---

.ci/scripts/fleet-test.sh

Fleet goal (#784) backport for 7.11.x

---

.ci/scripts/fleet-test.sh

Fleet goal (#784) backport for 7.x

---

e2e/_suites/fleet/ingest-manager_test.go

It updates the default value, using same value as in the CI.
Otherwise, defaut local executions of hte upgrade tests won't reproduce the CI-
```shell 
make -C e2e fleet-nightly
```
- Relates #749
WIll revisit same value in maintenance branches

fix: sync stale version for upgrade test with CI

---

.ci/.e2e-tests.yaml
e2e/_suites/fleet/features/backend_processes.feature
e2e/_suites/fleet/features/fleet_mode_agent.feature
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go

It extracts all processes-related scenarios from `Fleet Mode` feature file to a new feature file. In this new file, we will namespace all scenarios under the `@backend_processes` Cucumber annotation, so that we will be able to add a parallel branch for the test suite.
To accomplish it, we copied the scenarios from Fleet to the new file, removing all steps not related to processes. And, in the fleet file, we removed any process-related step, keeping functional steps in there.
We expect to two things:
1. reduce the CI build, as all the wait-for-process logic will be executed in the new feature file (in a parallel CI branch)
1. decouple errors related to backend process from other type of errors
```shell
SUITE="fleet" TAGS="backend_processes" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE …
```

feat: split backend processes scenarios into a new feature file

---

.ci/Jenkinsfile

It adds a `PENDING` GH status right after the git checkout
We want to provide feedback about the tests being run the soonest. Before this change, we contributed the GH status **but** at the end of the tests, which could be late for developer that already waited 1h for the package job to finish.
- Closes #838

chore: notify upstream PR/branch the soonest

---

.ci/.e2e-tests.yaml
e2e/_suites/fleet/features/backend_processes.feature
e2e/_suites/fleet/features/fleet_mode_agent.feature
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go

- feat: split backend processes scenarios into a new feature file (#837)

feat: split backend processes scenarios into a new feature file (#837) backport for 7.x

---

.ci/.e2e-tests.yaml
e2e/_suites/fleet/features/backend_processes.feature
e2e/_suites/fleet/features/fleet_mode_agent.feature
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go

- feat: split backend processes scenarios into a new feature file (#837)

feat: split backend processes scenarios into a new feature file (#837) backport for 7.11.x

---

.ci/.e2e-tests.yaml
e2e/_suites/fleet/features/backend_processes.feature
e2e/_suites/fleet/features/fleet_mode_agent.feature
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go

- feat: split backend processes scenarios into a new feature file (#837)

feat: split backend processes scenarios into a new feature file (#837) backport for 7.10.x

---

.ci/.e2e-tests.yaml
e2e/_suites/fleet/features/backend_processes.feature
e2e/_suites/fleet/features/fleet_mode_agent.feature
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/installers.go

- feat: split backend processes scenarios into a new feature file (#837)

feat: split backend processes scenarios into a new feature file (#837) backport for 6.8.x

---

.backportrc.json
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-integrations-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml

It adds the configuration for 7.12, removing 7.10. The supported configs are:
- Backport: target branches to send the backport to.
- JJBB: scheduled jobs listening for branches.
Support Beats PRs for 7.12
- Relates #802
Once merged, we can create 7.12.x branch, and then send a PR to that branch updating versions.

chore: add 7.12 and remove 7.10

---

cli/cmd/run.go
cli/cmd/stop.go
cli/config/compose/profiles/helm/docker-compose.yml
cli/docker/docker.go
cli/services/helm.go
cli/services/kibana.go
cli/services/kubectl.go
cli/services/manager.go
cli/shell/shell.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/steps/befores.go

- feat: instrument Helm charts test suite (#858)

feat: instrument Helm charts test suite (#858) backport for 7.x

---

cli/cmd/run.go
cli/cmd/stop.go
cli/config/compose/profiles/helm/docker-compose.yml
cli/docker/docker.go
cli/services/helm.go
cli/services/kibana.go
cli/services/kubectl.go
cli/services/manager.go
cli/shell/shell.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/steps/befores.go

- feat: instrument Helm charts test suite (#858)

feat: instrument Helm charts test suite (#858) backport for 7.12.x

---

cli/cmd/run.go
cli/cmd/stop.go
cli/config/compose/profiles/helm/docker-compose.yml
cli/docker/docker.go
cli/services/helm.go
cli/services/kibana.go
cli/services/kubectl.go
cli/services/manager.go
cli/shell/shell.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/steps/befores.go

- feat: instrument Helm charts test suite (#858)

feat: instrument Helm charts test suite (#858) backport for 7.11.x

---

cli/cmd/run.go
cli/cmd/stop.go
cli/config/compose/profiles/helm/docker-compose.yml
cli/docker/docker.go
cli/services/helm.go
cli/services/kibana.go
cli/services/kubectl.go
cli/services/manager.go
cli/shell/shell.go
e2e/_suites/fleet/ingest-manager_test.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/elasticsearch.go
e2e/steps/befores.go

- feat: instrument Helm charts test suite (#858)

feat: instrument Helm charts test suite (#858) backport for 6.8.x

---

.ci/Jenkinsfile

- [CI] tear down the workspace (#885)

[CI] tear down the workspace (#885) backport for 7.11.x

---

.ci/Jenkinsfile

- [CI] tear down the workspace (#885)

[CI] tear down the workspace (#885) backport for 7.12.x

---

.ci/e2eTestingFleetDaily.groovy

It uses `#elastic-agent` instead of `#fleet` Slack channel for sending notifications.
New one is more accurate and it narrows down to the right people.

chore: rename slack channel for Fleet's nightly build

---

.ci/Jenkinsfile
e2e/_suites/fleet/ingest-manager_test.go

This PR is bumping the version of the stale agent used in the upgrade tests from `7.10-SNAPSHOT` to `7.11-SNAPSHOT`.
The stale agent used in the upgrade agent test required 7.10-SNAPSHOT, but this version is not present anymore in https://artifacts-api.elastic.co/v1/versions/. For that reason, The nightly builds fails for the master branch.
- Fixes #911

fix: bump stale agent version to 7.11-SNAPSHOT

---

.mergify.yml
README.md

Automate the backport with mergify
Simplify the backport process with github labels.
- Already enabled by infra for this project

Add mergify

---

.ci/Jenkinsfile
e2e/_suites/fleet/world.go

It bumps stale agent version from 7.11.1 to 7.11.2
7.11.1 dissapeared from https://artifacts-api.elastic.co/v1/search/7.11.1/elastic-agent

fix: bump stale agent version to 7.11.2

---

cli/services/kibana.go
e2e/_suites/fleet/features/linux_integration.feature
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/integrations.go

Adds a Linux integration test scenario. This test only checks that the integration is installed, the right data stream is created, and some data is ingested.
Let me know if this should cover something else.
NOTE: I removed the Git pre-commit hook. `go lint ./...`, `make golint`, and `golangci-lint run` all pass successfully, but the golint step from the pre-commit hook keeps failing. I don't know what else I need to do to lint this, so hoping CI or someone can tell me. 
To test the Linux integration!
~~- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)~~
`godog -t @linux_integration`
Implements #825

Add basic tests for the Linux integration

---

cli/README.md

The current code examples were referencing outdated docker versions and also a
profile that is not available by default.
This is a documentation update to reflect the current profiles and docker images available to allow the code examples to run properly
Currently, the readme was outlining code examples that could not be run
You should be able to copy and paste the updated code examples to run without any further modifications.
-

Update readme with correct service versions and profile

---

e2e/_suites/fleet/stand-alone.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/steps/configurations.go
e2e/utils.go

- fix: use PRs configuration files (#956)

fix: use PRs configuration files (#956) backport for 7.11.x

---

e2e/_suites/fleet/stand-alone.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/steps/configurations.go
e2e/utils.go

- fix: use PRs configuration files (#956)

fix: use PRs configuration files (#956) backport for 7.12.x

---

e2e/_suites/fleet/stand-alone.go
e2e/_suites/metricbeat/metricbeat_test.go
e2e/steps/configurations.go
e2e/utils.go

- fix: use PRs configuration files (#956)

fix: use PRs configuration files (#956) backport for 7.x

---

e2e/_suites/fleet/world.go

Instead of using a fixed version of an old artifact, we are going to use the snapshot.
Otherwise, the artifact could disappear, causing the 7.11 builds to fail because the artifact is not present in the response.
- Closes #1001

fix: use snapshot artifact for stale agent 7.11.2

---

.ci/Jenkinsfile

It updates Jenkins default parameter to use the new version
I forgot to update the Jenkinsfile, which is prescriptive to create the build environment on CI 😞 
- Completes #1002

fix: use snapshot artifact for stale agent 7.11.2 in Jenkins

---

cli/config/compose/services/elastic-agent/docker-compose.yml
e2e/_suites/fleet/features/stand_alone_agent.feature
e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/stand-alone.go

It reverts the following PRs:
- Revert "Add a standalone test scenario for fleet server mode (#978) (#988)"
- Revert "Uniquify the stand-alone step for checking agent status (#993) (#997)"
Fleet Server is available from 7.13 and beyond, so it does not apply to 7.11.x

chore: revert standalone scenario for fleet server in 7.11

---

.ci/jobs/kibana-e2e-tests.yml

It removes definitions in the JJB file to download a revision for the current repository, as we noticed Jenkins failed to build the initial job.
We do not want to fetch this repo in a revision, as we want to build a kibana PR, and trigger a build for the maintenance branch.
- Relates #901

fix: use same JJB than in custom kibana

---

.ci/Jenkinsfile
e2e/_suites/fleet/world.go

It uses 7.11.3-SNAPSHOT instead of 7.11.2-SNAPSHOT
7.11.2-SNAPSHOT dissapeared from the artifacts endpoint

fix: bump stale version, as 7.11.2 dissapeared

---

e2e/_suites/fleet/features/fleet_mode_agent.feature

Removes consistently failing step
Green builds without noise

remove uninstall step

---

.ci/jobs/kibana-e2e-tests.yml

It uses a branch that exists in the repository (master)
The default checkout did not find the previous refspec, causing the build to fail, not generating the configuration
- Relates #1010 #905

fix(jjb): use a branch that exists

---

.ci/e2eKibana.groovy

It adds Node modules to the PATH on build time. This is a temporary solution meanwhile we release a new version of the shared library.
Besides that, it reuses the existing step to check permissions for who triggered the tests with the comment in Kibana PRs
It will fix the error for not finding NPM, NODE nor YARN commands on the CI worker when building the Docker image for a kibana PR
- Relates #1030
We could add exact same code to the shared library step, so any client code will benefit from it

fix: add NodeJS to PATH

---

.ci/e2eKibana.groovy

It removes a `$` from a variable name when using it.
The variable is not properly expanded, returning `null`, causing an error when using that variable (it's used to query Github API)
- Caused by #1045

fix: incorrect variable name

---

e2e/_suites/fleet/ingest_manager_test.go
e2e/utils.go
e2e/utils_test.go

It adds a function to verify if a given string matches the commit format, which is driven by the `\b[0-9a-f]{5,40}\b` regexp.
This new function will be used to determine which docker namespace to use when pulling the docker image for Kibana
If the version is a sha1, which happens when triggered by a Kibana PR, then uses the `kibana` namespace instead of the `observability-ci`. See https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/720/pipeline/#step-401-log-83

fix: check if kibana version is a commit

---

.ci/jobs/build-docker-images.yml

It fixes paths in JJBB
Place the job in the proper folder, and fetch the proper repo.
- Completes #1091

fix: update JJBB with proper values

---

.ci/build-docker-images.groovy

Fixes the variable name for the vault secret, as it was a wrong copy&paste.
Following same patterns is important: i used DOCKER_REGISTRY* as namespace, but copied from other pipeline its usage :/
- Caused by #1097

fix: use proper variable name

---

.ci/build-docker-images.groovy

It uses a wider selector for CI workers, as the `arm` label should grab the proper workers.
With the previous one, the worker provisioner could take long time to match or even it's possible to not find a worker.
-

fix: use wider selector for ARM workers

---

e2e/_suites/fleet/fleet.go

Fixes bug: agent should be uninstalled regardless log level

fix agent uninstall

---

.ci/Jenkinsfile

It bumps the stale agent version from 7.11-SNAPSHOT to 7.13-SNAPSHOT, which is one minot versior lower than 7.x (which is 7.14)
Keep 7.x consistent after 7.14 was created
- Relates #1085 #1098

chore: bump stale agent for 7.x

---

.backportrc.json
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-integrations-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml
.mergify.yml

This PR updates the descriptor files for Jenkins to track the 7.13.x branch
- JJBB files
- backport config
- mergify config
We want to retire 7.11.x and test 7.13.x, after 7.x being promoted to 7.14
- Relates #1098

chore: update descriptors for 7.13.x

---

e2e/_suites/fleet/ingest_manager_test.go
internal/docker/docker.go

It abstract the pull images method so that the consumer is passing what images to pull
To make the pull method reusable by other test suites.
- Relates #1123

chore: abstract image pulling

---

.mergify.yml

It adds the  target branch in backports from Mergify
Better visibility in the list of open PRs

chore: update mergify's titles

---

.mergify.yml

It tells mergify to remove the upstream branches when merging a PR from the upstream repository.
To keep the repository clean (and satisfy my obsessive compulsive disorder about outdated branches)

chore(mergify): delete upstream branches on merge

---

e2e/_suites/fleet/features/stand_alone_agent.feature

It adds a new step in the scenario that bootstraps the fleet server, adding a stronger verification for the backend processes, in this case checking that thre is one instance of the fleet-server process running.
To define a comprehensive set of assertions in this scenario/test.
```shell
SUITE="fleet" TAGS="stand_alone_agent && bootstrap-fleet-server && default" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE BEATS_USE_CI_SNAPSHOT=false DEVELOPER_MODE=true make -C e2e functional-test
```
- Closes #1161

feat: make a stronger verification of fleet-server being bootstrapped

---

e2e/_suites/fleet/README.md
e2e/_suites/metricbeat/README.md

It simply moves one explanation about how to install Beats' integrations from fleet test suite docs to the Metricbeat one.
Fix the bug in docs
- Closes #1105

docs: document integrations in the proper README file

---

.ci/Jenkinsfile

It adds a boolean input parameter to the Jenkins pipeline, which will decide whether the `pullRequestFilter` arguments must be passed to the test runner or not. These filters are declared in the `.e2e-tests.yaml` file, adding boolean expressions for godog's test runner to select the scenarios to include in the current execution.
This new param will allow a user to trigger a CI job including all supported platforms without skipping the less used ones: debian for Fleet test suite, or older versions of MySQL for the Metricbeat integrations test suite.
~~- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally~~
~~- [ ] I have run the End-2-End tests for the suite I'm working on, and …

chore: support running a build as the master branch

---

e2e/_suites/helm/helm_charts_test.go
e2e/_suites/metricbeat/metricbeat_test.go

It uses the `afterScenario` and `afterStep` test life cycle hooks to handle errors happened in the tests, sending them as APM errors
It will mark failed scenarios/steps as APM errors in the APM UI.
- Closes #1196

chore: handle APM errors properly

---

e2e/_suites/fleet/fleet.go
e2e/_suites/fleet/ingest_manager_test.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/metricbeat/metricbeat_test.go
internal/common/defaults.go
internal/elasticsearch/client.go

It moves the initialisation of the DEV_MODE, PROVIDER and ELASTIC_APM_ENABLED variables to the internal package, so that they are initialised only once.
It also adds a helper function to check if a local APM environment needs to be created, checking that the `ELASTIC_APM_ENVIRONMENT` is equals to `local` and APM is enabled.
It simplifies the init process for each test suite (existing and future ones), also locating the code in one single place: Go's init method for the common package.

chore: initialise shared variables only once

---

.ci/Jenkinsfile

On CI, it adds beat version and stack version as APM global labels.
It will be possible to use label filters to distinguish from executions in different maintenance branches (== versions of the products under test)
- Relates #687

chore: label beat and stack versions as APM labels

---

.ci/e2eKibana.groovy

It skips the default checkout in all stages, as we do not want that: the code is fetching Kibana's repo.
We started to see the following error:
>[2021-06-09T12:10:18.397Z] process apparently never started in /var/lib/jenkins/workspace/e2e-tests/e2e-testing-kibana-fleet/src/github.com/elastic/kibana/build@tmp/durable-0cf15004
[2021-06-09T12:10:18.397Z] (running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
[2021-06-09T12:10:18.422Z] Cannot contact beats-ci-immutable-ubuntu-2004-1623239911274313537: java.io.FileNotFoundException: File '/var/lib/jenkins/workspace/e2e-tests/e2e-testing-kibana-fleet/src/github.com/elastic/kibana/build@tmp/durable-0cf15004/output.txt' does not exist
And it may be related to …

chore: skip default checkout

---

e2e/_suites/fleet/features/stand_alone_agent.feature

It adds the `@skip:arm64` cucumber tag to the existing ubi8 scenarios (4), so that they are skipped on CI for the ARM workers. See [Jenkinsfile:L324](https://github.com/elastic/e2e-testing/pull/707/files#diff-ef8b2f5e4d21d81c0eba4754dea3a3dfc2c67d26284f195165b650cf4aff7beaR319).
Ubi8 tests are failing for the nightly builds, and this is caused because the ubi8 image that is pulled by Docker Compose is the AMD one, instead of the one for ARM.
- Closes #1248
- Relates elastic/beats#24186

fix: skip scenarios for standaline with ubi8 images on ARM

---

.ci/e2eKibana.groovy

It uses the right attribute when invoking the kibana build step
-

fix: use proper attribute for library step

---

.ci/e2eKibana.groovy

It adds two things:
- missing environment variables for pushing images to the Elastic's registry (read from vault)
- use the right parameters to build the multiplatform image: instead of passing a platform-based tag, we need to build/pass a platform-based image name: (kibana-amd64, kibana-arm64)
The push is failing because of above reasons
- Relates #1252 #1249

fix: use proper image format

---

e2e/_suites/fleet/features/agent_endpoint_integration.feature
e2e/_suites/fleet/stand-alone.go

Changing minimumHitsCount from 50 to 25
This PR will reduce running time of selected tests from 10 to 3 min
Run stand-alone test with @deploy-stand-alone tag

Changing minimumHitsCount from 50 to 25

---

e2e/_suites/fleet/ingest_manager_test.go
e2e/_suites/helm/helm_charts_test.go
e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
e2e/_suites/metricbeat/metricbeat_test.go

It adds more context to the APM errors that we produce, adding the Gherkin scenario/step that caused the error as an APM label. We also include the Gherkin entity type: step or scenario
There are some errors that simply show: `signal: terminated`, and we'd like to enrich the metadata with APM labels.
I.e. https://jenkins-stats-oblt.elastic.dev/app/apm/services/E2E%20Tests/errors/93ced3616eec6d6957996ae112adfd24?kuery=error.exception.type:%22ExitError%22&rangeFrom=now%2Fd&rangeTo=now%2Fd&environment=ENVIRONMENT_ALL&detailTab=metadata

chore: add labels for APM errors

---

.ci/e2eKibana.groovy

It checkouts the git repo for the e2e before using the script, which is located on it
The script cannot be found and I think it's because the repository is never checked out
- Completes #1277

fix: checkout current project

---

.ci/e2eKibana.groovy

We are passing repo and branch to the step, as it runs in the context of a regular pipeline, not a multi-branch pipeline.
The pipeline fails on checkout. See https://github.com/elastic/apm-pipeline-library/blob/master/vars/gitCheckout.groovy to know how the step must be configured
- Completes #1286

fix: configure gitCheckout step properly

---

internal/installer/elasticagent_zip.go

It uses the new method added in #1272
That PR should have updated the usage of the old methods in the ZIP installer code, but because it's not executed on the CI yet, it was missed. Nevertheless, the pre-commit hook caught it locally.
- Caused by #1272
- Relates #1269

fix: use new method to calculate binary paths in ZIP installer

---

.backportrc.json
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-integrations-daily-mbp.yml
.ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml
.mergify.yml

It retires 7.12.x branch in favour of the new 7.14.x one
Snapshots for 7.12 are not available anymore, and we want to run tests against 7.14 changes.
- Closes #1293

chore(ci): listen for 7.14 branch, retiring 7.12

---

.ci/Jenkinsfile

Expands Ci to allow for the `/test` trigger to re-run tests
-

ci: allow /test trigger

---

cli/config/compose/profiles/fleet/docker-compose.yml

Successfully got the right syntax needed for
XPACK_FLEET_AGENTS_FLEET_SERVER_HOSTS as it required an parseable json array
string for Kibana to acknowledge it properly
Re-enables remote docker daemon support for running deployments and tests
- Reference: https://github.com/elastic/kibana/issues/103891#issuecomment-876681777

Re-enable docker remote with correct kibana config

---

e2e/_suites/fleet/README.md
e2e/_suites/helm/README.md
e2e/_suites/kubernetes-autodiscover/README.md
e2e/_suites/metricbeat/README.md
e2e/commons-test.mk

This updates the references to switching from the godog binary to using go test
exclusively. This makes the testing experience consistent across all operating
systems as godog will not compile on Windows but utilizing godog through go test
works as intended.
```
cd e2e/_suites/fleet
OP_LOG_LEVEL=DEBUG go test -v
```
- Fixes #1309

Update readmes to reflect using go test instead of godog binary

---

e2e/_suites/fleet/fleet.go

There seems to be a time gap between when an enrollment token is deleted and
when the stack actually knows it is deleted.
Ref: https://github.com/elastic/kibana/issues/105078
-

Temporary fix for revoke token tests

---

cli/config/compose/profiles/fleet/docker-compose.yml
cli/config/compose/profiles/metricbeat/docker-compose.yml
cli/config/kubernetes/base/elasticsearch/deployment.yaml
cli/config/kubernetes/base/fleet-server/deployment.yaml
cli/config/kubernetes/base/kibana/deployment.yaml

Bump stack version with the latest one. 
[start_time:Wed, 21 Jul 2021 00:24:20 GMT, release_branch:master, prefix:, end_time:Wed, 21 Jul 2021 04:43:25 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-1e9bea0f, build_duration_seconds:15545]

[automation] update elastic stack version for testing 8.0.0-1e9bea0f

---

cli/config/compose/profiles/fleet/docker-compose.yml
cli/config/compose/profiles/metricbeat/docker-compose.yml
cli/config/kubernetes/base/elasticsearch/deployment.yaml
cli/config/kubernetes/base/fleet-server/deployment.yaml
cli/config/kubernetes/base/kibana/deployment.yaml

Bump stack version with the latest one. 
[start_time:Wed, 21 Jul 2021 12:17:25 GMT, release_branch:master, prefix:, end_time:Wed, 21 Jul 2021 16:52:14 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-a6334483, build_duration_seconds:16489]

[automation] update elastic stack version for testing 8.0.0-a6334483

---

cli/config/compose/profiles/fleet/docker-compose.yml
cli/config/compose/services/elastic-agent/docker-compose.yml
e2e/_suites/fleet/stand-alone.go

It adds Fleet Server port to the docker-compose profile for Fleet.
Because we are going to start using a remote approach, the fleet server must be accessible from outside the Docker network.
- Relates #1258

fix: expose fleet-server port

---

e2e/_suites/kubernetes-autodiscover/features/filebeat.feature
e2e/_suites/kubernetes-autodiscover/testdata/templates/filebeat.yml.tmpl
internal/kubernetes/kubernetes.go

Add a common scenario for collection of kubernetes logs.
Added to the autodiscover suite because is an overlapping use case, though this doesn't use autodiscover features.
This is the default configuration recommended for filebeat in kubernetes and is a pretty common use case.
It adds coverage for `add_kubernetes_metadata`.
-

Add kubernetes autodiscover scenario with inputs

---

go.mod
go.sum

It bumps the agent to latest release
To fix a CVE in current version of the agent.
- Closes #1396

chore: bump Go agent to v1.13.0

---

e2e/README.md

Minor fix to documentation link

Fix documentation link

---

internal/common/defaults.go

It bumps the base version for BEATS
It could impact the test framework, selecting a non existing artifact
- Completes #1431

fix: use alias as base version

---

e2e/_suites/fleet/fleet.go

It uses the elastic version helper methods to retrive the version including context: for this specific use case, where the upgrade code is comparing versions without git commits, we need to convert the provided version (including commit) to a version without it.
Because we are automatically bumping the versions used in the master branch to get the latest versions from the artifactory, and those versions include the Git sha commit in the version (i.e. 8.0.0-abcdef-SNAPSHOT), we need the tests to remove that git commit from the comparison between versions in the upgrade test, which is run in nightly builds, only (we do not run this test scenario on PRs, cc/ @michalpristas for awareness)
7.13 branch does not include the upgrade tests, that's why we do not need a backport to that branch

fix: use version without commit when upgrading the agent

---

e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
e2e/_suites/metricbeat/metricbeat_test.go
internal/installer/elasticagent_docker.go

It uses the version in the right context, which is removing the git commit from the version when loading/tagging a downloaded Docker image.
Beats merge commits are failing hard.
- Completes #1470

fix: tag images without git commit

---

.ci/Jenkinsfile

It does three things for the tests running on Windows:
- wraps the execution of the remote stack (which runs on a Linux node) with a `filebeat` step, to be able to capture container logs and see them in Jenkins UI.
- removes the installatino of UNZIP, as we use powershell to extract the archive
- avoids hardcoding the test suite name when running the stack profile, which was set to Fleet.
We are seeing a consistent error for Fleet `install` command on Windows in the 7.13.x, and we'd need to collect the logs of fleet-server to identify why the command fails and hangs up without response, running out the default timeout for the operation (up to 10 mins).
- Relates https://github.com/elastic/beats/issues/27501

chore: grab stack logs

---

.backportrc.json
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-integrations-daily-mbp.yml
.ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml
.mergify.yml

It retires 7.13.x from Jenkins, mergify and backport tool, adding 7.15.x
7.13 does not receive backports and 7.16.x is here
- Completes #1492 
- Relates #1484

chore: retire 7.13.x branch in favour of 7.15.x

---

.ci/jobs/e2e-testing-mbp.yml

This PR mimics what the APM Agent Ruby has in its JJBB configuration for the build.
We want to keep as many build executions as possible, as the branches in the main MBP are used as downstream by multiple projects: nightly builds, Beats, and the development of the project itself.
- Closes #1449

chore: increase builds to keep

---

cli/config/kubernetes/overlays/deployment.yaml

It uses the OBLT CI Docker image for centos as the base image for k8s deployment.
Consistency

chore: use our Docker image

---

.ci/scripts/install-dependencies.sh
.pre-commit-config.yaml
cli/config/config.go
internal/deploy/docker.go
internal/deploy/docker_client.go
internal/deploy/remote.go
internal/elasticsearch/assertions.go
internal/elasticsearch/client.go
internal/installer/elasticagent_deb.go
internal/installer/elasticagent_docker.go
internal/installer/elasticagent_rpm.go
internal/installer/elasticagent_tar.go
internal/installer/elasticagent_tar_macos.go
internal/installer/elasticagent_zip.go
internal/kibana/agents.go
internal/kibana/fleet.go
internal/kibana/url_prefixes.go
internal/utils/utils.go

This PR removes go-lint from pre-commit, using [staticheck](https://staticcheck.io/) instead.
For that we are adding it to the pre-commit hooks, and adding one commit per issue resolved.
Consistency across Go projects in the OBLT space.
```shell
pre-commit install
pre-commit run go-static-check -a
```
- Relates https://github.com/elastic/elastic-package/pull/503
- Relates https://github.com/golang/go/issues/44354#issuecomment-835504889

chore: use staticcheck instead of go-lint

---

.ci/scripts/install-dependencies.sh
.pre-commit-config.yaml

It reverts to golint while we detect why errcheck is failing.
PRs are failing because errcheck cannot be found, even though it's installed.
-

chore: revert to golint

---

.ci/Jenkinsfile
internal/common/defaults.go

It bumps the stale version for 7.x, using 7.15-SNAPSHOT. 7.x is at the moment of writing 7.16
Fix the upgrade scenario, as it used a version that is not found in elastic's artifactory
-

chore: bump stale version to 7.15-SNAPSHOT

---

.ci/Jenkinsfile
internal/common/defaults.go

It bumps the stale version for 7.15.x, using 7.14-SNAPSHOT.
Fix the upgrade scenario, as it used a version that is not found in elastic's artifactory
-

chore: bump stale agent to 7.14-SNAPSHOT

---

.github/paths-labeller.yml

It changes the label for Fleet, from Ingest Manager to Agent team, and removes the metricbeat label
-

chore: update paths-labeller

---

internal/installer/elasticagent_zip.go

Fixes a small lint error in the code for windows installer
-

Fixes lint error

---

.ci/Jenkinsfile

It adds Godog's formatting flag to the Windows execution, as it was simply reporting the test results in the default format (pretty) (See https://github.com/cucumber/godog#testmain)
The Windows stage was not contributing test results to the CI build, causing a Zero-test-errors build even though the build was unstable (yellow). The slack message sent to the teams was misleading because it uses the yellow color indicating UNSTABLE status, but with zero failed tests, causing an incomplete experience.
- Fixes #1612
We should consider creating a BAT script for windows, adapting the Makefile to be multi-platform

chore: report godog tests in junit format on Windows

---

.ci/e2eKibana.groovy

It simplifies how the build-tests-for-kibana fetches the script to push the multiplatform images.
Instead of cloning the entire repo, we are simply downloading the file
KISS
besides that, the build is failing at pushing in the GitHubStatusNotificationStep, and we think it's caused by the `gitCheckout` step requiring notify-first-time-contributor:
```stacktrace
java.lang.IllegalArgumentException: Unable to infer git data, please specify repo, credentialsId, account and sha values
at org.jenkinsci.plugins.pipeline.githubstatusnotification.GitHubStatusNotificationStep$Execution.getSource(GitHubStatusNotificationStep.java:494)
at org.jenkinsci.plugins.pipeline.githubstatusnotification.GitHubStatusNotificationStep$Execution.tryToInferCredentialsId(GitHubStatusNotificationStep.java:451)
at …
```

fix: simplify downloading push script

---

.ci/e2eKibana.groovy

It executes the script from BASE_DIR, to avoid adding it to PATH
The script was not discovered as it's not in PATH
- Completes #1629

fix: run script from relative path

---

.ci/e2eFleetServer.groovy

It uses `mage` build tool as a Go dependency (see https://github.com/elastic/beats/blob/cca59bad174b56ced2f74bccc6694f233752eecd/tools/tools.go#L25) and install ZIP as a Linux package in the ubuntu worker.
The build system of Fleet Server and Beats needs to add those libraries to complete a full build/package of the project.

chore(ci): install build tools

---

.pre-commit-config.yaml

Uses HTTPS for pre-commit
It started to fail today with:
```shell
[2021-11-02T13:07:21.659Z] + pre-commit install --install-hooks
[2021-11-02T13:07:21.659Z] pre-commit installed at .git/hooks/pre-commit
[2021-11-02T13:07:21.659Z] [WARNING] The 'rev' field of repo 'git@github.com:elastic/apm-pipeline-library' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[2021-11-02T13:07:21.659Z] [INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[2021-11-02T13:07:21.919Z] An unexpected error has occurred: CalledProcessError: command: …
```

fix: use HTTPS protocol for pre-commit hooks

---

.backportrc.json
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml
.mergify.yml

This PR adds the recently created `8.0` branch to the descriptors we used for automated work:
- backport tool
- mergify
- regular MBP for the project
- scheduled MBPs for nightly builds for specific projects (fleet, k8s-autodiscover and hel charts)
Adds 8.0 in the automation
- 
After merging this, new jobs will appear for 8.0 branch in the nightly builds, we should manually trigger them to enable the daily schedule.

chore: add 8.0 branch to descriptors

---

e2e/_suites/fleet/features/fleet_mode_agent.feature

It removes the upgrade scenario from the feature file
The stale version, 7.14, is not present in current artifactory, that's why the scenario fails in 7.15 nightly builds
- 
Maybe we shuold investigate with Infra how to access artifacts that are out from the 2-minor-release window

chore: remove upgrade tests from 7.15

---

e2e/_suites/fleet/fleet.go

It uses log.Infof properly, setting the status as first parameter in the replacement of the predefined `%s` format
Misleading messages could make it difficult to debug
- Caused by #1807

fix: use format correctly

---

internal/kibana/integrations.go

The POST metadata endpoint is being deprecated in favor of using GET request
instead. No parameter changes required.
Ref: https://github.com/elastic/kibana/pull/119401
-

Fixes #1847

---

.mergify.yml

Fix mergify syntax for pull_request_rules

---

internal/kibana/integrations.go

It adds the package name to both logs and APM spans when an error occur after not finding an integration package.
We have seen error logs that are not clear enough to identify a failure:
```
[2021-12-13T14:59:37.332Z] FATA[2021-12-13T14:59:37Z] Unable to find package
```
For that we'd like to add the name of the package to them.
- Discovered while testing #1895

chore: add package name to error logs and spans

---

e2e/_suites/fleet/fleet.go

It changes the signature of the internal `readJSONFile` method to return the error, instead of silently calling log.Fatal, which internally calls `os.Exit(1)`
We do not want to abort the execution at this moment, but instead throw the error to be handled upstream

chore: do not exit with log.Fatal while reading JSON file

---

.ci/Jenkinsfile

This PR does two things:
1. wraps the evaluation of the stack deployment stage in an `anyOf` block, so that is consistent with all other stages.
2. extracts the logic to evaluate if the tests must be skipped to a single function. This function starts setting the `SKIP_TESTS` env var to false, and:
- if there are only markdown files in the changeset, the it will set the env var `SKIP_TESTS` to true.
- if the changeset contains at least one modified file matching certain paths (see the modified files in this PR), then it will set the `SKIP_TESTS` env var to false.
The unit tests stage is constantly skipped.
- Fixes #1915

chore: properly evaluate how tests are skipped on CI when checking modified files

---

.ci/Jenkinsfile
.ci/build-docker-images.groovy
.ci/e2eFleetServer.groovy
.ci/e2eKibana.groovy
.ci/jobs/build-docker-images.yml
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml
.ci/jobs/fleet-server-e2e-tests.yml
.ci/jobs/kibana-e2e-tests.yml
.mergify.yml
README.md
cli/README.md
e2e/README.md

Update main branch in the JJBB/Jenkinsfile/Docs and other places

Update main branch

---

.ci/Jenkinsfile
internal/common/defaults.go

It bumps the stale agent for 8.0 to 7.17, which is current version -1
Use an existing version to upgrade
- Closes #2012

chore: bump stale agent for 8.0

---

.mergify.yml

It uses 7.17 as the branch used by mergify when a `backport:7.17` label is added to a PR
7.17 was not receiving backports and it was because of that

fix: use the right branch for 7.17 backports

---

.ci/Jenkinsfile
.ci/ansible/github-ssh-keys
.ci/ansible/playbook.yml
.ci/ansible/tasks/install_deps.yml
.ci/ansible/tasks/install_ssh_keys.yml
.ci/ansible/tasks/runners.yml
.ci/aws-instances-reaper.groovy
.ci/jobs/aws-instances-reaper.yml
.ci/scripts/import-ssh-keys.sh
e2e/TROUBLESHOOTING.md

Backports the following commits to 7.17:
- feat: enable SSH access to users for debugging cloud instances (#2001)

feat: enable SSH access to users for debugging cloud instances (#2001) backport for 7.17

---

.ci/Jenkinsfile
.ci/ansible/github-ssh-keys
.ci/ansible/playbook.yml
.ci/ansible/tasks/install_deps.yml
.ci/ansible/tasks/install_ssh_keys.yml
.ci/ansible/tasks/runners.yml
.ci/aws-instances-reaper.groovy
.ci/jobs/aws-instances-reaper.yml
.ci/scripts/import-ssh-keys.sh
e2e/TROUBLESHOOTING.md

Backports the following commits to 8.0:
- feat: enable SSH access to users for debugging cloud instances (#2001)

feat: enable SSH access to users for debugging cloud instances (#2001) backport for 8.0

---

.ci/.e2e-tests-for-elastic-agent.yaml
.ci/.e2e-tests.yaml
.ci/Jenkinsfile

It adds the suite name to the name of the Jenkins stage representing an execution of the tests.
It also uses a right machine type for ARM
The suite is not shown and visual inspections on Jenkins UI could be slower
- Follow-up of #2034

chore: rename Jenkins stage to include suite

---

.ci/Jenkinsfile
.ci/ansible/requirements.txt
.ci/ansible/tasks/wait_for_ssh.yml

- Relates https://github.com/elastic/e2e-testing/issues/2071

fix: use ansible.cfg in the right path

---

.ci/ansible/playbook.yml
.ci/ansible/tasks/setup_test_script.yml

~~It removes the when clause for the installation of the dependant roles when provisioning the runners representing the target VMs~~
Update: it fixes a typo in the when expression, where we were using the `nodeLabel` variable instead of `suite`, also updating the value used for the when condition:
```diff
- kubernetes_autodiscover
+ kubernetes-autodiscover
```
We want to have reproducible builds, and having all tooling installed for each specific test suite is key, that¡s why we are installing the tools with the right when conditions.

chore: always install tools in runners

---

cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml

Uses 8.0 version for fleet-server
The current value was added by a backport, so it's wrong
- Caused by #2101

fix: use valid version for 8.0

---

.ci/bump-stack-version.sh

It will update the version for services using the existing script, so no more manual updates.
We detected the services did not receive the bump, and fleet-server and elastic-agent containers are now deployed from there.
```shell
./.ci/bump-stack-version.sh a-version
```

chore: bump version for services

---

.ci/Jenkinsfile
.ci/ansible/playbook.yml
.ci/ansible/tasks/copy_test_files.yml
.ci/ansible/tasks/install_deps.yml
.ci/ansible/tasks/runners.yml
.ci/ansible/tasks/setup_test_script.yml
e2e/_suites/fleet/fleet.go
internal/kibana/policies.go

- fix: remove update cache
- fix: update nodeUser variable
- chore: bump Go to 1.17
- chore: sync Ansible tasks
- chore: remove duplicated task after backport
- chore: format equals to main
It puts the Ansible code in sync with main branch
Keep deployment stable across maintenance branches

fix: add missing backports selectively

---

cli/config/compose/services/elastic-agent/docker-compose.yml

It updates the version of the elastic-agent on its Docker Compose.
Keep versions up-to-date

fix: right version for 8.0

---

cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
cli/config/compose/services/elastic-agent/docker-compose.yml
cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
cli/config/compose/services/elasticsearch/docker-compose.yml
cli/config/compose/services/kibana/docker-compose.yml
cli/config/compose/services/metricbeat/docker-compose.yml

It uses the ssame stac-version across all docker-compose files
We want to avoid having mismatching versions where starting up services, in particular de fleet-server
It should have been corrected by the automated bump, but because it's always failing the PR, then it's never merged in the automated process.

fix: sync versions with stack

---

.ci/ansible/github-ssh-keys

Add my username to the github ssh key list.
-

Add ph to the e2e github-ssh-keys

---

.ci/Jenkinsfile
internal/common/defaults.go

It bumps stale agent from 7.16-SNAPSHOT to 7.17.1-SNAPSHOT
Because 7.16 disappeared from the Elastic artifacts, therefore the upgrade scenario is failing in this branch

fix: bump stale agent

---

.ci/.e2e-tests-for-elastic-agent.yaml
.ci/.e2e-tests.yaml
.ci/ansible/tasks/install_deps.yml
.ci/ansible/tasks/runners.yml

It adds support for Oracle Linux 8 for the "running-on-beats" scenarios.
Increase the support matrix
- Closes https://github.com/elastic/e2e-testing/issues/2196

chore: support for Oracle Linux 8

---

.ci/Jenkinsfile
.ci/ansible/tasks/setup_test_script.yml
.ci/scripts/functional-test.sh

It adds a prefix to the test report names so that it's easier to look them up in the Jenkins UI. In the past, the report name was created calling `uname` in the remote VM, now it uses the metadata coming from the platform descriptors
Consistency about file names, and adding discoverability when reading reports in the Jenkins UI
- Completes #2245

chore: include suite, platform and tags in test reports name

---

.ci/Jenkinsfile

It uses the `junit2otel` apm-library step to collect OpenTelemetry traces and metrics for the project.
We'd like to start collecting traces, first to dogfood the test reports integration, second to collect useful information regarding SCM metrics from this project.

chore: start sending OTEL traces for the e2e

---

.backportrc.json
.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml
.mergify.yml

- chore: add 8.2 retiring 8.0
- fix: do not listen for tags
- chore: retire old 7.16 from jjbb
- chore(mergify): add 8.2 and retire 8.0
It updates the descriptors for backports: mergify and backport tool, to include 8.2 and retire 8.0 branches.
Finally, it polishes the JJBB to remove old branches (7.16) and to avoid listening for git tags
Keep automated tasks in sync with the current state of the maintenance branches

chore: backport settings

---

.ci/Jenkinsfile
internal/common/defaults.go

It bumps the stale agent version from 7.17.1 to 7.17.2
The 7.17.1 version disappeared from artifacts-api
I believe this upgrade agent scenario should be rewritten in a way that is not that sensible to the snapshot version, and instead uses a release version. For 7.17, it currently uses the branch's version minus 1 patch as a snapshot (see current changes), but this moving target is retired from the artifacts-api with certain frequency.
@v1v and I have mentioned a few times to detect the move and bump the stale agent version in an automated way, but I think it would be hiding the real problem of the sensitivity of this scenario.
@jlind23 @ph wdyt?
- Closes #2326 #2325 #2324 
- Relates https://github.com/elastic/e2e-testing/issues/1643

fix: bump stale agent to 7.17.2

---

.ci/schedule-daily.groovy

It adds 8.next-minor alias to the scheduled builds
8.next-minor relates to 8.2, which must be scheduled as a nightly
-

chore: add 8 next-minor to the scheduled builds

---

.ci/ansible/github-ssh-keys

Add ANdersonQ to github-ssh-keys
So I can ssh SSH into the Cloud machines to debug failing tests
- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have run the Unit tests (`make unit-test`), and they are passing locally~~
- ~~[ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally~~

Add AndersonQ to github-ssh-keys

---

.ci/ansible/github-ssh-keys

chore: add narph to ssh users (#2389)

---

e2e/TROUBLESHOOTING.md

- docs: document machine types
- docs: add that a pull request including backports is needed
- fix: right variable name
- docs: quote variables
- docs: document how to look up the IP address to SSH into the VMs
- docs: document how to run the tests
- chore: rename section
It documents how to run the test in the cloud machines, preparing the stack and the environment before to do that.
I had a pair-programming session with @AndersonQ to do it, and I took notes on what we did. We were missing these instructions.
- Closes #2400

docs: document the process of running the tests in the cloud machines

---

e2e/_suites/kubernetes-autodiscover/README.md
e2e/_suites/kubernetes-autodiscover/features/elastic_agent_standalone.feature

Explained how to run tests for a single scenario
Added docs on how to run a single scenario
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have run the Unit tests (`make unit-test`), and they are passing locally~~
- Relates #2434

how to run tests a single scenario

---

.ci/Jenkinsfile
internal/common/defaults.go

It bumps the version of the stale agent, from 7.17.2-SNAPSHOT to 7.17.3-SNAPSHOT
Because the 7.17.2-SNAPSHOT artifact was retired from the artifacts API, we need to bump the stale agent.
- The automated bump will be probably fixed with #2354

chore: bump stale agent for 7.17

---

.ci/ansible/playbook.yml

It adds three Ansible tasks to wait for the different services that represent the Elastic stack: Elasticsearch, Kibana and Fleet Server
The wait_for Ansible module will use the main ports for each service, including a delay of 10 seconds. The default max timout of 300 secs will be used.
We have detected that after launching the stack, the fleet-server container dies, causing all the following test scenarios to fail. We want to fail fast and not to create all the VMs in the case the stack is not healthy

chore: wait for the stack while provisioning

---

.ci/.e2e-tests-beats.yaml

- chore: copy default profile for beats
- chore: remove system integrations tests for Beats
It copies the default profile for running the e2e tests, removing the system-integration tests, as they are adding certain flakiness
Having a more stable test execution is critical for team success, and the system integration test suite is behaving with certain flakiness, which the product team is currently investigating.
- Completes https://github.com/elastic/beats/pull/31531

chore: skip system-integration scenarios for Beats

---

.ci/.e2e-tests-for-elastic-agent.yaml
.ci/.e2e-tests.yaml
.ci/Makefile
.ci/README.md
e2e/Makefile
e2e/README.md
e2e/TROUBLESHOOTING.md
e2e/_suites/fleet/features/apm_integration.feature
e2e/_suites/fleet/features/endpoint_integration.feature
e2e/_suites/fleet/features/fleet_mode.feature
e2e/_suites/fleet/features/integrations.feature
e2e/_suites/fleet/features/linux_integration.feature
e2e/_suites/fleet/features/permission_output_change.feature
e2e/_suites/fleet/features/preconfigured_policies.feature
e2e/_suites/fleet/features/running_on_top_of_beats.feature
e2e/_suites/fleet/features/stand_alone_mode.feature
e2e/_suites/fleet/features/system_integration.feature

It refactors the tag names in the cucumber feature files, for the following reasons: clarity, align with the intention of the scenario, and simplicity.
During this process, we detected the duplication of two examples in one scenario, causing it to be executed 4 times instead of 2.
KISS
- Close #373

chore: refactor cucumber tags

---

.ci/.e2e-tests-beats.yaml

It removes the APM Server helm charts scenarios for the execution of the e2e for Beats
Remove suites/scenarios that are not related to Beats, to avoid non-related failures

chore: do not run apm-server helm chart scenarios for Beats

---

.ci/ansible/requirements.txt

It fixes the broken dependency
The transitive dependency is breaking all Python tool chain
- Supersedes #2568
- Relates https://github.com/protocolbuffers/protobuf/issues/10051#issuecomment-1138392640

fix: use fixed, valid version for protobuffers

---

.ci/Makefile
.ci/README.md
.ci/scripts/yq.sh
.gitignore

- chore: support extracting env from the platforms file
- chore: support listing supported platforms
This PR adds three build commands:
- list-platforms: uses YQ to extract the top-level keys in the YAML file representing the available platforms
- set-env-PLATFORM: uses YQ to generate a .env file for the platform, so that it's possible to source it and avoid passing it to each build command
- set-env-stack: same as the previous one, but for the stack
It will simplify how the build scripts interact with the node: instead of passing the env vars again and again, it will simply generate the env file once, and print a help message to source it.
Therefore, when running the tests against multiple OS targets (Centos 8, Debian 11, Ubuntu 22.04...), the end user will simply need to source the …

chore: simplify extracting info from the supported platforms

---

.ci/Jenkinsfile
.ci/e2eTestingFleetDaily.groovy
.ci/e2eTestingHelmDaily.groovy
.ci/e2eTestingK8SAutodiscoveryDaily.groovy

It increases the build time from 1'5h to 2h
We have seen builds taking +90mins, causing failures in the upstream callers

chore: increase build timeout to 2h

---

.ci/jobs/e2e-testing-fleet-daily-mbp.yml
.ci/jobs/e2e-testing-helm-daily-mbp.yml
.ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
.ci/jobs/e2e-testing-mbp.yml
.ci/schedule-daily.groovy

Increases the build time in JJBB
Update definition of the builds
- Completes #2660

chore(jjbb): increase build timeout to 2h

---

.ci/.e2e-tests-beats.yaml

It updates the tags for fleet_mode, as they were changed in https://github.com/elastic/e2e-testing/pull/2496.
It's probably the beats file was created before the creation of the 8.3 branch, and it did not received a backport :shrug:
As a consequence, any build in 8.3 was not detecting the right cucumber tags for the fleet_mode scenarios, therefore those scenarios were not run.

fix: update fleet mode tags

---

pkg/downloads/versions.go

It prints out the state of the Github variables (commit SHA and repository) so that we can identify if the build was triggered by a Pull Request on Beats.
These variables are important for the execution of PRs on the elastic-agent and Beats repositories, as they pass the commit sha to look up the artifacts in the proper GCP storage bucket.
- Discovered while testing #2727

chore: log github checks variables

---

.ci/ansible/tasks/setup_test_script_windows.yml
e2e/_suites/fleet/README.md
e2e/_suites/helm/README.md
e2e/_suites/kubernetes-autodiscover/README.md
e2e/commons-test.mk

Increases the max timeout for test execution, controlled by `go test`, from 60m to 90m
We noticed a few test executions (i.e. fleet_mode on Windows2019) that take more than 1h, therefore the test is stopped with the following error:
> [2022-07-07T07:06:49.190Z] Test killed: ran too long (1h1m0s).
[2022-07-07T07:06:49.198Z] exit status 1
See https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-2770/detail/PR-2770/1/pipeline/785

chore: increase max test timeout in 'go test' command

---

.ci/Jenkinsfile
.ci/Makefile

It prepends the BUILD_URL to the instance ID so that it is formed by BUILD_URL_PLATFORM_SUITE_TAGS
We noticed that parallel builds could be destroying instances from concurrent builds, as the instanceID was formed by PLATFORM_SUITE_TAGS, which is not unique per build.
Prepending the BUILD_URL makes that instance ID unique.
- Caused by #2490

fix: do not destroy machines from concurrent builds

---

.ci/Makefile

Removes the `-vvvv` flag when executing SSH connections
Remove noise in the logs

chore: remove verbosity in SSH connections

---

.ci/Jenkinsfile
.ci/e2eTestingMacosDaily.groovy

It adds two input parameters to the Mac pipeline:
- GITHUB_CHECK_REPO: name of the repository where to look up the SHA. Default is the elastic-agent, and this should not be changed unless used by an upstream caller like Beats
- GITHUB_CHECK_SHA1: SHA of the commit in the above repo. The artifacts for the SHA must have been produced by the packaging job, therefore they live in a GCP bucket
If present, the e2e code will use them to download the artifacts for that commit, using them in the execution
To allow debug a Mac build

feat(ci): support passing a commit SHA to run the MacOS tests

---

.ci/README.md

It documents the Python version needed to interact with the build system.
The QA Source folks have faces errors in the build even when there have not been changes in the build system, which at first sight seemd weird. After debugging the issue, we identified the controller machines (the ones running Ansible) where using an outdated version og Python (3.7.x), which led to errors interacting with boto_core and the ec2 module.
With these changes we expect it's more clear what versions to use.
- Closes #2883 
Dockerising the build and running all the Make commands in an ephemeral docker run command using Python 3.9 will be super. We should create a build-tools machine for that

docs: add Python version

---

.ci/Jenkinsfile

It uses a retry in the Jenkins pipeline, wrapping the execution of the shell scripts that consolidates the Cucumber test reports.
We have detected a few cases where the docker pull command failed with this error:
> [2022-08-01T16:03:15.060Z] docker: Error response from daemon: Head "https://docker.elastic.co/v2/observability-ci/cucumber-html-reporter/manifests/latest": dial tcp 34.68.230.202:443: connect: connection refused.
Build URL: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/PR-2879/7/pipeline/807

fix: add resiliency when consolidating the cucumber reports

---

.ci/.e2e-platforms.yaml
.ci/.e2e-tests-beats.yaml
.ci/.e2e-tests-daily.yaml
.ci/.e2e-tests-for-elastic-agent.yaml
.ci/.e2e-tests.yaml
.ci/Makefile
.ci/README.md

It renames the platform from `debian_amd64` to `debian_10_amd64`
It stands it clear what version of Debian is used.
Besides that, it will help with the backports, to 7.17 and 8.3, as Mergify will find conflicts with the platform names

chore: use a more descriptive name for debian 10

---

e2e/_suites/fleet/features/upgrade_agent.feature

It removes the 8.2-SNAPSHOT example from the Scenario outline representing the upgrade agent tests.
In the light of the appearance of 8.5-SNAPSHOT, 8.2-SNAPSHOT dissapeared from the artifacts API. Therefore any usage of that version needs to be removed from any scenario.
And because the upgrade scenarios for each maintenance branch uses the previous version to perform the upgrades, we removed the version here in the 8.3 maintenance branch.

fix: retire 8.2-SNAPSHOT from upgrade tests

---

e2e/_suites/fleet/testresources/default_system_metrics.json
e2e/_suites/fleet/testresources/linux_metrics.json

Fix testcases for fleet, adding required fields into vars

Fix testcases for fleet api

---

.ci/.e2e-tests-daily.yaml
.ci/.e2e-tests.yaml

The Fleet test pipeline has been failing for months. This change eliminates a bunch of test scenarios while we work on stabilizing the tests to improve confidence in the suite.
Originally the goal was to run the Fleet mode and upgrade tests on Windows and Linux, but Windows is currently failing, so it is now only running on Ubuntu 22.
We're ignoring all of these failures because they're so flaky. We need to be able to gate Agent builds and Fleet releases with these tests
- Related to https://github.com/elastic/elastic-agent/issues/1174

Only run Fleet mode and upgrade tests on Ubuntu 22

---

.ci/e2eTestingFleetDaily.groovy
.ci/e2eTestingMacosDaily.groovy

Update the slack channel used for failures notifications.

Update slack channels

---

.ci/ansible/tasks/runners.yml

Cloud labeling

---

.ci/ansible/tasks/setup_test_script_windows.yml

this is fixed on Linux but not on windows

fix: interpolate stackRunner Ansible variable on windows

---

e2e/_suites/fleet/features/upgrade_agent.feature

There is a know issue fixed in agent where agents fail to upgrade because they download the wrong package (fixed in 8.6.0). This commit removes such versions from the test since they won't be released anymore (hence no point in backporting the fix).
This PR aims at removing the failures for the e2e test related to elastic agent upgrade
Make sure that relevant elastic agent versions are tested reliably.
-

Remove known non-working agent versions

---

.ci/.e2e-tests-daily.yaml
.ci/scripts/install-dependencies.sh
.github/workflows/golangci-lint.yml
e2e/_suites/fleet/features/manage_integrations.feature
e2e/_suites/fleet/integrations.go
e2e/_suites/fleet/system_integration.go
e2e/_suites/fleet/testresources/windows.json

Code added for adding Windows integration to fleet suite.
As one of the core integration, so checking out, if integration is available and added to policy without any errors.
-

Fixes for #3361 : Adding Windows integration successfully  to test Policy

---

internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
internal/config/compose/services/elastic-agent/docker-compose.yml
internal/config/compose/services/elasticsearch/docker-compose.yml
internal/config/compose/services/kibana/docker-compose.yml
internal/config/compose/services/metricbeat/docker-compose.yml

Otherwise the `updatecli` won't work.

use pinned versions

---

.github/workflows/pull-request.yml
.pre-commit-config.yaml

remove duplicated entry and avoid failures for the stack.version

fix pre-commit linting

---

.github/workflows/junit-test-reporter.yml
.github/workflows/opentelemetry.yml
.github/workflows/pre-commit.yml
.github/workflows/pull-request.yml

Use the composite action from the library and avoid running twice for PRs.

github-action: listen for push into the active branches and use opentelemetry composite action

---

e2e/_suites/fleet/features/upgrade_agent.feature

Remove usage of old 7.17.10-SNAPSHOT agent version for upgrade tests and replace it with the 7.17.10 release
It seems that downloading and installing an old snapshot is causing build failures.
In any event, it's best to use official releases whenever possible (the snapshot had been introduced because of a backport that was not yet released at the time)
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have run the Unit tests (`make unit-test`), and they are passing locally~~
- ~~[ ] I have run the End-2-End tests for the suite …

Change old agent snapshot version to official release

---

.mergify.yml

Mergify support for the new CI

mergify: use GitHub checks and add backports
